local lang = RSRG.Languages["en"]

lang["#CONTROL_BINDCHECKER_TITLE"] = "Missing Controls detected!"
lang["#CONTROL_BINDCHECKER_SUBTITLE"] = "Resurgence replaces default Garrysmod controls, if these controls are not bound, you will have difficulty playing the game."
lang["#CONTROL_BINDCHECKER_FOOTNOTE"] = "Click Open Garrysmod Menu, go \"Options\", select \"Keyboard\", and bind these keys, or click \"Use Defaults\" for the optimal experience.\nRevalidate Controls after you're done."
lang["#CONTROL_BINDCHECKER_REVALIDATE"] = "Revalidate Controls"
lang["#CONTROL_BINDCHECKER_OPENMENU"] = "Open Garrysmod Menu"
lang["#CONTROL_BINDCHECKER_PLAYANYWAY"] = "Play Anyway"
lang["#CONTROL_BINDCHECKER_PLAYANYWAY_CONFIRM"] = "Are you sure you want to play without binding these controls?\nYou may experience Errors or be unable to Play."
lang["#CONTROL_BINDCHECKER_NOTVALIDATED"] = "Missing Bindings are Still Detected."
lang["#CONTROL_BINDCHECKER_VALIDATED"] = "All Controls Validated!\nYou can now play the game."

lang["#CONTROL_AMMOTYPE"] = "Change Ammo Types / Weapon Menu (Hold)"
lang["#CONTROL_MELEENADE"] = "Melee Power Attack / Gun Bash / Grenade (Hold)"
lang["#CONTROL_ACCEPTINVITE"] = "Accept Invite"
lang["#CONTROL_DECLINEINVITE"] = "Decline Invite"
lang["#CONTROL_COMMUNITY"] = "Open Community Menu"
lang["#CONTROL_CAMERA"] = "Camera Mode"
lang["#CONTROL_PING"] = "Party Ping"
lang["#CONTROL_PIPBOY"] = "Open Pip-Boy / Toggle Light (Hold)"
lang["#CONTROL_INTERACT"] = "Interact"
lang["#CONTROL_ATTACK"] = "Attack / Shoot"
lang["#CONTROL_AIM"] = "Aim / Parry"
lang["#CONTROL_AIM"] = "Aim / Parry"
lang["#CONTROL_RELOAD"] = "Reload / Toggle Weapon Equip (Hold)"
lang["#CONTROL_HOTKEY1"] = "Hotkey 1"
lang["#CONTROL_HOTKEY2"] = "Hotkey 2"
lang["#CONTROL_HOTKEY3"] = "Hotkey 3"
lang["#CONTROL_HOTKEY4"] = "Hotkey 4"
lang["#CONTROL_HOTKEY5"] = "Hotkey 5"
lang["#CONTROL_HOTKEY6"] = "Hotkey 6"
lang["#CONTROL_HOTKEY7"] = "Hotkey 7"
lang["#CONTROL_HOTKEY8"] = "Hotkey 8"
lang["#CONTROL_HOTKEY9"] = "Hotkey 9"
lang["#CONTROL_ZOOMIN"] = "Zoom In"
lang["#CONTROL_ZOOMOUT"] = "Zoom Out"

lang["#BINDING_PURPOSE"] = "Resurgence Purpose: $control"
lang["#BINDING_DEFAULT"] = "Default Binding: $key"
lang["#BINDING_CURRENT"] = "Currently bound to: $command"

-- Shows as "currently bound to Nothing in the bind checker"
lang["#BINDING_NOTHING"] = "Nothing"

RELOADSCHEMA = true