local lang = RSRG.Languages["en"]


-- █████╗ ███╗   ███╗███╗   ███╗ ██████╗
--██╔══██╗████╗ ████║████╗ ████║██╔═══██╗
--███████║██╔████╔██║██╔████╔██║██║   ██║
--██╔══██║██║╚██╔╝██║██║╚██╔╝██║██║   ██║
--██║  ██║██║ ╚═╝ ██║██║ ╚═╝ ██║╚██████╔╝
--╚═╝  ╚═╝╚═╝     ╚═╝╚═╝     ╚═╝ ╚═════╝

---ENERGY
lang["#SEC_NAME"] = "Small Energy Cell"
lang["#MFC_NAME"] = "Microfusion Cell"
lang["#MFC_OC_NAME"] = "Microfusion Cell, Over Charge"
lang["#MFC_MC_NAME"] = "Microfusion Cell, Max Charge"
lang["#MFC_BULK_NAME"] = "Microfusion Cell, Bulk"
lang["#MFC_ND_NAME"] = "Leaking Microfusion Cell"
lang["#ECP_NAME"] = "Electron Charge Pack"
lang["#ECP_OC_NAME"] = "Electron Charge Pack, Over Charge"
lang["#ECP_MC_NAME"] = "Electron Charge Pack, Max Charge"
lang["#ECP_BULK_NAME"] = "Electron Charge Pack, Bulk"
lang["#PLASMACARTRIDGE_NAME"] = "Plasma Cartridge"
lang["#ALIENPOWERCELL_NAME"] = "Alien Power Cell"
lang["#ALIENPOWERMODULE_NAME"] = "Alien Power Module"
---HANDGUN
lang["#9MM_NAME"] = "9mm"
lang["#9MM_AP_NAME"] = "9mm AP"
lang["#9MM_HP_NAME"] = "9mm HP"
lang["#9MM_+P_NAME"] = "9mm +P"
lang["#9MM_ND_NAME"] = "Old 9mm"
lang["#10MM_NAME"] = "10mm"
lang["#10MM_AP_NAME"] = "10mm AP"
lang["#10MM_HP_NAME"] = "10mm HP"
lang["#10MM_+P_NAME"] = "10mm +P"
lang["#38_NAME"] = ".38 Special"
lang["#38_ND_NAME"] = "Old .38 Special"
lang["#357_NAME"] = ".357 Mag LRN"
lang["#357_HP_NAME"] = ".357 Mag JSP"
lang["#357_HC_NAME"] = ".357 Mag +P HCLFN"
lang["#357_ND_NAME"] = "Old .357 Mag"
lang["#44_NAME"] = ".44 Mag LRN"
lang["#44_SPL_NAME"] = ".44 Special"
lang["#44_HP_NAME"] = ".44 Mag JSP"
lang["#44_HC_NAME"] = ".44 Mag +P HCLFN"
lang["#45ACP_NAME"] = ".45 Auto"
lang["#45ACP_HP_NAME"] = ".45 Auto HP"
lang["#45ACP_+P_NAME"] = ".45 Auto +P"
lang["#14.5MM_NAME"] = "14mm LFN"
lang["#12.7MM_NAME"] = "12.7mm LFN"
lang["#12.7MM_AP_NAME"] = "12.7mm JHP"
lang["#12.7MM_HP_NAME"] = "12.7mm HP"
---RIFLE
lang["#22LR_NAME"] = ".22LR"
lang["#22LR_HP_NAME"] = ".22LR HP"
lang["#22LR_PLINK_NAME"] = ".22LR Plinking"
lang["#2MM_NAME"] = "2mm EC"
lang["#4.7MM_NAME"] = "4.7mm Caseless"
lang["#5MM_NAME"] = "5mm"
lang["#5MM_AP_NAME"] = "5mm AP"
lang["#5MM_HP_NAME"] = "5mm HP"
lang["#5.56MM_NAME"] = "5.56mm"
lang["#5.56MM_AP_NAME"] = "5.56mm AP"
lang["#5.56MM_HP_NAME"] = "5.56mm HP"
lang["#5.56MM_MATCH_NAME"] = "5.56mm Match"
lang["#223_NAME"] = ".223"
lang["#223_ND_NAME"] = "Old .223"
lang["#7.62MM_NAME"] = "7.62x39"
lang["#7.62MM_AP_NAME"] = "7.62x39 AP"
lang["#7.62MM_MATCH_NAME"] = "7.62x39 Match"
lang["#308_NAME"] = ".308"
lang["#308_AP_NAME"] = ".308 AP"
lang["#308_HP_NAME"] = ".308 SP"
lang["#308_MATCH_NAME"] = ".308 Match"
lang["#3006_NAME"] = ".30-06"
lang["#3006_AP_NAME"] = ".30-06 AP"
lang["#9X39MM_NAME"] = "9x39mm"
lang["#9X39MM_AP_NAME"] = "9x39mm AP"
lang["#4570_NAME"] = ".45-70 GOVT"
lang["#4570_HP_NAME"] = ".45-70 HP"
lang["#4570_HC_NAME"] = ".45-70 +P HCLFN"
lang["#50BMG_NAME"] = ".50 BMG"
lang["#50BMG_MATCH_NAME"] = ".50 BMG Super Match"
--SHOTSHELL
lang["#12G_NAME"] = "12GA 00Buck"
lang["#12G_SLUG_NAME"] = "12GA Slug"
lang["#12G_PSLUG_NAME"] = "12GA Pulse Slug"
lang["#12G3_NAME"] = "12GA 00Buck 3'' Mag"
lang["#12G3_SLUG_NAME"] = "12GA Slug 3'' Mag"
lang["#12G_FLECHETTE_NAME"] = "12GA Flechette"
lang["#12G_DRAGONS_BREATH_NAME"] = "12GA Dragon's Breath"
lang["#20G_NAME"] = "20GA Buck"
lang["#20G_SLUG_NAME"] = "20GA Slug"
---ORDANANCE
lang["#ROCKET_NAME"] = "Rocket"
lang["#ROCKET_CANISTER_NAME"] = "Canister Rocket"
lang["#MISSILEHE_NAME"] = "HE Missile"
lang["#MININUKE_NAME"] = "Mini-Nuke"
lang["#25MM_NAME"] = "25mm Grenade"
lang["#40MM_NAME"] = "40mm Grenade"
lang["#FUELGAS_NAME"] = "Flamer Fuel"
lang["#FUELNAPALM_NAME"] = "Flamer Fuel, Optimized"
lang["#FUELHOMEMADE_NAME"] = "Improvised Flamer Fuel"

---OTHER
lang["#DART_NAME"] = "Dart"
lang["#DART_STIM_NAME"] = "Dart, Stimpak"
lang["#DART_RADSCOPRION_NAME"] = "Dart, Radscorpion"
lang["#DART_CONCENTRATEDRADSCOPRION_NAME"] = "Dart, Concentrated Radscorpion"
lang["#DART_GREENGECKO_NAME"] = "Dart, Green Gecko"
lang["#DART_CONCENTRATEDGREENGECKO_NAME"] = "Dart, Concentrated Green Gecko"
lang["#DART_FATIGUE_NAME"] = "Dart, Fatigue"
lang["#DART_BLIGHT_NAME"] = "Dart, Blight"
lang["#DART_FEVCURLING11_NAME"] = "Dart, FEV Curling-11"
lang["#DART_CONCENTRATEDBLIGHT_NAME"] = "Dart, Concentrated Blight"
lang["#DART_RAD_NAME"] = "Dart, Radioactive"
lang["#DART_SBLOCK_NAME"] = "Dart, Stimblock"
lang["#DART_CBLOCK_NAME"] = "Dart, Chemblock"
lang["#DART_PSYCHO_NAME"] = "Dart, Psycho"
lang["#DART_BUFFOUT_NAME"] = "Dart, Buffout"
lang["#DART_SLOTH_NAME"] = "Dart, Sloth"
lang["#DART_HYDRA_NAME"] = "Dart, Hydra"
-- lang["#DART_GOBLIN_NAME"] = "Dart, Goblin" -- This shit is so dumb. I hate it.
lang["#RAILSPIKE_NAME"] = "Railspike"
lang["#RAILSPIKE_SPIKY_NAME"] = "Spiky Railspike"
lang["#RAILSTAKE_NAME"] = "Railstake"

------------------------------------------------------------------
---Ammo Desc
------------------------------------------------------------------
--ENERGY
lang["#SEC_DESC"] = "The Small Energy Cell is a high-capacity battery that contains a considerable amount of energy for it's size.\n\nBecause it doesn't produce power like the Microfusion cell, it is more suited to applications that require less, such as energy based hanguns."
lang["#SEC_OC_DESC"] = "The Overcharged variant of a small energy cell\n\nUses a non-standard method for containing energy, making the battery more unstable, but providing a higher energy output, resulting in a higher damage at the cost of weapon condition."
lang["#MFC_DESC"] = "A weapons grade power source, commonly found in the use of slow firing weapons.\n\nThe Microfusion Cell is a miniature self contained fusion plant, capable of generating and containing a massive amount of energy.\n\nWhile it had many applications in the old world, today, It is mainly used to power various energy rifles."
lang["#MFC_OC_DESC"] = "A weapons grade power source, commonly found in the use of slow firing weapons.\n\nOver Charged Variant.\n\nIncreases damage output and armor penetration effect, at the cost of quicker weapon degradation."
lang["#MFC_MC_DESC"] = "A weapons grade power source, commonly found in the use of slow firing weapons.\n\nMax Charged Variant.\n\nGreatly increases damage output and armor penetration effect, at the cost of heavy weapon degradation."
lang["#MFC_BULK_DESC"] = "A weapons grade power source, commonly found in the use of slow firing weapons.\n\nBulk Variant.\n\nReduces weapon degradation, at the cost of lower damage output, and no inherent armor penetration."
lang["#MFC_ND_DESC"] = "A damaged Microfusion Cell, recovered from someone else's trash.\n\n#STARTER_AMMO_DISCLAIMER"
lang["#ECP_DESC"] = "A weapons grade power source, commonly found in the use of rapid firing weapons.\n\nUnlike Small Energy Cells which are not capable of high enough energy transfer, and Microfusion Cells which are insufficent for rapid discharge, ECPs contain both the charge and power load to feed the most intense Pre-War laser weaponry."
lang["#ECP_OC_DESC"] = "A weapons grade power source, commonly found in the use of rapid firing weapons.\n\nOver Charged Variant.\n\nIncreases damage output and armor penetration effect, at the cost of quicker weapon degradation."
lang["#ECP_MC_DESC"] = "A weapons grade power source, commonly found in the use of rapid firing weapons.\n\nMax Charged Variant.\n\nGreatly increases damage output and armor penetration effect, at the cost of heavy weapon degradation."
lang["#ECP_BULK_DESC"] = "A weapons grade power source, commonly found in the use of rapid firing weapons.\n\nBulk Variant.\n\nReduces weapon degradation, at the cost of lower damage output, and no inherent armor penetration."
lang["#PLASMACARTRIDGE_DESC"] = "The Plasma Cartridge is a small, green container and is used by all varieties of plasma weapons."
lang["#ALIENPOWERCELL_DESC"] = "Alien Power Cell." -- NEED DESC
lang["#ALIENPOWERMODULE_DESC"] = "Alien Power Module." -- NEED DESC
--HANDGUN
lang["#9MM_DESC"] = "A light handgun cartridge, commonly found in the use of pistols and sub-machine guns.\n\nAlthough it has largely been retired by law enforcement in favor of the 10mm, this round maintains a steady following in several parts of the world due to its low cost and controllability."
lang["#9MM_AP_DESC"] = "A light handgun cartridge, commonly found in the use of pistols and sub-machine guns.\n\nArmor Piercing Variant\n\nAn Overpressure round used in submachineguns by the military, these bullets contain a hardened penetrator for use against armored targets."
lang["#9MM_HP_DESC"] = "A light handgun cartridge, commonly found in the use of pistols and sub-machine guns.\n\nHollow Point Variant\n\nA defensive round used by Law Enforcment and civilians alike, these bullets expand in soft targets for greater lethality, but fail against armor."
lang["#9MM_+P_DESC"] = "A light handgun cartridge, commonly found in the use of pistols and sub-machine guns.\n\nOverpressure Variant\n\nAmmo that has been intentionally loaded to higher internal pressure. This ensures higher projectile velocity and stopping power, and affords a slight armor piercing ability but at the cost of requiring more maintenance than usual."
lang["#9MM_ND_DESC"] = "A poorly aged handgun cartridge.\n\n#STARTER_AMMO_DISCLAIMER"
lang["#38_DESC"] = "A light handgun cartridge, commonly found in the use of snubnose revolvers.\n\nThis round can be used in most guns chambered for .357.\n\n.38 Special and .357 are both straight-wall, rimmed cartridged, sharing the same bullet diameter. The former, however, is much lower powered and causes less wear to firearms."
lang["#38_ND_DESC"] = "An old .38 round. Could still be shot.\n\n#STARTER_AMMO_DISCLAIMER"
lang["#357_DESC"] = "A medium handgun cartridge, popular for hunting small game. Used in revolvers and certain rifles.\n\nLead-Round-Nose loads use a simple lead bullet, and are relatively common and cheap."
lang["#357_HP_DESC"] = "A medium handgun cartridge, popular for hunting small game. Used in revolvers and certain rifles.\n\nHunting variant\n\nIntended for small to medium game, Soft Points mushroom on impact, taking prey quickly and effectivly.\n\nEfficacy suffers against armor."
lang["#357_HC_DESC"] = "A heavy handgun cartridge, popular for hunting large game. Used in revolvers and certain rifles.\n\nDangerous Game variant\n\nIntended for use against things larger, faster, and deadlier than you, Hard-Cast-Lead-Flat-Nose use a hardended slug with the maximum charge possible to punch through thickened animal hide.\n\nThis punishing round is hard to find and dramaticaly shortens a firearms life."
lang["#357_ND_DESC"] = "Still very powerful for its age.\n\n#STARTER_AMMO_DISCLAIMER"
lang["#10MM_DESC"] = "A common cartridge, found in the use of pistols and sub-machine guns.\n\nAdopted by numerous law enforcement agencies, it is standard issue caliber for the B.A.D.T.F.L."
lang["#10MM_AP_DESC"] = "A common cartridge, found in the use of pistols and sub-machine guns.\n\nArmor Piercing Variant\n\nA high-pressure round used in submachineguns by the military, these bullets contain a hardened penetrator for use against armored targets."
lang["#10MM_HP_DESC"] = "A common cartridge, found in the use of pistols and sub-machine guns.\n\nHollow Point Variant\n\nA defensive round used by Law Enforcment and civilians alike, these bullets expand in soft targets for greater lethality, but fail against armor."
lang["#10MM_+P_DESC"] = "A common cartridge, found in the use of pistols and sub-machine guns.\n\nOverpressure Variant\n\nAmmo that has been intentionally loaded to higher internal pressure. This ensures higher projectile velocity and stopping power, and affords a slight armor piercing ability but at the cost of requiring more maintenance than usual."
lang["#44_DESC"] = "A heavy handgun cartridge, popular for hunting medium to large game. Used in various sidearms and certain rifles.\n\nLead-Round-Nose loads use a simple lead bullet, and are relatively common and cheap."
lang["#44_SPL_DESC"] = "A medium handgun cartridge, commonly found in the use of revolvers.\n\nThis round can be used in most guns chambered for .44.\n\n.44 Special and .44 are both straight-wall, rimmed cartridged, sharing the same bullet diameter. The former, however, is much lower powered and causes less wear to firearms."
lang["#44_HP_DESC"] = "A heavy handgun cartridge, popular for hunting medium to large game. Used in revolvers and certain rifles.\n\nHunting variant\n\nIntended for small to medium game, Soft Points mushroom on impact, taking prey quickly and effectivly.\n\nEfficacy suffers against armor."
lang["#44_HC_DESC"] = "A heavy handgun cartridge, popular for hunting meduim to large game. Used in revolvers and certain rifles.\n\nDangerous Game variant\n\nIntended for use against things larger, faster, and deadlier than you, Hard-Cast-Lead-Flat-Nose use a hardended slug with the maximum charge possible to punch through thickened animal hide.\n\nThis punishing round is hard to find and dramaticaly shortens a firearms life."
lang["#45ACP_DESC"] = "A large caliber handgun cartridge, found in the use of pistols and sub-machine guns.\n\nWant to deal more damage without dropping the caps for Hollow Points? The answer is simple: Make a bigger hole."
lang["#45ACP_HP_DESC"] = "A large caliber handgun cartridge, found in the use of pistols and sub-machine guns.\n\nHollow Point Variant\n\nA defensive round used by Law Enforcment and civilians alike, these bullets expand in soft targets for greater lethality, but fail against armor."
lang["#45ACP_+P_DESC"] = "A large caliber handgun cartridge, found in the use of pistols and sub-machine guns.\n\nOverpressure Variant\n\nAmmo that has been intentionally loaded to higher internal pressure. This ensures higher projectile velocity and stopping power, and affords a slight armor piercing ability but at the cost of requiring more maintenance than usual."
lang["#14.5MM_DESC"] = "A Soviet manufactured round comparable to the .50 AE.\n\nWith a bullet diameter of over one half-inch, this round by far the largest handgun cartridge found in the Frontier Wasteland.\n\nHard to find and very sought after."
lang["#12.7MM_DESC"] = "A Hauer Premium civic defense round is large pistol cartridge comparable to the .50 AE.\n\nWith a bullet diameter of one half-inch, this round by far the one of the largest handgun cartridge found in the Frontier Wasteland.\n\nHard to find and very sought after."
lang["#12.7MM_AP_DESC"] = "A Hauer Premium civic defense round is large pistol cartridge that tears through anything it touches.\n\nJacketed Hollow Point Variant\n\nThis round manages to mostly keep the firepower of an HP round while allowing further penetration of most armors and hides.\n\nThis punishing round is hard to find and dramaticaly shortens a firearms life."
lang["#12.7MM_HP_DESC"] = "A Hauer Premium civic defense round is large pistol cartridge that tears through anything it touches.\n\nHollow Point Variant\n\nUnlike most loads in this caliber, this round features a Hollow-Point, trading penetration for a massive wound channel.\n\nHard to find and very sought after."
--RIFLE
lang["#22LR_DESC"] = "The .22LR is a very low powered rifle cartridge, commonly found in the use of rifles and handguns.\n\nThe .22LR was used as a commercial small game hunting and recreational shooting round.\n\nIt has a self-contained ''rimfire'' primer and thus cannot be broken down to gain small pistol primers, nor can it be crafted."
lang["#22LR_HP_DESC"] = "The .22LR is a very low powered rifle cartridge, commonly found in the use of rifles and handguns.\n\nHollow Point Variant\n\nPrimarily used for small game hunting and pest control, these bullets expand in soft targets for greater lethality, but hopelessly fail against armor and heavily starched clothing."
lang["#22LR_PLINK_DESC"] = "The .22LR is a very low powered rifle cartridge, commonly found in the use of rifles and handguns. A cheaply made round, even for .22LR, plinking ammo was mass produced for ''quantity over quality''.\n\nThough less powerful, accurate, and reliable than standard .22LR ammunition, plinking ammo can usually be found in abundance."
lang["#2MM_DESC"] = "An ultra lightweight, miniature round. Used in electromagnetic propulsion weapons.\n\nWith speed outmatched only by rarity, these hyper-velocity cartridges are fatal to all known forms of Pre-War armor."
lang["#4.7MM_DESC"] = "One of the rarest forms of ammo available in the wastland, and used for some of the more premier Pre-War weapons.\n\nThese hyper-velocity cartridges are fatal to all known forms of Pre-War armor."
lang["#5MM_DESC"] = "Despite being a dated round even before the war, this cartridge is utilized by many automatic weapons.\n\nCounter-balancing a low damage yeild, the 5mm round has a high velocity and can penatrate through armor and light cover."
lang["#5MM_AP_DESC"] = "Despite being a dated round even before the war, this cartridge is utilized by many automatic weapons.\n\nArmor Piercing Variant\n\nUsing a specially hardened penetrator and shaped nose, the anti-armor nature of the 5mm is extended even further.\n\nThese hyper-velocity cartridges are fatal to all known forms of Pre-War armor."
lang["#5MM_HP_DESC"] = "Despite being a dated round even before the war, this cartridge is utilized by many automatic weapons.\n\nHollow Point Variant\n\nUtilized by the military as an anti-personel round, these bullets expand in soft targets for greater lethality, but fail against armor."
lang["#5.56MM_DESC"] = "An intermediate rifle cartridge.\n\nThis lightweight round has high velocity and adequate penetration.\n\nRelatively easy to find and moderately priced, this round was adapted from .223 for international military use."
lang["#5.56MM_AP_DESC"] = "An intermediate rifle cartridge.\n\nArmor Piercing Variant\n\nIssued alsmost exclusively to Armed Forces, these bullets contain a hardened penetrator for use against most forms of armor and light cover."
lang["#5.56MM_HP_DESC"] = "An intermediate rifle cartridge.\n\nHollow Point Variant\n\nA defensive round used by Law Enforcment and civilians alike, these bullets expand in soft targets for greater lethality, but fail against armor."
lang["#5.56MM_MATCH_DESC"] = "An intermediate rifle cartridge.\n\nMatch Grade Variant\n\nCarefully hand-loaded with a Match Grade projectile, this round far exceeds mass produced ammo at both precision and accuracy at long range."
lang["#223_DESC"] = "An intermediate rifle cartridge.\n\nThis round can be used in any gun chambered for 5.56.\n\n.223 and 5.56 are both bottle-necked, rifle cartridges, sharing the same bullet diameter. The former, however, is lower powered and causes less wear to firearms."
lang["#223_ND_DESC"] = "A slightly rusted rifle cartridge.\n\nThis round can be used in any gun chambered for 5.56mm.\n\n#STARTER_AMMO_DISCLAIMER"
lang["#7.62MM_DESC"] = "An intermediate rifle cartridge. \n\nA 30 caliber round with a moderate charge, it's metric name betrays its origin overseas."
lang["#7.62MM_AP_DESC"] = "An intermediate rifle cartridge. \n\nA 30 caliber round with a moderate charge, this one has an armor penetrating projectile."
lang["#7.62MM_MATCH_DESC"] = "An intermediate rifle cartridge. \n\nA Match Grade Variant, carefully hand-loaded for improved performance."
lang["#9X39MM_DESC"] = "A high-caliber, subsonic round designed for stealth and precision, the 9x39mm is prized by wastelanders who prefer to operate in the shadows. Originally developed by the pre-war Soviet Union for use with suppressed rifles, this round is perfect for quiet takedowns and is capable of punching through light armor with ease. Though it's rare to find, it can be a game-changer in the right hands."
lang["#9X39MM_AP_DESC"] = "A high-caliber, subsonic round designed for stealth and precision, the 9x39mm is prized by wastelanders who prefer to operate in the shadows. Originally developed by the pre-war Soviet Union for use with suppressed rifles, this round is perfect for quiet takedowns and is capable of punching through light armor with ease. This is the armor-piercing variant.\n\nQuite devistating to any unsuspecting targets."
lang["#308_DESC"] = "A popular rifle cartridge, commonly found in the use of sportsmen and militaries.\n\nKnown internationally as 7.62x51mm, these fully jacketed bullets were sold as a more affordable alternative to common hunting bullets of the day."
lang["#308_AP_DESC"] = "A popular rifle cartridge, commonly found in the use of sportsmen and militaries.\n\nArmor Piercing variant\n\nIssued almost exclusively to Armed Forces, these bullets contain a hardened penetrator for use against most forms of armor and light cover."
lang["#308_HP_DESC"] = "A popular rifle cartridge, commonly found in the use of sportsmen and militaries.\n\nHunting variant\n\nIntended for medium to large game, Soft Points mushroom on impact, taking prey quickly and effectivly.\n\nEfficacy suffers against armor."
lang["#308_MATCH_DESC"] = "A popular rifle cartridge, commonly found in the use of sportsmen and militaries.\n\nMatch Grade Variant\n\nCarefully hand-loaded with a Match Grade projectile, this round far exceeds mass produced ammo at both precision and accuracy at long range."
lang["#308_DESC"] = "A popular rifle cartridge, commonly found in the use of sportsmen and militaries.\n\nKnown internationally as 7.62x51mm, these fully jacketed bullets were sold as a more affordable alternative to common hunting bullets of the day."
lang["#3006_DESC"] = "Once a staple of pre-War military forces, .30-06 ammunition is a powerful, full-sized rifle cartridge originally used in the U.S. Army’s M1 Garand and other high-powered rifles. Though most production ceased after the Great War, these rounds are still prized by Wasteland marksmen for their stopping power and reliability when you can find them."
lang["#3006AP_DESC"] = "A full length, bottlenecked rifle cartridge, the .30-06 M2 AP round features a hardened steel core seated in a black-tipped, full metal jacketed bullet, crimped into a long brass case with a slight shoulder taper. The overall length and powder charge give it impressive muzzle velocity, making it deadly accurate at long range."

lang["#4570_DESC"] = "An ancient rifle cartridge, still in use today.\n\nThis timeless round is considered adequate for any North American big game.\n\nOriginally developed over 400 years ago for use with blackpowder, the .45-70 is one of the earliest U.S. military cartridges."
lang["#4570_HP_DESC"] = "An ancient rifle cartridge, still in use today.Hunting variant\n\nIntended for medium to large game, Soft Points mushroom on impact, taking prey quickly and effectivly.\n\nEfficacy suffers against armor."
lang["#4570_HC_DESC"] = "An ancient rifle cartridge, still in use today.\n\nDangerous Game variant\n\nIntended for use against things larger, faster, and deadlier than you, Hard-Cast-Lead-Flat-Nose use a hardended slug with the maximum charge possible to punch through thickened animal hide.\n\nThis punishing round is hard to find and dramaticaly shortens a firearms life."
lang["#50BMG_DESC"] = "The .50 Browning Machine Gun is a monsterously heavy cartridge, used exclusively in anti-material and vehicle mounted weaponry.\n\nThis mass-produced bullet, although simple in design, delivers a devistating payload."
lang["#50BMG_MATCH_DESC"] = "The .50 Browning Machine Gun is a monsterously heavy cartridge, used exclusively in anti-material and vehicle mounted weaponry.\n\nMatch Grade Variant\n\nCarefully hand-loaded with a Match Grade projectile, this round far exceeds mass produced ammo at both precision and accuracy at long range."
--SHOTSHELL
lang["#12G_SLUG_DESC"] = "A rifled slug, for use in smoothbore shotguns. \n\nRequiring a considerable amount of lead per round, this massive projectile was designed for hunting medium to large Game."
lang["#12G_PSLUG_DESC"] = "These slugs cause more damage to robots and enemies wearing power armor, and the target gets an extra kick from an electromagnetic pulse triggered by the impact."
lang["#12G_DESC"] = "A Shell used in Shotguns.\n\nDamage is divided amongst a cluster of pellets, making it devastating to soft targets, but more or less bounce off of heavy armor."
lang["#12G3_SLUG_DESC"] = "A Magnum rifled slug, for use in smoothbore shotguns.\n\nThe higher powder charge and solid copper slug of this shell means greater velocities, higher damage, and better penatration against medium armor.\n\nDrawbacks are higher recoil, premature weapon wear, and it kicks like a damn Bighorner."
lang["#12G3_DESC"] = "A Magnum Shell used in smoothbore shotguns.\n\nThe higher powder charge and copper-plated buckshot of this shell means greater velocities, higher damage, and better penatration against light armor.\n\nDrawbacks are higher recoil, premature weapon wear, and it kicks like a damn Bighorner."
lang["#12G_FLECHETTE_DESC"] = "A special armor piercing shell for shotguns.\n\nFlechettes are small metal darts ideal for piercing light armor. Though not as lethal as buckshot, flechettes serve as an effective answer to body armor.\n\nThey must be fired smoothbore, and are thus incompatible with rifled chokes."
lang["#12G_DRAGONS_BREATH_DESC"] = "A box marked with Oriental lettering and a dragon containing shells packed with magnesium pellets and bird shot that ignite when making contact with the air. Devastating to soft targets and even hard targets that have exposed flesh."
--ORDANANCE
lang["#ROCKET_DESC"] = "A rocket shell with a large explosive warhead."
lang["#ROCKET_CANISTER_DESC"] = "A rocket shell with large amount of shell shot loaded inside."
lang["#MISSILEHE_DESC"] = "A High-Explosive missile, meant to be fired from a missile launcher."
lang["#MININUKE_DESC"] = "A miniature atomic warhead, can be fired as-is from a FatMan, or be used in crafts of the destructive variety."
lang["#25MM_DESC"] = "A 25mm grenade designed for a Pre-War military launcher, explodes on contact.\n\nIn contrast to the more targeted use of missiles, these were often fired in rapid succession for area-of-effect."
lang["#40MM_DESC"] = "A 40mm grenade."
lang["#FUELGAS_DESC"] = "A cylinder containing an extremely flammable liquid fuel for flamethrowers."
lang["#FUELNAPALM_DESC"] = "A cylinder containing an extremely flammable liquid fuel for flamethrowers\n\nThis flamethrower fuel uses an advanced super-burn mix."
lang["#FUELHOMEMADE_DESC"] = "A cylinder containing an extremely flammable liquid fuel for flamethrowers.\n\nImprovised from crude materials, this formula runs extremely dirty, and will degrade weaponry at an alarming rate."

---OTHER
lang["#DART_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns."
lang["#DART_STIM_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nSupport Variant\n\nContaining a partial dose of the Pre-War wonder drug, Stimdarts are useful as a form of ''long-range first aid''."
lang["#DART_RADSCOPRION_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nPoison Variant\n\nFilled with venom from the fearsome Radscorpion, be sure to warn your target ''this might sting a little''."
lang["#DART_CONCENTRATEDRADSCOPRION_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nPoison Variant\n\nFilled with concentrated venom from the fearsome Radscorpion, be sure to warn your target ''this will hurt A LOT''."
lang["#DART_GREENGECKO_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nPoison Variant\n\nFilled with poison from the Green Gecko, it acts quickly, but doesn't last long."
lang["#DART_CONCENTRATEDGREENGECKO_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nPoison Variant\n\nFilled with concentrated poison from the Green Gecko, it acts quickly, and kills especially fast."
lang["#DART_FEVCURLING11_DESC"] = "Dart, FEV Curling-11." -- NEED DESC
lang["#DART_FATIGUE_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nPoison Variant\n\nContains a dose to wear out people from running."
lang["#DART_BLIGHT_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nPoison Variant\n\nContains a disgusting sludge of viscous green fluid. This surely cant be good for you."
lang["#DART_BLIGHT_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nPoison Variant\n\nContains a disgusting sludge of viscous green fluid. In its concentrated form it looks more like a solid."
lang["#DART_RAD_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nPoison Variant\n\nLoaded with radioactive liquid, these ''dirty darts'' are best used against human targets, not mutants."
lang["#DART_SBLOCK_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nCounter-Support Variant\n\nA specialized drug cocktail designed to subdue the body's ability to heal, rendering target-consumed healing items like stimpaks temporarily usesless."
lang["#DART_CBLOCK_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nCounter-Support Variant\n\nA specialized drug cocktail designed to subdue the body's adrenal system, rendering target-consumed combat chems like Buffout temporarily usesless."
lang["#DART_PSYCHO_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nSupport Variant\n\nContaining a partial dose of the Pre-War combat chem, Psychodarts are used to provide a temporary boost to friendlies without the risk of addiction."
lang["#DART_BUFFOUT_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nSupport Variant\n\nContaining a partial dose of the Pre-War steroid, Buffdarts are used to provide a temporary S.P.E.C.I.A.L. boost to friendlies without the risk of addiction."
lang["#DART_SLOTH_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nCounter-Support Variant\n\nContains the ingredients for tranquilizer. Not likely to put an active enemy to sleep immediately, but should slow them down enough to be hunted like prey."
lang["#DART_HYDRA_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nSupport Variant\n\nContaining a partial dose of the improvised wasteland chem, Hydradarts are used to quickly mend the broken limbs of friendlies without the risk of addiction."
-- lang["#DART_GOBLIN_DESC"] = "A ballistic dart tipped with a hypodermic needle and a hollow reservoir resembling a syringe, for use in specialty air guns.\n\nPoison Variant\n\n''Try goblin deez nuts'' - Dictator"
lang["#RAILSPIKE_DESC"] = "A large spike, meant for nailing in new train tracks. They're able to penetrate steel and other durable materials. Unfortunately, you can't exactly work on any trains in Fallout: Resurgence.\n\nGuess you'll have to shoot people with 'em."
lang["#RAILSPIKE_SPIKY_DESC"] = "A large spike, with assorted barbs welded onto it. It'll get a little caught on armor, but absolutely shred people's flesh.\n\nNote: They'll only cause bleeding when shooting ensouled beings."
lang["#RAILSTAKE_DESC"] = "A very, very, very large spike, no longer meant for nailing train tracks. They're able to penetrate tanks, let alone armor. \n\nThey're big and unwieldly though; you're unsure if they'll easily fit into a Railway Rifle."

-- Grenade Names
lang["#FRAGGRENADE_NAME"] = "Frag Grenade"
lang["#BASEBALLGRENADE_NAME"] = "Baseball Grenade"
lang["#SHORTFUSE_NAME"] = "Short-Fuse Grenade"
lang["#PLASGRENADE_NAME"] = "Plasma Grenade"
lang["#NUKAGRENADE_NAME"] = "Nuka-Grenade"
lang["#TINGRENADE_NAME"] = "Tin Grenade"
lang["#MFCGRENADE_NAME"] = "MFC Grenade"
lang["#TIMEBOMB_NAME"] = "Time Bomb"
lang["#TIMEBOMBHY_NAME"] = "Time Bomb, High Yield"
lang["#DYNO_NAME"] = "Dynamite"
lang["#DYNOLF_NAME"] = "Dynamite, Long Fuse"
lang["#GRENADEFLAME_NAME"] = "Incendiary Grenade"
lang["#MOLOTOV_NAME"] = "Fire Bottle"
-- Grenade Desc
lang["#FRAGGRENADE_DESC"] = "A small handheld explosive.\n\nFragments in to shrapnel, making the lethal range of the blast quite large.\n\nPull the pin and throw."
lang["#BASEBALLGRENADE_DESC"] = "Hollowed out baseballs filled with a Cherry Bomb, Pistol Powder and Fertilizer, which act as an improvised explosive mix. Low-tech and easy to make, the baseball grenade deals moderate explosive damage to nearby enemies."
lang["#SHORTFUSE_DESC"] = "A small handheld explosive.\n\nFragments in to shrapnel, making the lethal range of the blast quite large.\n\nSeems to be tampered with. Has a very short fuse."
lang["#PLASGRENADE_DESC"] = "An explosive device that yields a blast of superheated plasma.\n\nWhere it lack fragmentation and blast radius, it more than makes up for with damage."
lang["#NUKAGRENADE_DESC"] = "An extremely powerful improvised explosive device.\n\nIncorporates the radioactive properties of a relatively rare Nuka-Cola variant to produce an enhanced plasma blast.\n\n#WIP_DESC"
lang["#TINGRENADE_DESC"] = "The tin grenade is an improvised thrown explosive device,\nit is created at a workbench and assembled from scrap.\n\nA tin can is used for both the casing and for shrapnel, pistol powder for the explosive and duct tape to hold it all together.\n\n#WIP_DESC"
lang["#MFCGRENADE_DESC"] = "A powerful improvised weapon made from modified Microfusion Cells.\n\nLess damaging than a true Plasma Grenade, but with a wider area-of-effect.\n\n#WIP_DESC"
lang["#TIMEBOMB_DESC"] = "An improvised explosive weapon made with several sticks of dynamite.\n\n15 second timer.\n\n''Set it, DON'T forget it."
lang["#TIMEBOMBHY_DESC"] = "An improvised explosive weapon made with several sticks of dynamite.\n\n15 second timer.\n\nYou put more in, you get more out."
lang["#DYNO_DESC"] = "Sticks with fuses that stick out of them. Once lit, they are tossed at a hostile and will damage or kill them.\n\nMainly used in the mining, quarrying, construction, and demolition industries; it has a rather small blast radius for an explosive, which reduces its effectiveness against groups of enemies.\n\n#WIP_DESC"
lang["#DYNOLF_DESC"] = "Sticks with fuses that stick out of them. Once lit, they are tossed at a hostile and will damage or kill them.\n\nMainly used in the mining, quarrying, construction, and demolition industries; it has a rather small blast radius for an explosive, which reduces its effectiveness against groups of enemies.\n\nThis version has an fuse twice as long.\n\n#WIP_DESC"
lang["#GRENADEFLAME_DESC"] = "The AN-2051 Incendiary Grenade is a thrown explosive device that ignites after a small delay.\n\nTargets caught in the blast radius will take fire damage, and continue to burn for several seconds after the initial detonation.\n\nUseful for area denial and killing things with fire."
lang["#MOLOTOV_DESC"] = "An improvised thrown explosive that erupts in a fireball on contact.\n\nThe bottle is filled with a flammable substance, such as oil or gasoline, and topped with a cap and cloth as the igniter.\n\nJust light and throw, you little arsonist you.\n\n#WIP_DESC"

-- Mine Names
lang["#FRAGMINE_NAME"] = "Frag Mine"
lang["#PLASMAMINE_NAME"] = "Plasma Mine"
lang["#POWDERCHARGE_NAME"] = "Powder Charge"
lang["#FLAMEMINE_NAME"] = "Incendiary Mine"
lang["#FATMINE_NAME"] = "Fat-Mine"
lang["#BCMINE_NAME"] = "Bottlecap Mine"

-- Mine Desc
lang["#FRAGMINE_DESC"] = "A Pre-War explosive weapon used for area denial. Once activated; will explode if touched, or its proximity timer ends, blasting the offender with shrapnel.\n\nTry not to catch a new piercing."
lang["#PLASMAMINE_DESC"] = "A high-tech explosive weapon used for area denial. Once activated; will explode if touched, or its proximity timer ends, blasting the offender with plasma fire.\n\nDon't get your face melted off."
lang["#POWDERCHARGE_DESC"] = "An improvised explosive weapon used for area denial. Once activated; will explode if touched, or its proximity timer ends, blasting the offender with whatever crap you stuffed inside.\n\nI hope your wiring is good.\n\n#WIP_DESC"
lang["#FLAMEMINE_DESC"] = "A Pre-War explosive weapon used for area denial. Once activated; will explode if touched, or its proximity timer ends, blanketing the area with ignited napalm.\n\nDon't burn down the neighborhood, kid.\n\n#WIP_DESC"
lang["#FATMINE_DESC"] = "An improvised fusion weapon used for area denial. Once activated; will explode if touched, or its proximity timer ends, blasting the offender with the power of a small Sun.\n\nWhat kind of monster would create this?\n\n#WIP_DESC"
lang["#BCMINE_DESC"] = "An improvised explosive weapon disguised as junk. Once activated; will explode if touched, or its proximity timer ends, blasting the offender with pocket change.\n\n(Hand-written note from Mom not included)\n\n#WIP_DESC"

RELOADSCHEMA = true