local lang = RSRG.Languages["en"]

--███╗   ███╗███████╗██╗     ███████╗███████╗
--████╗ ████║██╔════╝██║     ██╔════╝██╔════╝
--██╔████╔██║█████╗  ██║     █████╗  █████╗
--██║╚██╔╝██║██╔══╝  ██║     ██╔══╝  ██╔══╝
--██║ ╚═╝ ██║███████╗███████╗███████╗███████╗
--╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝╚══════╝

lang["#BOTTLESHANK_NAME"] = "Bottle Shank"
lang["#STORMCUTTER_NAME"] = "Storm-Cutter"
lang["#ZAPGLOVE_NAME"] = "Zap Glove"
lang["#INDUSTRIALGAUNTLET_NAME"] = "Industrial Gauntlet"
lang["#PLASMACUTTER_NAME"] = "Plasma Cutter"
lang["#SWORD_NAME"] = "Katana"
lang["#PICKAXE_NAME"] = "Pickaxe"
lang["#COMBATKNIFE_NAME"] = "Combat Knife"
lang["#COMBATKNIFE_STARTER_NAME"] = "Bent Knife"
lang["#CROWBAR_NAME"] = "Crowbar"
lang["#FIREAXE_NAME"] = "Fire Axe"
lang["#DEATHCLAWWARAXE_NAME"] = "Deathclaw War Axe"
lang["#DEATHCLAWGAUNTLET_NAME"] = "Deathclaw Gauntlet"
lang["#FISTOFMORTIS_NAME"] = "Fist Of Mortis"
lang["#WARAXE_NAME"] = "War Axe"
lang["#KATANA_NAME"] = "Katana"
lang["#MACHETE_NAME"] = "Machete"
lang["#BOWIEKNIFE_NAME"] = "Bowie Knife"
lang["#BLOODNAP_NAME"] = "Blood-Nap"
lang["#REBARCLUB_NAME"] = "Rebar Club"
lang["#SHISHKEBAB_NAME"] = "Shishkebab"
lang["#SPIKEKNUCKLES_NAME"] = "Spiked Knuckles"
lang["#SUPERSLEDGE_NAME"] = "Super Sledge"
lang["#9IRON_NAME"] = "Nine Iron"
lang["#BASEBALLBAT_NAME"] = "Baseball Bat"
lang["#BASEBALLBAT_STARTER_NAME"] = "Aged Baseball Bat"
lang["#BASEBALLBAT_SCRAPYARD_NAME"] = "Scrapyard Smasher"
lang["#CATTLEPROD_NAME"] = "Cattle Prod"
lang["#SUPERCATTLEPROD_NAME"] = "Super Cattle Prod"
lang["#CLEAVER_NAME"] = "Cleaver"
lang["#DRESSCANE_NAME"] = "Dress Cane"
lang["#LEADPIPE_NAME"] = "Lead Pipe"
lang["#KITCHENKNIFE_NAME"] = "Kitchen Knife"
lang["#DRIVER_NAME"] = "Golf Driver"
lang["#NAILBOARD_NAME"] = "Nailboard"
lang["#HATCHET_NAME"] = "Hatchet"
lang["#PIPEWRENCH_NAME"] = "Pipe Wrench"
lang["#STRAIGHTRAZOR_NAME"] = "Straight Razor"
lang["#ROLLINGPIN_NAME"] = "Rolling Pin"
lang["#SLEDGE_NAME"] = "Sledgehammer"
lang["#WEIGHTBAR_NAME"] = "The 45 Pounder"
lang["#SHOVEL_NAME"] = "Shovel"
lang["#HOE_NAME"] = "Hoe"
lang["#SPADE_NAME"] = "Spade"
lang["#MOP_NAME"] = "Mop"
lang["#SWITCHBLADE_NAME"] = "Switchblade"
lang["#WAKAZASHI_NAME"] = "Wakazashi"
lang["#BUMPER_NAME"] = "Bumper Sword"
lang["#BATON_NAME"] = "Baton"
lang["#ALIENBATON_NAME"] = "Alien Shock Baton"
lang["#POWERFIST_NAME"] = "Power Fist"
lang["#SICKLE_NAME"] = "Sickle"
lang["#BONEKNIFE_NAME"] = "Bone Knife"
lang["#BONECLUB_NAME"] = "Bone Club"
lang["#BONESWORD_NAME"] = "Bone Sword"
lang["#CANOPENER_NAME"] = "Can Opener"
lang["#BEAREROFTHESTANDARD_NAME"] = "Bearer of the Standard"
lang["#ENDBOSSKNIFE_NAME"] = "Frank Horrigan's Wrist Knife"

--Melee Weapons Desc
lang["#BOTTLESHANK_DESC"] = "Broken bottle. The label is worn beyond recognition but you can make out two letters: B.S.\n\nCould be used as a close-combat weapon, if you're into that."
lang["#STORMCUTTER_DESC"] = "Forged in electricity, this large blade is capable of lopping off the head of any bandit that stands in your way.\n\nGo; test your blade. Make it one of legend."
lang["#ZAPGLOVE_DESC"] = "A glove with an electric grid on its knuckles, meant to provide an electrifying alternative to the layman's punch.\n\nWarning: Static Discharge after wearing this glove is notably powerful; make sure to ground yourself after."
lang["#INDUSTRIALGAUNTLET_DESC"] = "A glove with a sawblade attached to the back of the hand, meant to provide a bloody alternative to the layman's punch.\n\nWarning: Many users have accidentally lost fingers during removal. Proceed with caution."
lang["#PLASMACUTTER_DESC"] = "A cutting tool meant for quickly melting through steel in both industrial and rescue contexts.\n\nIn your hands? Certainly not rescuing anybody."
lang["#PICKAXE_DESC"] = "You unfortunately won't be able to easily mine cars with this.\n\nYou can easily mine for someone's grey matter though!"
lang["#SWORD_DESC"] = "Thousands of folds form this blade, crafted with pre-war steel, and forged in post-war blood.\n\nAll of that is irrelevant; this blade will be a sharp stick in a time of need."
lang["#BONECLUB_DESC"] = "A large bone made into a club ... \n\nyou're not going to use it, are you?"
lang["#SICKLE_DESC"] = "Fields of wheat are unfortunately few and far between in the wasteland. However, it's certainly sharp enough to separate a neck from a body.\n\nMurder is certainly more profitable than farming."
lang["#BONEKNIFE_DESC"] = "This primitive weapon is composed of a small piece of bone attached to a sharpened shard of obsidian. It'll cut through Deathclaw hide alright. "
lang["#BONESWORD_DESC"] = "This primitve weapon is composed of an antler attached to a sharpened slab of obsidian. This one won't just cut through Deathclaw hide, it'll behead it." 
lang["#COMBATKNIFE_DESC"] = "A Combat knife primarily used by military.\n\nA staple of close-quarters combat, which made it a popular knife among enthusiast and survivalists.\n\nCan be used as a bayonet on some weapons."
lang["#COMBATKNIFE_STARTER_DESC"] = "A crappy old knife. Once used by military, now deserted to time. Not very sharp, but could still poke something with it."
lang["#CROWBAR_DESC"] = "A simple bar of steel with a curved end, but an effective tool nonetheless.\nDepite it's intention as a utility device, the weight and balance of this tool make it an effective fallback as a melee weapon."
lang["#DEATHCLAWWARAXE_DESC"] = "An axe, made with two Deathclaw horns. Unfortunately Deathclaw horns aren't very sharp on the edges; this is functionally just an axe-shaped mace."
lang["#DEATHCLAWGAUNTLET_DESC"] = "The claws of this mighty fist were taken directly from a Deathclaw, used tear prey limb from limb. It fits snugly around your wrist.\n\nDeathclaw strength not included."
lang["#FISTOFMORTIS_DESC"] = "The claws of this mighty fist were taken directly from Unguem Mortis, the strongest Deathclaw in the west.\nIt looks pretty similar to a normal deathclaw gauntlet.\n\nUnlike a normal deathclaw gauntlet, you feel the strength of a Deathclaw flowing through your veins."
lang["#WARAXE_DESC"] = "A barbarian's War Axe, the type that Grognak himself would use!\n\nThere's nothing comical about how you're going to use it."
lang["#BOWIEKNIFE_DESC"] = "Originally created for dueling, the Bowie Knife represents the perfect answer to a knife fight.\n\nIt's likely also the perfect answer to a ghoul, but they couldn't have known that when they made it."
lang["#BLOODNAP_DESC"] = "The best thing about a knife?\n\nIt doesn't misfire, and it's always loaded."
lang["#FIREAXE_DESC"] = "The fire axe is a wooden handled axe with a heavy steel head intended for firefighting use. The long hardwood handle allows for sweeping attacks at reasonable distance and is partially rubber coated to ensure a good grip on the weapon.\n\nOriginally designed for breaking down walls and doors, this weapon can inflict severe damage to a soft target."
lang["#KATANA_DESC"] = "Deadly melee weapon.\nWorked steel alloy that has been perfectly sharpened and flattened over a thousand times to produce a perfect blade; useful for all styles of blade combat such as stabbing, slashing, and thrusting."
lang["#MACHETE_DESC"] = "Sharp melee weapon.\nReworked metal shaped into a medium length blade. one end sports a leather wrapped handle for a nice grasp.\nCan be used for a medium-ranged melee weapon."
lang["#REBARCLUB_DESC"] = "Makeshift blunt melee weapon.\nA rod of rebar for a handle and a chunk of concrete as a hammer-head; This is a questionable choice of weaponry, it is effective but unbalanced making it challenging to use.\nCan be used as a medium range weapon."
lang["#SHISHKEBAB_DESC"] = "Incendiary melee weapon.\nA very elaborate design of great intellect; Some kind of fuel flows out into a flame that surrounds the sharp flat blade of the device, truly wondrous.\nCan be used as an effective medium range weapon that can light it's targets ablaze."
lang["#SPIKEKNUCKLES_DESC"] = "Crude melee weapon.\nReworked metal formed into a grip like shape with tapered spikes at the knuckles.\nCan be used as a close-combat weapon."
lang["#SUPERSLEDGE_DESC"] = "Effective blunt melee weapon.\nA large hydraulic piston on the end of a long staff handle; The piston and handle form a hammer like shape, the piston is powered by unseen forces.\nCan be used as an effective smashing weapon, which is also long range."
lang["#9IRON_DESC"] = "This old 9 iron is bent and battered after many years of exposure to the elements."
lang["#BASEBALLBAT_DESC"] = "This all-American, hardwood, baseball bat will knock anything right out of the park."
lang["#BASEBALLBAT_STARTER_DESC"] = "An old, wooden, baseball bat. Once used to swing balls out of the park, now good for bashing a threat's head in."
lang["#BASEBALLBAT_SCRAPYARD_DESC"] = "A metal baseball bat used by the 80s Tribe.\n\nTake an aluminium bat, temper it, wrap some brahmin leather around the handle, and chain a pair of circular saw blades and you get this nasty piece of work.\n\n''.308 round to the elbow means I can't use this anymore. Swing for the fences, kid.'' - Tweak"
lang["#SUPERCATTLEPROD_DESC"] = "A Farmer's Best Friend model cattle prod from Wattz Electronics. This model has been upgraded to increase the electrical discharge."
lang["#CATTLEPROD_DESC"] = "Normally used for herding stubborn cattle, it has been re-purposed as a non-lethal weapon against humans.\n\nIn addition to the taser-like prongs at the tip normally found on cattle prods, it has been outfitted with a thick, electrified metal coil around the striking end, hooked up to a pair of batteries taped down near the handle."
lang["#CLEAVER_DESC"] = "A kitchen utensil made specifically for Hackin', Whackin', Choppin' that meat!"
lang["#DRESSCANE_DESC"] = "A dress cane from before the war.\n\nLike all things owned by high society, it is in excellent condition, and is made of a sturdy, shiny black wood with an ivory handle."
lang["#LEADPIPE_DESC"] = "A widely available, inexpensive, melee weapon. One of the ends has tape wrapped around it to improve grip, while the other is topped with a pipe fitting.\n\nCaution: Known to the state of New California to cause birth defects.\n\n#WIP_DESC"
lang["#HATCHET_DESC"] = "It is a hand-axe with a rubber-gripped wooden handle for chopping wood and limbs alike.\n\nUnlike throwing hatchets, these are not balanced for use as a projectile weapon."
lang["#KITCHENKNIFE_DESC"] = "For all your horror movie-related needs, or if you just need to cut some carrots."
lang["#DRIVER_DESC"] = "Always be sure to have the latest version."
lang["#NAILBOARD_DESC"] = "This 2x4 has several nails driven through it, with a whittled shaft to ensure a better grip.\n\nCommonly used by super mutants and other idiots."
lang["#PIPEWRENCH_DESC"] = "A typical wrench used by mechanics for hurting people. Also good for breaking apart vehicles!"
lang["#STRAIGHTRAZOR_DESC"] = "An old-fashioned shaving razor with a polished wooden handle. Though its blade is short, it's lightweight and can deliver several slashing hits in rapid succession."
lang["#ROLLINGPIN_DESC"] = "A plain wooden rolling pin used in baking to flatten dough, with a couple thin streaks of blood down one side."
lang["#SLEDGE_DESC"] = "The strongman's specialty makes an appearance in the wasteland."
lang["#WEIGHTBAR_DESC"] = "Clearly never intended to be used as a weapon, this baneful mass of lead and steel is no stranger to being weilded by only the strongest of the strong."
lang["#SHOVEL_DESC"] = "A wood-handed shovel. Useful for digging up graves, or hitting your targets from the furthest possible range. Meant for those who are true shovel knights."
lang["#HOE_DESC"] = "An old gardening tool. A long stick with a thick piece of metal attached to the end of it. Not sure what you plan to do with this, but it may prove to be a useful weapon."
lang["#SPADE_DESC"] = "Similar to a shovel, but significantly smaller. What's the actual difference between these two? They'll still bash a head in."
lang["#MOP_DESC"] = "You can use this to clean the blood on the floor from your enemies after violently beating them to death with it."
lang["#SWITCHBLADE_DESC"] = "The blade of this small knife is held by a spring. When a button on the handle is pressed, the blades shoots out with a satisfying ''Sssssshk'' sound."
lang["#WAKAZASHI_DESC"] = "A short finely crafted knife.\n\nThe tip seems to be designed to pierce armor!"
lang["#BUMPER_DESC"] = "More of a raw hunk of steel than a weapon, the bumper sword is an extremely heavy and sharp weapon created from the bumper of a car, dealing massive damage."
lang["#BATON_DESC"] = "A collapsible model law enforcement baton, used by various police departments before the Great War."
lang["#ALIENBATON_DESC"] = "Alien Shock Baton." -- NEED DESC
lang["#POWERFIST_DESC"] = "Originally used as pre-War hardware for demolition crews rather than as a weapon.\n\nThe power fist uses a pneumatic battering ram to deliver powerful, medium-speed punches to attackers"
lang["#CANOPENER_DESC"] = "A special something for those whose uncanned aggression would incite a war over something as trivial as Pre-War beans.\n\nJust track down some of those precious cans and get to bashing, baby!"
lang["#BEAREROFTHESTANDARD_DESC"] = "Carried at the head of a Brotherhood charge, this reinforced flagpole now serves a more direct purpose. The Brotherhood of Steel insignia hangs from its banner with ash and desert dust, a reminder that symbols can hit just as hard as steel. Some say fighting under the banner steadies the hand and hardens the heart. Others just appreciate a weapon that lets them beat their foes with ideology."
lang["#ENDBOSSKNIFE_DESC"] = "A brutal, retractable combat blade mounted beneath a power gauntlet — once part of the Enclave's most feared soldier's personal arsenal. The wrist knife hums faintly when activated, its monomolecular edge vibrating with suppressed energy. Designed for close-quarters execution, it deploys with a hydraulic snap capable of slicing through armor plating — or bone — with equal ease. Dried black residue stains the hinge, a silent testament to its former owner's fieldwork."

--███████╗███╗   ██╗███████╗██████╗  ██████╗██╗   ██╗
--██╔════╝████╗  ██║██╔════╝██╔══██╗██╔════╝╚██╗ ██╔╝
--█████╗  ██╔██╗ ██║█████╗  ██████╔╝██║  ███╗╚████╔╝
--██╔══╝  ██║╚██╗██║██╔══╝  ██╔══██╗██║   ██║ ╚██╔╝
--███████╗██║ ╚████║███████╗██║  ██║╚██████╔╝  ██║
--╚══════╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚═════╝   ╚═╝

lang["#GATLASER_NAME"] = "Gatling Laser"
lang["#HKL40_NAME"] = "[WIP] P.E L-40 Apollo"
lang["#LASERGUN_NAME"] = "Laser Gun"
lang["#PLASMAGUN_NAME"] = "Plasma Gun"
lang["#TRILASER_NAME"] = "Tri-Beam Laser Gun"
lang["#PLASMACASTER_NAME"] = "Plasma Caster"
lang["#PLASMACASTERTURBO_NAME"] = "Turbo Plasma Caster"
lang["#GAUSSRIFLE_NAME"] = "Gauss Rifle"
lang["#GAUSSPISTOL_NAME"] = "Gauss Pistol"
lang["#M72_NAME"] = "M72 Gauss Driver"
lang["#RCW_NAME"] = "Laser RCW"
lang["#SOLARCANNON_NAME"] = "Solar Cannon"

lang["#INCENERATOR_NAME"] = "Incinerator"
lang["#FLAMER_NAME"] = "Flamer"
lang["#P95_NAME"] = "P95 Turbo Plasma Rifle"
lang["#WATZ2k_NAME"] = "Wattz Laser Rifle"
lang["#WATZ1k_NAME"] = "Wattz Laser Pistol"
lang["#HOLORIFLE_NAME"] = "Hologram Rifle"
lang["#PULSERIFLE_NAME"] = "YK42B Pulse Rifle"
lang["#PPK12_NAME"] = "PPK12 Gauss Pistol"
lang["#PLASMADEFENDER_NAME"] = "Plasma Defender"
lang["#UNIQUEPLASMADEFENDER_NAME"] = "Semper Purus"
lang["#ENDBOSSPLASMAGUN_NAME"] = "Frank Horrigan's Plasma Cannon"

-- Alien

lang["#ALIENDISINTEGRATOR_NAME"] = "Alien Disintegrator"
lang["#ALIENBLASTER_NAME"] = "Alien Blaster"
lang["#ALIENATOMIZER_NAME"] = "Alien Atomizer"
lang["#CAPTAINSSIDEARM_NAME"] = "Captain's Sidearm"

-- Plasma

lang["#PLASMAGUN_PISTOL_NAME"] = "Plasma Pistol"
lang["#PLASMAGUN_MAGNUM_NAME"] = "Plasma Blaster"
lang["#PLASMAGUN_RIFLE_NAME"] = "Plasma Rifle"
lang["#PLASMAGUN_CARBINE_NAME"] = "Plasma Carbine"
lang["#PLASMAGUN_REPEATER_NAME"] = "Plasma Repeater"
lang["#PLASMAGUN_PDW_NAME"] = "Plasma PDW"
lang["#PLASMAGUN_MULTIPLASRIFLE_NAME"] = "Multiplas Rifle"
lang["#PLASMAGUN_MULTIPLASPISTOL_NAME"] = "Multiplas Pistol"
lang["#PLASMAGUN_SNIPERPISTOL_NAME"] = "Plasma Sniper Pistol"
lang["#PLASMAGUN_SNIPERRIFLE_NAME"] = "Plasma Sniper Rifle"

-- Laser

lang["#LASERGUN_PISTOL_NAME"] = "Laser Pistol"
lang["#LASERGUN_PISTOL_STARTER_NAME"] = "Unfocused Laser Pistol"
lang["#LASERGUN_RIFLE_STARTER_NAME"] = "Unfocused Laser Carbine"
lang["#LASERGUN_BLASTER_NAME"] = "Laser Blaster"
lang["#LASERGUN_RIFLE_NAME"] = "Laser Rifle"
lang["#LASERGUN_CARBINE_NAME"] = "Laser Carbine"
lang["#LASERGUN_REPEATER_NAME"] = "Laser Repeater"
lang["#LASERGUN_PDW_NAME"] = "Laser PDW"
lang["#LASERGUN_SNIPERPISTOL_NAME"] = "Laser Charge Pistol"
lang["#LASERGUN_SNIPERRIFLE_NAME"] = "Laser Charge Rifle"

-- Scatter Laser

lang["#LASERGUN_SCATTERRIFLE_NAME"] = "Scattered Laser Rifle"
lang["#LASERGUN_SCATTERPISTOL_NAME"] = "Scattered Laser Pistol"
lang["#LASERGUN_SCATTERREPEATER_NAME"] = "Scattered Laser Repeater"
lang["#LASERGUN_SCATTERPDW_NAME"] = "Scattered Laser PDW"
lang["#LASERGUN_SCATTERCARBINE_NAME"] = "Scattered Laser Carbine"
lang["#LASERGUN_SCATTERBLASTER_NAME"] = "Scattered Laser Blaster"
lang["#LASERGUN_SNIPERSCATTERPISTOL_NAME"] = "Scattered Laser Charge Pistol"
lang["#LASERGUN_SNIPERSCATTERRIFLE_NAME"] = "Scattered Laser Charge Rifle"

-- Tri-beam

lang["#TRILASERPISTOL_NAME"] = "Tri-Beam Laser Pistol"
lang["#TRILASERRIFLE_NAME"] = "Tri-Beam Laser Rifle"

--Energy Weapons Desc
lang["#GATLASER_DESC"] = "A multi-prism Gatling Laser.\n\nDesigned specifically for military use, these were in the prototype stage at the beginning of the Great War.\n\nPowered by Electron Charge Packs,these weapons have a high rate of fire and a generous battery resevoir."
lang["#HKL40_DESC"] = "A multi-prism Gatling Laser design stolen by Poseidon Energy from H&K in the late 2060's. The Apollo was a originally meant to be an upgrade to the mass produced L-30 design but pivoted to fit into a heavy antiarmor role later into its devlopment.\n\n The Apollo is fitted with a myriad of proprietary technology from Poseidon Energy causing the laser to have deflagrating effect on armor forcing it to usually be mounted on a tripod for use due to its extreme weight."
lang["#INCENERATOR_DESC"] = "Designed by some high-tech faction claiming to be the old world government, this monster shoots napalm like a mortar."
lang["#AERPISTOL_DESC"] = "The AER7 Laser Pistol is a military-grade laser, infrequently used by police and military units before the war. It makes use of a crystal array making it far more lethal than a Wattz."
lang["#AERPISTOL_STARTER_DESC"] = "A defective laser pistol pieced together from other defective laser pistols."
lang["#AERRIFLE_STARTER_DESC"] = "A defective laser carbine pieced together from other defective laser guns."
lang["#AERRIFLE_DESC"] = "The AER9 Laser Rifle is a high-power laser rifle that makes use of a crystal array, and was on track to be fielded by domestic military units prior to the Great War."
lang["#PLASMACASTER_DESC"] = "The Winchester P94 Caster was used as an industrial destruction tool utilizing plasma bolts before the the war.\n\nNow it's just a destruction tool that uses plasma bolts."
lang["#PLASMAGUN_DESC"] = "Plasma rifles are high-tech weapons which find numerous applications in military and industrial fields.\n\nThe plasma bolt is a toroid of superheated hydrogen gas that delivers high levels of both thermal and kinetic energy damage to the target, melting through most types of armors and causing massive 3rd-degree and 4th-degree burns."
lang["#M72_DESC"] = "The M72 Gauss Driver is of German design. It uses an electromagnetic field to propel rounds at tremendous speed... and pierce almost any obstacle. Its range, accuracy and stopping power is almost unparalleled."
lang["#GAUSSRIFLE_DESC"] = "The Gauss Rifle uses magnetic induction to propel a projectile at an incredible and devastating speed.\n\nEach shot can be charged for maximum damage by keeping the trigger held for a moment before releasing."
lang["#GAUSSPISTOL_DESC"] = "The PPK12 Gauss Pistol has unrivaled range, accuracy and damage in its class."
lang["#RCW_DESC"] = "A precursor to the Gatling Laser, the unique feature of this weapon is the addition of a rotating capacitor bank.\n\nThis capacitor rotation allows the Laser RCW to operate like a ''laser assault rifle'', avoiding the rate-of-fire limitations of a single capacitor design."
lang["#TRILASER_DESC"] = "A heavily modified weapon formed by combining multiple lasers.\n\nFires 3 full-powered beams per trigger pull, while consuming just as much ammo.\n\nMassivly improved damage output compaired to the standard Laser Rifle, but it's hastily improvised design requires much more frequent maintenance."
lang["#FLAMER_DESC"] = "The Flambe model 450 Flamer Varmiter version. Shoots hot napalm out for 'bug extermination'."
lang["#SOLARCANNON_DESC"] = "Developed by Posedion Energy before the Great War, the Solar Cannon is a energy weapon that can fire a ball of solar energy using microfusion cells.\n\n It was intended for crowd control but was found to be too unstable."

-- Alien
lang["#ALIENDISINTEGRATOR_DESC"] = "⏃ ⏃⍜⏃⎎⟒⍀⎎⎍⎍ ⏃⏁⍜⋏⏃⏁⟟☾ ⏃⌇⌇⏁⎍⎍⏁ ⍀⟟⎎⟒, ⌖⎍⏃⍀⏁⋏⟒⟒⎅ ⏁⍜ ⎍⟟⎎⎍⎅⟒⎅ ⏃ ⍑⍜⌇⏁⟟⎍⎍ ⏃⎍⟟⟒⋏.\n\n⊗⎍⍀⏃⍀ ⍙⍜⎍⎅ ⏃⟒ ⏃⍀⍜⎍⎅." -- Aurebesh Star Wars Language
lang["#ALIENBLASTER_DESC"] = "⏃ ⌇⎍⟟☾⌇ ⎍⏁⏁⟒⎍ ⏃⟟⌇⏁⍜⎍, ☾⍀⟒⏃⏁⟒⎅ ⏁⍜ ⌇⟒⍜⏁ ⏃⎍⟟⟒⋏ ⎎⏃⎍⋏⏃.\n\n⌖⟒'⎍⍀⟒ ⋏⍜⏁ ⏃☽⏁⍜⎍⟒⎍ ⏁⍀⏃⋏⌇⎍⟟⏁⟒⋏☌ ⊑⟟⌇, ⏃⍀⟒ ⎍⍀⟟⍜⎍?" -- Aurebesh Star Wars Language
lang["#CAPTAINSSIDEARM_DESC"] = "⏁⊑⟟⌇ ⏃⟟⌇⏁⍜⎍, ⋔⏃⋏⍜⎎⎍⎅⍜⍀⍀⎍⏁⟒⎅ ⏃⎍⎅ ⊑⍜ ⊑⟒ ⎍⟒☌⟒⋏⎅⏃⍀⟒⎍ ⏃⎍⟟⟒⋏ ⌇⋏⟟⊑ ⊗⎍⍀⏃, ⏁⍀⏃⎅⍀⟒⎍⎅ ⋔⟟⎍⎍⍜⋏⌇ ⍜⎎ ⎍⟟☌⊑⏁⟟⟒⏃⍀⌇ ⏁⍜ ⊑⟒ ⍀⏃⋏⟒⏁ |Earth|.\n\n⟒⏁ ⍙⏃⌇ ⟒⎎⌇⍜⟒☌⟟⎍⟟⏁⎍⟟⏁⟒⎅ ⎍⌇⟒⎅ ⊑⍜ ⊑⟒ ⏃⎍⟟⟒⋏ ☾⏃⏁⏁⟟⏃⋏⌇.\n\n⋏⍜⍙, ⟟⏁'⌇ ⏁⟟⋔⟒ ⏁⍜ ⋏⏃☾⟒ ⊑⟒ ⊑⎍⋏⏃⋏ ⍀⏃☾⟒ ⏃⟒⋏⎅ ⏁⍜ ⍙⍜⎍⍀ ⍙⟟⌇⌇." -- Aurebesh Star Wars Language
lang["#ALIENATOMIZER_DESC"] = "Alien Atomizer." -- NEED DESC

lang["#AER9_DESC"] = "The AER9 is a high-tech weapon that emits a concentrated beam of coherent light, with sufficient wattage to do considerable damage.\n\nFar sturdier and more reliable, it's much more commonly found than the models that followed."
lang["#AEP7_DESC"] = "The AEP7 laser was put into service to replace the N99 as the standard issue sidearm for military forces.\n\nWhile civilian models utilize a laser diode, military models employ a photonic focusing chamber and crystal array, creating a tighter, more destructive beam."
lang["#PLASMADEFENDER_DESC"] = "Glock 86 Plasma Pistol, designed by the Gaston Glock artificial intelligence.\n\nShoots a small bolt of superheated plasma.\n\nPowered by Microfusion Cells."
lang["#UNIQUEPLASMADEFENDER_DESC"] = "A presentation version of the Glock 86.\n\nDespite the silver and engravings providing no tactical advantage whatsoever, this piece was sightly enhanced for combat while still lovingly cared for. 'Colonel Samuel Vimes' is engraved along one side in small lettering."
lang["#PULSERIFLE_DESC"] = "The YK42B is an electrical pulse weapon that was developed by the Yuma Flats Energy Consortium.\n\nIt is considered a far superior weapon to the YK32 pulse pistol, having a greater charge capacity and range."
lang["#WATZ2k_DESC"] = "The Wattz 2000 is a consumer-grade high-tech laser rifle that uses high-energy light as a means of damage, striking it's target instantly at any range."
lang["#WATZ1k_DESC"] = "The Wattz 1000 is a consumer-grade laser created by the Wattz Corporation. It uses a laser focusing diode instead of a crystal array, decreasing it's damage."
lang["#PPK12_DESC"] = "A hand-held weapon of German design utilizing electromagnetic coils to propel metal slugs at extremely high velocities. They fire an incredibly small 2mm round at speeds just under the speed of light, tearing through just about any armor."
lang["#P95_DESC"] = "An early prototype, the Winchester P95 Plasma rifle was never officially mass produced due to it's expensive materials cost and bulky design.\n\nDespite this, the weapon is deadly thanks to it's experimental plasma accelerator, allowing the weapon to project plasma at extreme speeds."
lang["#ENDBOSSPLASMAGUN_DESC"] = "A monstrous, handheld plasma projector fused directly into the armor of Enclave operative Frank Horrigan. Designed to channel a concentrated surge of ionized plasma through magnetically sealed conduits, this weapon vaporizes anything unlucky enough to stand in its path. Its custom-built coolant system keeps it from melting its own housing—barely."

-- ██████╗ ██╗   ██╗███╗   ██╗███████╗
--██╔════╝ ██║   ██║████╗  ██║██╔════╝
--██║  ███╗██║   ██║██╔██╗ ██║███████╗
--██║   ██║██║   ██║██║╚██╗██║╚════██║
--╚██████╔╝╚██████╔╝██║ ╚████║███████║
-- ╚═════╝  ╚═════╝ ╚═╝  ╚═══╝╚══════╝

--Rifle
lang["#ASSAULTCARBINE_NAME"] = "Assault Carbine"
lang["#MARKSMANCARBINE_NAME"] = "Marksman Carbine"
lang["#ANTIMAT_NAME"] = "Anti-Materiel Rifle"
lang["#BLACKARROW_NAME"] = "Black Arrow"
lang["#LEVERGUN_NAME"] = "Brush Gun"
lang["#COWBOYREPEATER_NAME"] = "Cowboy Repeater"
lang["#COWBOYREPEATER_STARTER_NAME"] = "Antique Cowboy Repeater"
lang["#TRAILCARBINE_NAME"] = "Trail Carbine"
lang["#DKS_NAME"] = "Sniper Rifle"
lang["#FAMAS_NAME"] = "FAMAS"
lang["#LIBERTY_NAME"] = "Liberty"
lang["#FAL_NAME"] = "Battle Rifle"
lang["#FNC_NAME"] = "Battle Carbine"
lang["#HUNTING_NAME"] = "Hunting Rifle"
lang["#R91_NAME"] = "Assault Rifle"
lang["#SERVICERIFLE_NAME"] = "Service Rifle"
lang["#AK_NAME"] = "Soviet Rifle"
lang["#TYPE93_NAME"] = "Chinese Assault Rifle"
lang["#PIPERIFLE_NAME"] = "Pipe Gun"
lang["#PIPERIFLE_STARTER_PISTOL_NAME"] = "Scrap Pistol"
lang["#PIPERIFLE_STARTER_RIFLE_NAME"] = "Scrap Rifle"
lang["#PIPERIFLE_STARTER_SMG_NAME"] = "Scrap SMG"
lang["#PIPERIFLEBOLT_NAME"] = "Pipe Bolt-Gun"
lang["#VARMINT_NAME"] = "Varmint Rifle"
lang["#VARMINT_STARTER_NAME"] = "Bubba'ed Varmint Rifle"
lang["#BAR_NAME"] = "Browning Automatic Rifle"
lang["#MACHINEGUN_NAME"] = "Light Machine Gun"
lang["#HMACHINEGUN_NAME"] = "T-24 GPMG"
lang["#G11_NAME"] = "Salvo Rifle"
lang["#RANCOR_NAME"] = "Rancor Repeater"
lang["#BOZAR_NAME"] = "Bozar"
lang["#ASVAL_NAME"] = "AS-Val"
lang["#VSK_NAME"] = "VSK"
lang["#M1GARAND_NAME"] = "M1 Garand"
lang["#M1903_NAME"] = "M1903 Springfield"


lang["#SVD_NAME"] = "Soviet Sniper"
lang["#RHODIESPECIAL_NAME"] = "Rhodesian Special"
lang["#R91INFILTRATOR_NAME"] = "Infiltrator"
lang["#R91PERFORATOR_NAME"] = "Perforator"
lang["#R91WANDA_NAME"] = "Wanda"
lang["#RATSLAYER_NAME"] = "Ratslayer"
lang["#R91TELAVIV_NAME"] = "Tel Aviv Combat Rifle"
lang["#SRIFLE12.7_NAME"] = "12.7mm Thumper Carbine"
lang["#SRIFLECOMRADE_NAME"] = "Comrade-15"
lang["#SRIFLEPARTIZAN_NAME"] = "Partizan"
lang["#SRIFLEM199_NAME"] = "M199 Service Rifle"
lang["#SRIFLEROBERTS_NAME"] = "Roberts' Training Rifle"
lang["#HRIFLE_WHITEDEATH"] = "White Death"
lang["#TYPE93BD_NAME"] = "Xuanlong Assault Rifle"

--Shotgun
lang["#SHOTGUN"] = "Shotgun"
lang["#COMBATSHOTGUN_NAME"] = "Combat Shotgun"
lang["#SINGLEBARREL_NAME"] = "Single Shotgun"
lang["#DOUBLEBARREL_NAME"] = "SxS Shotgun"
lang["#TOZ34_NAME"] = "O/U Shotgun"
lang["#870_NAME"] = "Pump Action Shotgun"
lang["#STREETSWEEPER_NAME"] = "Street Sweeper"
lang["#SPAS12_NAME"] = "Police Shotgun"
lang["#SALVATION_NAME"] = "Salvation"
lang["#RIOTSHOTGUN_NAME"] = "Riot Shotgun"
lang["#870ECHO_RED_NAME"] = "Echos of Redemption"
lang["#870ECHO_DEL_NAME"] = "Echos of Deliberation"
lang["#870ECHO_PERD_NAME"] = "Echos of Perdition"
lang["#FUDD_NAME"] = "Fudd's Inheritance"
lang["#COACHGUN_NAME"] = "Coach Gun"
lang["#GRIMSREAVER_NAME"] = "Grims-Reaver"
lang["#ULTIMATUM_NAME"] = "Ultimatum"


--Handgun
lang["#USP_NAME"] = "9mm Combat Pistol"
lang["#USP45_NAME"] = ".45 Combat Pistol"
lang["#MAUSER_NAME"] = "Mauser Pistol"
lang["#10MMPISTOL_NAME"] = "10mm Pistol"
lang["#10MMREVOLVER_NAME"] = "10mm Revolver"
lang["#12.7MMPISTOL_NAME"] = "12.7mm Pistol"
lang["#14.5MMPISTOL_NAME"] = "14mm Pistol"
lang["#357MAGNUM_NAME"] = ".357 Revolver"
lang["#357MAGNUM_STARTER_NAME"] = "Rusted Magnum"
lang["#44MAGNUM_NAME"] = ".44 Magnum Revolver"
lang["#DEAGLE357_NAME"] = ".357 Desert Eagle"
lang["#DEAGLE_NAME"] = ".44 Desert Eagle"
lang["#WASTELANDHAWK_NAME"] = "Wasteland Hawk"
lang["#HUNTINGREVOLVER_NAME"] = "Hunting Revolver"
lang["#SEQUOIA_NAME"] = "Ranger Sequoia"
lang["#NEEDLER_NAME"] = "HK Needler"
lang["#M9FS_NAME"] = "9mm Pistol"
lang["#M9FS_STARTER_NAME"] = "Weathered 9mm Pistol"
lang["#1911PISTOL_NAME"] = ".45 Auto Pistol"
lang["#1911CAV_NAME"] = "Cavalry Handgun"
lang["#DETECTIVEPISTOL_NAME"] = "Detective Pistol"
lang["#MARKSMANPISTOL_NAME"] = "Marksman Pistol"
lang["#GALVANICTHUNDER_NAME"] = "Galvanic Thunder"

lang["#1911DELTA_NAME"] = "Delta Elite"
lang["#THATGUN_NAME"] = "That Gun"
lang["#93R_NAME"] = "Rapid 9"
lang["#ELDERSJUDGEMENT_NAME"] = "Elder's Judgement"
lang["#357POLICE_NAME"] = "Combat Magnum"
lang["#10MMVOLLEY_NAME"] = "10mm Volley Pistol"
--smg
lang["#9MMSMG_NAME"] = "9mm SMG"
lang["#P90_NAME"] = "4.7mm PDW"
lang["#10MMSMG_NAME"] = "10mm SMG"
lang["#TOMMYGUN_NAME"] = ".45 Auto SMG"
lang["#44TOMMY_NAME"] = "Valentine Typewriter"
lang["#P90C_NAME"] = "10mm PDW"
lang["#12.7MMSMG_NAME"] = "12.7mm SMG"

lang["#GREASEGUN_NAME"] = "The Tanker"

--heavy
lang["#MINIGUN_NAME"] = "5mm Minigun"
lang["#AVENGER_NAME"] = "Avenger Minigun"
lang["#VINDICATOR_NAME"] = "Vindicator Minigun"
lang["#GAUSS_MINIGUN_NAME"] = "Gauss Minigun"
--other
lang["#SYRINGER_NAME"] = "Dart Gun"
--lang["#FARTNADE_NAME"] = "Fart-Nade" -- This shit was so stupid.
lang["#RAILRIFLE_NAME"] = "Railway Rifle"

--explosive
lang["#APW_NAME"] = "25mm APW"
lang["#M79_NAME"] = "Break-Action Grenade Rifle"
lang["#SKYBREAKER_NAME"] = "Skybreaker"
lang["#FATMAN_NAME"] = "Fat-Man"
lang["#MISSILELAUNCHER_NAME"] = "Missile Launcher"
lang["#REDGLARE_NAME"] = "Red Glare"
lang["#CHINALAKE_NAME"] = "China Lake"
-------------------------------------------------------
--Guns Desc
-------------------------------------------------------
--rifle
lang["#ASSAULTCARBINE_DESC"] = "The assault carbine is a magazine-fed, compact automatic weapon with a high rate of fire and a comparatively low max spread.\n\nChambered in 5mm, this weapon was designed as a lightweight, portable solution for armored infantry.\n\nThe compairably small size of the round however makes it ill suited for anything other than its intended purpose."
lang["#MARKSMANCARBINE_DESC"] = "A high-end semiautomatic rifle of U.S. origin.\n\nCousin to the Service Rifle, The Marksman Carbine is an improved version using only the best components available.\n\nFaster firing, more durable, and lighter weight to boot!"
lang["#ANTIMAT_DESC"] = "The PGM Hecate II is an extremely powerful Anti-Materiel weapon made to be used against heavily armored military equipment\n\nOne could only imagine what it could do to a Deathclaw."
lang["#BLACKARROW_DESC"] = "A prototype 12.7 bullpup rifle. The original role of this rifle was to act as a compact and light weight alternative to previous Anti-Material rifles. \n\nDuring the trial phases the weapon showed promise but ultimately failed to meet the D.O.D's required terms for adoption. The design was shelved until some post-war factions found it and started producing it in moderate numbers to serve as a highpower marksmen rifle."-- NEED DESC
lang["#COWBOYREPEATER_DESC"] = "A Pre-War reproduction of a now ancient design, the Cowboy Repeater.\n\nIt's a good thing too, 19th century ammo is hard to come by."
lang["#COWBOYREPEATER_STARTER_DESC"] = "An ancient Cowboy Repeater chambered in .38 Special only. Still pretty powerful, could use some cleaning though."
lang["#TRAILCARBINE_DESC"] = "A Pre-War reproduction of a now ancient design, chambered for modern ammuniton.\n\nIt's a good thing too, 19th century ammo is hard to come by."
lang["#DKS_DESC"] = "A DKS-501 sniper rifle, excellent for long range combat.\n\nChambered for .308.\n\nPrimarily seen issued as a contract military weapon; it saw limited use in the commercial market as a high-end, but notoriously fragile, hunting rifle."
lang["#FAMAS_DESC"] = "A Bullpup service rifle manufactured in France.\n\nChambered for 5.56, this uncommon rifle is easier fed than found. One wonders how it ever made its way stateside."
lang["#LIBERTY_DESC"] = "A symbol of freedom and resistance.\n\nThis rifle was used by partisans and resistance fighters during the Resource Wars to fight against oppressive regimes."
lang["#FAL_DESC"] = "A battle rifle produced by the Belgian arms manufacturer Fabrique Nationale de Herstal.\n\nThis rifle has been more widely used by armed forces than any other rifle in history."
lang["#FNC_DESC"] = "A variant of the battle rifle produced by the Belgian arms manufacturer Fabrique Nationale de Herstal.\n\nThis is a rechambered in 5.56, internally improved, fully-automatic, and slightly more modern variant of the Battle Rifle."
lang["#HUNTING_DESC"] = "An aged but reliable weapon.\n\nThis rifle has seen better days, but is still effective for long ranged combat.\n\nChambered in .308."
lang["#LEVERGUN_DESC"] = "A big bore lever gun chambered in .45-70 Govt.\n\nBrush guns are known for their ease of use in heavy brush or tight spaces, where a long range precision rifle would be unwieldy or impractical."
lang["#PARTIZAN_DESC"] = "This gun is liberty,\n\nhold for certain that the day when you no more have it, you will be returned to slavery."
lang["#R91_DESC"] = "An R91 full-auto urban assault rifle, issued to U.S. Armed Forces during urban pacification operations and combat.\n\nThe R Series of rifles were used following the discontinuation of the M Series in the early 21st century.\n\nProduced by civilian manufacturer Stent Security Solutions, they were made in many models and variations."
lang["#SERVICERIFLE_DESC"] = "A semiautomatic rifle of U.S. origin.\n\nReverse engineered from Pre-war schematics, this design has enjoyed a new found surge in popularity for its ease of manufacturing and respectable firepower.\n\nThis example is a post-war imitation, as the originals had been phased out in favor of the R Series by the time the bombs fell."
lang["#AK_DESC"] = "Originating in Soviet Russia at the tail of the second World War, this design has since been utilized in conflicts all over the world.\n\nIt is no surprise so many years after the bombs fell that these sturdy rifles remain, in some form or another."
lang["#TYPE93_DESC"] = "A design used en masse during the Resource Wars for Chinese infiltrators and sympathizers.\n\nThousands of these weapons were smuggled into the US, and many remain functional even 150 years after the Great War."
lang["#PIPERIFLE_DESC"] = "A crude, but effective weapon. Fashioned from leftover scrap and Pre-War piping, its cheap and easy to produce.\n\nCoupled with it's 9mm chambering, this makes it widely used by Raiders and loners alike."
lang["#PIPERIFLE_STARTER_PISTOL_DESC"] = "A functional gun, made with scraps. Nothing really special about it, other than it shoots bad bullets."
lang["#PIPERIFLE_STARTER_RIFLE_DESC"] = "A functional gun, made with scraps. A stronger base with a crappy stock screwed onto it, shoots pretty slow though."
lang["#PIPERIFLE_STARTER_SMG_DESC"] = "A functional gun, made with scraps. This one has a auto-tune built in, so it can fire fully automatic. Very weak with damage though."
lang["#PIPERIFLEBOLT_DESC"] = "A simple, but effective weapon. Fashioned from leftover scrap and Pre-War piping, its powerful and easy to produce.\n\nGiven the high pressure of its .308 chambering, an internal top-loaded magazine and a bolt action were chosen over, well, it exploding in your hands."
lang["#VARMINT_DESC"] = "A Pre-War rifle typically used in hunting small game.\n\nLower powered than it's .308 cousin, but much more common, as is it's ammo.\n\nChambered in 5.56."
lang["#VARMINT_STARTER_DESC"] = "A terribly mistreated varmint rifle chambered in 5.56.\n\nThis gun saw it's share of abuse long before the bombs dropped, and the following years have't been any kinder."
lang["#MACHINEGUN_DESC"] = "A fully automatic support machinegun.\n\nChambered in 5.56 and sporting a 90 round magazine by default, this is one of the more intimidating Pre-War small arms surviving still today.\n\nUnfortunately, you'll need the combined strength and resources of an army to carry and feed it."
lang["#HMACHINEGUN_DESC"] ="The T24 Light Machine Gun is a salvaged pre-War prototype based on the German MG 42, originally developed to replace the BAR and M1919A4.\n\nThough the project failed before the Great War, Phoenix Company later revived it using scavenged parts and Blueprints, creating rugged variants prized for their fierce rate of fire and reliability in the wasteland."
lang["#BAR_DESC"] = "This air-cooled automatic rifle, chambered for .308 caliber rounds, is one of the rarest types of weaponry in the pre-War United States.\n\n The automatic rifle was extensively used by U.S. forces in World War I, World War II, and the Korean War."
lang["#G11_DESC"] = "The HK G11 K2 is one of the most advanced assault rifles created.\n\nIt is capable of firing salvos of caseless 4.7mm which exit the gun before any recoil can even be felt.\n\nDue to complex construction and rare materials, as well as specialized ammo that is difficult to procure, this rifle is exceedingly rare."
lang["#RANCOR_DESC"] = "This weapon was born from a need of protection against a evolving and unforgiving wasteland.\n\nConstructed using some of the most expensive materials Desert Rangers could find the Rancor Repeater it is capble of firing 14mm a monsterously large handgun catridge designed to takedown monsterously large foes."
lang["#BOZAR_DESC"] = "The ultimate refinement of the sniper's art. Although, somewhat finicky and prone to jamming if not kept scrupulously clean, the big weapon's accuracy more than makes up for its extra maintenance requirements."
lang["#M1GARAND_DESC"] = "Before plasma rifles and laser weaponry, the M1 Garand was the cutting edge of American firepower. This semi-automatic legend earned its place in history through decades of military service and now it’s found a second life in your hands.\n\nFiring .30-06 from an 8-round en-bloc clip with that unmistakable ping, it’s a symbol of a bygone era one where craftsmanship met firepower head-on. Rugged, reliable, and still deadly."
lang["#M1903_DESC"] = "Forged in the fires of two World Wars and resurrected for the wastes, the M1903 Springfield is a bolt-action marksman's dream deadly accurate and devastating at range\n\nThis antique beauty earned its stripes in the trenches of Europe and the islands of the Pacific, Chambered in .30-06 the Springfield doesn't spray it speaks, and when it does, heads pop like melons."

lang["#RATSLAYER_DESC"] = "Developed by a farmer tired of Molerats, this is the apex of Varmint Rifle technology.\n\nContinue his legacy. Make those damn rats extinct."
lang["#SVD_DESC"] = "A lengthy rifle. Similar to the Soviet Rifle, but is capable of firing .308 rounds, which makes it a great sniper to use."
lang["#RHODIESPECIAL_DESC"] = "''Pugnamus Amo Leo''" --  probably don't change this because it's supposed ot be a latin reference
lang["#R91INFILTRATOR_DESC"] = "R91 urban assault rifle, Infiltration Variant.\n\nDesigned for use by special operations groups, the stock has been removed, barrel shortened, and a suppressor, optic, and extended magazine have been added."
lang["#R91PERFORATOR_DESC"] = "R91 urban assault rifle, Infiltration Variant.\n\n''This is the best gun I ever had. A little slower on the trigger, but she makes up for it in power and accuracy.\n\nUse her in good health.''"
lang["#R91WANDA_DESC"] = "An R91 full-auto urban assault rifle.\n\n''Look, you obviously don't know anything about intelligence work, lady.\n\nIt's an X-K-Red-27 technique.''"
lang["#R91TELAVIV_DESC"] = "A foreign combat rifle.\n\nChambered in .308, this pattern of rifle was the design basis for the American made R91. The selector is stuck in automatic mode. This particular rifle was plucked from the irradiated ruins of Tel Aviv after its destruction in 2053.\n\n''Ki b'Tahbulot, Ta'ase-l'kha milhama.''"
lang["#SRIFLE12.7_DESC"] = "A semiautomatic big-bore carbine of U.S. origin.\n\nReverse engineered from Pre-war schematics, this caliber conversion was originally designed to disable enemy vehicles.\n\nPostwar, it's been found to work on everything else, so long as you can afford it."
lang["#SRIFLECOMRADE_DESC"] = "''That rifle hanging on the wall of the working-class flat or labourer's cottage is the symbol of democracy.\n\nIt is our job to see that it stays there."
lang["#SRIFLEPARTIZAN_DESC"] = "''This gun is liberty,\n\nhold for certain that the day when you no more have it, you will be returned to slavery.''"
lang["#SRIFLEM199_DESC"] = "Perhaps the most well-recognized weapon in the modern U.S. military arsenal, the M199 earned its nickname ''The Backtalker'' from the unusual report the firing mechanism makes as it ejects a spent shell.\n\nFiring standard 5.56mm rounds, the M199 was the official infantry weapon of the U.S. Army prior to being discontinued in favor of the R series in the early 21st century."
lang["#SRIFLEROBERTS_DESC"] = "A well-loved service rifle.\n\nThis particular rifle is said to have belong to Colonel Roberts, first Chief of Ordnance of the New California Republic Army.\n\n''For the Republic!''"
lang["#HRIFLE_WHITEDEATH_DESC"] = "An aged but reliable weapon.\n\nImported cheaply in-mass before the Great War, this rifle was was manufactured somewhere in Eastern Europe.\n\nChambered in 7.62x39."
lang["#TYPE93BD_DESC"] = "Ancient Chinese Emperor Huizong of Song canonized five colored dragons as ''kings''.\n\nXuanlong is the black dragon, dwelling in the depths of mystic water."

--shotgun
lang["#COMBATSHOTGUN_DESC"] = "The Winchester City-Killer is an automatic Bullpup shotgun.\n\nRestricted to law enforcement and military, this weapon saw most of it's action in riot control."
lang["#SINGLEBARREL_DESC"] = "A single-shot break action shotgun.\n\nSimple, dependable, cheap. These qualities saw to single barrel shotguns being produced in incredible numbers before the bombs fell.\n\nCapable of firing 12 Gauge shotgun shells, of which various types exist."
lang["#DOUBLEBARREL_DESC"] = "A Side-By-Side shotgun. Popular in hunting and Pre-War shooting sports.\n\nCapable of firing 12 Gauge shotgun shells, of which various types exist."
lang["#TOZ34_DESC"] = "An Over/Under shotgun. Popular in hunting and Pre-War shooting sports.\n\nCapable of firing 12 Gauge shotgun shells, of which various types exist."
lang["#870_DESC"] = "A pump action shotgun. Popular in hunting and Pre-War home protection.\n\nCapable of firing 12 Gauge shotgun shells, of which various types exist."
lang["#870ECHO_DESC"] = "A battle-scarred, heavily modified M-12 Trench Gun affixed with a 17-inch bayonet. Its surface is etched with markings and wax seals, each telling a tale of hardship.\n\nAs you grasp it, a heavy feeling presses down on your shoulders accompanied by a unrelenting drive to strive forward to an unseen goal. Etched among the markings are the words: 'The light of the mind alone cannot burn away all darkness.'."
lang["#STREETSWEEPER_DESC"] = "A semi-automatic shotgun with a drum magazine.\n\nCapable of firing 12 Gauge shotgun shells, of which various types exist.\n\nSeen infrequently in the hands of Pre-War military units and police departments, this model has found renewed popularity post war by just about anyone able to get their hands on it."
lang["#SPAS12_DESC"] = "A semi-automatic shotgun with a tube magazine.\n\nCapable of firing 12 Gauge shotgun shells, of which various types exist.\n\nA high-end imported model popular with police departments and firearms enthusiasts alike, its high rate of fire is great for dealing with multiple targets."
lang["#SALVATION_DESC"] = "This well-made reliable shotgun is primarily characterized by its high fire-rate, a marked improvement over other Police Shotgun models.\n\nIt unfortunately has a mangled over/underrail. It'll be hard to aim down these sights." 
lang["#RIOTSHOTGUN_DESC"] = "A terrifying drum-mag fed, semi-automatic shotgun seen used by the NCR Riot Control.\n\nNot too displaced from its origional use pre-war, the Riot Shotgun is the perfect weapon for disposing of large crowds of protesting civilians or instead homicidal raiders."

lang["#GRIMSREAVER_DESC"] = "Grims-Reaver." -- NEED DESC
lang["#ULTIMATUM_DESC"] = "Ultimatum." -- NEED DESC
lang["#FUDD_DESC"] = "A coming-of-age gift from a father, intended for his now late son, taken before his time.\n\n\n\nIt's Crow Season."
lang["#COACHGUN_DESC"] = "A double barrel shotgun specially modified by the 80s Tribe.\n\nCoach guns feature a full length stock but a cut down barrel. This particular shotgun fires both barrels at once; a nasty surprise for unarmored targets.\n\nIncapable of firing slugs.\n\n''Shoot this at a trooper's unarmored legs and watch them turn to jelly.'' -Gridlock"


--handgun
lang["#USP_DESC"] = "An H&k USP, made in a foreign country.\n\nOnce marketed towards international law lnforcement and military use, this pistol never saw adoption in the U.S.\n\nPlagued by competition with dometic manufacturers, high import costs, and a particularly embarrassing mistake on a widespread promotional poster, these pistols are an obscure rarity in the Wasteland."
lang["#MAUSER_DESC"] =  "A Shanxi Type 17 pistol.\n\nMass produced by the Taiyuan Arsenal for the army of Yan Xishan, this pistol is now a relic of the Sino-American War."
lang["#10MMPISTOL_DESC"] = "Favored for it's quality and simple manufacturing, this weapon was widely used by law enforcement in the old world.\n\nDue to it's reliability in desert-like conditions, the Colt 6520 is still widely used today."
lang["#10MMREVOLVER_DESC"] = "This revolver is chambered in 10mm, and is a reliable choice for law enforcement.\n\nIt's reliable, sure, but it still fell behind the 10mm Pistol quite quickly."
lang["#14.5MMPISTOL_DESC"] = "A Sig-Sauer 14mm Semi-Auto Pistol. Large, singleshot handgun. Near-perfect craftsmanship."
lang["#12.7MMPISTOL_DESC"] = "A Sig-Sauer 12.7mm Semi-Auto Pistol.\n\nLarge, semi-automatic handgun with a fixed barrel, an example of excellent craftsmanship.\n\nImported to the U.S. from Europe, this design was chambered originally in 14mm."
lang["#MARKSMANPISTOL_DESC"] = "A Commanche Break-Action Pistol chambered for .45-70 govt. It can hold only one round, lets hope it kills whoever its aimed at."
lang["#357MAGNUM_DESC"] = "A single action revolver chambered for .357 Magnum and .38 special rounds.\n\nIts compairably slow firing rate and low capacity are made up for with its powerful cartridge and reliable action.\n\nThe cylinder swings open to quickly eject spend rounds and reload."
lang["#357MAGNUM_STARTER_DESC"] = "An old magnum. Can still load and shoot .357, but not as well as it probably could have back then."
lang["#44MAGNUM_DESC"] = "One of the bigger bore handguns in the world, this gun can punch through nearly all soft armor.\n\nThe ammunition is hard to find and can be very costly."
lang["#DEAGLE357_DESC"] = "A well-rounded powerful Semi-Automatic handgun chambered in .357 Magnum."
lang["#DEAGLE_DESC"] = "A powerful Semiautomatic handgun chambered in .44 Magnum."
lang["#WASTELANDHAWK_DESC"] = "Named ''Wasteland Hawk'' as a playful spin on ''Desert Eagle'', this gun has earned notoriety as the best pistol a Bounty Hunter can buy.\n\nNow that it's in your hands, it's time to fall upon your prey like some sort of..."
lang["#HUNTINGREVOLVER_DESC"] = "A monsterously large handgun chambered for the 45-70 Govt round.\n\nUsed exclusivly in hunting Dangerous game, this gun is punishing to fire, but it just might save your life."
lang["#SEQUOIA_DESC"] = "A Hunting Revolver seen being used by Vetran Rangers, this weapon has been coined the 'Ranger Sequoia' for its distinct image of strength and resilience that both rangers and the weapon evoke."
lang["#NEEDLER_DESC"] = "A handgun capable of shooting needles filled with various substances.\n\nThe ammunition can be made by hand and filled with all manner of substances."
lang["#M9FS_DESC"] = "One of the more common 9mm pistols, the Beretta is popular due to its reliability, 17 round magazine and good looks."
lang["#M9FS_STARTER_DESC"] = "An aging 9mm pistol given to you before you set out on your own. There are many like it, but this one is yours."
lang["#1911PISTOL_DESC"] = "The classic Colt M1911 A1.\n\nWhile the fixed barrel and tight tolerances of this pistol make for an extremely accurate firearm, it comes at the cost of a higher frequency of jams.\n\nFor this reason and the compairatively limited capacity, this design was phased out of U.S. service some time after World War II."
lang["#1911CAV_DESC"] = "An improved version of the classic Colt M1911A1.\n\nWhile the fixed barrel and tight tolerances of this pistol make for an extremely accurate firearm, this chambering and configuration lessens the jam chances of the standard version.\n\nAdopted by U.S. Armored Cavalry Units this fairly heavy firearm reduces recoil and flip up and sports various improvements including a match barrel and night sights, but was phased out of U.S. service just after the M1911A1 in favor of newer sidearm options."
lang["#DETECTIVEPISTOL_DESC"] = "Long nights.\nHard cases.\nStale ramen from a Protectron.\nThese are the hallmarks of a good Detective.\n\nAnd this detective's friend is ready to help you shut down any rogue RobCo freak."
lang["#GALVANICTHUNDER_DESC"] = "Funny Ha Ha Do not give out."

lang["#THATGUN_DESC"] = "That Gun." -- NEED DESC
lang["#1911DELTA_DESC"] = "Catalog Variant 5 - Spur hammer with wood grips.\n\n''A true collector's piece.''"
lang["#93R_DESC"] = "Burst fire machine pistol.\n\n''Dead or alive, you're coming with me.''"
lang["#ELDERSJUDGEMENT_DESC"] = "Do you see destiny immutable? \n\nDoes fate or dedication keep you bended knee and dutiful? \n\nFeign predestination? \n\nor is zealotry the truth of all?"
lang["#357POLICE_DESC"] = "A double action revolver chambered for .357 Magnum and .38 special rounds.\n\nAllows one to fire without having to cock the hammer before every shot.\n\nThe cylinder swings open to quickly eject spend rounds and reload."
lang["#10MMVOLLEY_DESC"] = "A 10mm pistol modified by the 80s Tribe.\n\nModified to dump its entire magazine in one trigger pull. Kicks like a damn mule and can't fit extended mags, but fires very quickly.\n\n''Strike fast, strike hard. -Fire Crotch''"
--smg
lang["#9MMSMG_DESC"] = "A open-bolt submachine gun chambered in 9mm. Has a good magazine capacity and fire rate, but the short barrel has been terribly worn, limiting engagements to short range."
lang["#10MMSMG_DESC"] = "A higher-end submachine gun chambered in 10mm.\n\nWhile the roller-lock firing mechanism results in incredibly little recoil, its effective range is limited in full auto.\n\nEasy to control and shred unarmored foes with, this weapon is vital among freelance-mercs."
lang["#P90_DESC"] = "A personal defense weapon chambered in 4.7mm.\nThis weapon has an extremely generous 50 round mag. Along with a high rate of fire.\n\nThe rounds are not common and must be bought more often than found."
lang["#TOMMYGUN_DESC"] = "The .45 Auto SMG is a relatively robust gun that offers heavy firepower. Unfortunately, the result is that this gun requires two hands to operate.\n\nAlso, the heavy recoil means that this SMG cannot be used by frail individuals and accuracy will suffer in long-distance engagements."
lang["#44TOMMY_DESC"] = "\'\'Valentine's day has always been a tradition of love, dating all the way back to the goddamn Roman times.\n\nThen, Al Capone figured out a better use for the day.\n\nGoodbye, my love.\'\'"
lang["#P90C_DESC"] = "A 10mm PDW otherwise know as the H&K P90c.\n\nPre-War, firearm enthusiasts would find it strange that the logo of Heckler & Koch is on a P90 however that is no longer relevant to them.\n\nDespite being produced in secrecy with stolen designs its not a bad copy."
lang["#ASVAL_DESC"] = "A relic of Soviet engineering, the AS-Val is a fully automatic integrally suppressed assault rifle chambered in 9x39mm subsonic rounds.\n\nOriginally built for covert operations behind enemy lines, its armor-piercing rounds and whisper-silent profile make it a favorite among aspiring wasteland assassins."
lang["#VSK_DESC"] = "VSK"
lang["#12.7MMSMG_DESC"] = "12.7mm SMG"

lang["#GREASEGUN_DESC"] = "''I never liked you, Joker.\nI never thought you were funn--''\n\n\nBANG"
--heavy
lang["#MINIGUN_DESC"] = "A Rockwell CZ53 Personal Minigun. When the Great War struck, it was already an aging design and was slowly being replaced by the more advanced CZ57 Avenger minigun."
lang["#AVENGER_DESC"] = "Rockwell designed the Avenger as the replacement for their aging CZ53 Personal Minigun. The Avenger's design improvements include improved, gel-fin, cooling and chromium plated barrel-bores. This gives it a greater range and lethality"
lang["#VINDICATOR_DESC"] = "The German Rheinmetall AG company created the ultimate minigun.\n\nThe Vindicator throws 4.7mm caseless down its six carbon-polymer barrels. \n\nAs the pinnacle of Teutonic engineering skill, it is the ultimate hand-held weapon."
lang["#GAUSS_MINIGUN_DESC"] = "The Gauss minigun is a powerful, automatic ballistic weapon that rapidly fires 2mm electromagnetic cartridges. While it accelerates the projectiles at a slower velocity compared to other gauss weaponry it makes up for this by the sheer number of projectiles hitting the poor fool in the sights of this monster.\n\n"
--other
lang["#SYRINGER_DESC"] = "An improvised, but effective weapon. Fashioned from leftover scrap and Pre-War piping, it was designed in the image of Pre-War ''tranquilizer guns''.\n\nCan be used offensively or as a support weapon, depending on the type of darts chosen by user."
lang["#FARTNADE_DESC"] = "M-42 Tactical Gastrointestinal Grenade is a handheld capsule fitted to contain Megasharts, small smelly warheads.\nDevastating against all noses."
lang["#RAILRIFLE_DESC"] = "A highly-powered pneumatic conversion of an industrial nailgun, now able to launch nails at great distances.\n\nOnce devastating for train tracks, now devastating for the NCR and any of their 'allies' wearing Power Armor."

--explosive
lang["#APW_DESC"] = "The 25mm anti-personnel weapon is a semi-automatic grenade launcher.\n\nDesigned to give a soldier the death-dealing capability of vehicle mounted grenade machineguns in a more portable package."
lang["#M79_DESC"] = "A single shot, hand-held grenade launcher.\n\nLaunches 40mm Grenades.\n\nDeveloped in the early 1960s, this weapon has seen continued use by U.S. forces for over a century, due to its simple design."
lang["#SKYBREAKER_DESC"] = "A two shot, hand-held grenade launcher.\n\nLaunches 40mm Grenades.\n\n#WIP_DESC"
lang["#FATMAN_DESC"] = "M-42 Tactical Nuclear Catapult is a shoulder mounted crossbow fitted to launch Mini-Nukes, small atomic warheads.\nDevastating against all targets, if you can find any ammo for it."
lang["#MISSILELAUNCHER_DESC"] = "A Shoulder Mounted explosive weapon.\nFires a large projectile that explodes on impact."
lang["#REDGLARE_DESC"] = "A Fully Automatic shoulder mounted explosive weapon.\nFires a Red Rocket that explodes on impact.\n\n\"And the Rocket's Red Glare... The bombs bursting in air...\"."

RELOADSCHEMA = true