local lang = RSRG.Languages["es-es"]

lang["#CONTROL_BINDCHECKER_TITLE"] = "Controles faltantes detectados!"
lang["#CONTROL_BINDCHECKER_SUBTITLE"] = "Resurgence reemplaza los controles predeterminados de Garrys Mod, si estos controles no están asignados, tendrás dificultades jugando."
lang["#CONTROL_BINDCHECKER_FOOTNOTE"] = "Presiona abrir Menú de Garrys Mod, dirígete a \"Opciones\", selecciona \"Teclado\", y asigna estas teclas, o presiona \"Usar Predeterminado\" para una experiencia optima.\nVuelve a validar los controles después de terminar."
lang["#CONTROL_BINDCHECKER_REVALIDATE"] = "Volver a validar los controles"
lang["#CONTROL_BINDCHECKER_OPENMENU"] = "Abrir Menú de Garrys Mod"
lang["#CONTROL_BINDCHECKER_PLAYANYWAY"] = "Jugar de todas maneras"
lang["#CONTROL_BINDCHECKER_PLAYANYWAY_CONFIRM"] = "Estas seguro de que quieres jugar sin asignar estos controles?\nPodrias experimentar problemas o ser incapaz de jugar."
lang["#CONTROL_BINDCHECKER_NOTVALIDATED"] = "Aun se detectan controles faltantes."
lang["#CONTROL_BINDCHECKER_VALIDATED"] = "Todos los controles han sido validados!\nPuedes jugar normalmente ahora."

lang["#CONTROL_AMMOTYPE"] = "Cambiar tipo de munición / Menú de Arma (Mantén)"
lang["#CONTROL_MELEENADE"] = "Ataque cuerpo a cuerpo fuerte / Culatazo / Granada (Mantén)"
lang["#CONTROL_ACCEPTINVITE"] = "Aceptar invitación"
lang["#CONTROL_DECLINEINVITE"] = "Rechazar invitación"
lang["#CONTROL_COMMUNITY"] = "Abrir menú de comunidad"
lang["#CONTROL_CAMERA"] = "Modo de cámara"
lang["#CONTROL_PING"] = "Marcador de equipo"
lang["#CONTROL_PIPBOY"] = "Abrir Pip-Boy / Encender luz (Mantén)"
lang["#CONTROL_INTERACT"] = "Interactuar"
lang["#CONTROL_ATTACK"] = "Atacar / Disparar"
lang["#CONTROL_AIM"] = "Apuntar / Desviar"
lang["#CONTROL_RELOAD"] = "Recargar / Alistar arma (Mantén)"
lang["#CONTROL_HOTKEY1"] = "Acceso rápido 1"
lang["#CONTROL_HOTKEY2"] = "Acceso rápido 2"
lang["#CONTROL_HOTKEY3"] = "Acceso rápido 3"
lang["#CONTROL_HOTKEY4"] = "Acceso rápido 4"
lang["#CONTROL_HOTKEY5"] = "Acceso rápido 5"
lang["#CONTROL_HOTKEY6"] = "Acceso rápido 6"
lang["#CONTROL_HOTKEY7"] = "Acceso rápido 7"
lang["#CONTROL_HOTKEY8"] = "Acceso rápido 8"
lang["#CONTROL_HOTKEY9"] = "Acceso rápido 9"
lang["#CONTROL_ZOOMIN"] = "Hacer Zoom"
lang["#CONTROL_ZOOMOUT"] = "Alejar Zoom"

lang["#BINDING_PURPOSE"] = "Propósito de Resurgence: $control"
lang["#BINDING_DEFAULT"] = "Asignación predeterminada: $key"
lang["#BINDING_CURRENT"] = "Actualmente Asignada a: $command"

-- Shows as "currently bound to Nothing in the bind checker"
lang["#BINDING_NOTHING"] = "Nada"

RELOADSCHEMA = true