local lang = RSRG.Languages["es-es"]

--███╗   ███╗███████╗██╗     ███████╗███████╗
--████╗ ████║██╔════╝██║     ██╔════╝██╔════╝
--██╔████╔██║█████╗  ██║     █████╗  █████╗
--██║╚██╔╝██║██╔══╝  ██║     ██╔══╝  ██╔══╝
--██║ ╚═╝ ██║███████╗███████╗███████╗███████╗
--╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝╚══════╝

lang["#BOTTLESHANK_NAME"] = "Botella rota"
lang["#STORMCUTTER_NAME"] = "Cortatormentas"
lang["#ZAPGLOVE_NAME"] = "Guante Desplazador"
lang["#INDUSTRIALGAUNTLET_NAME"] = "Guantelete Industrial"
lang["#PLASMACUTTER_NAME"] = "Cortador de Plasma"
lang["#SWORD_NAME"] = "Katana"
lang["#PICKAXE_NAME"] = "Pico"
lang["#COMBATKNIFE_NAME"] = "Cuchillo de Combate"
lang["#COMBATKNIFE_STARTER_NAME"] = "Cuchillo Doblado"
lang["#CROWBAR_NAME"] = "Palanca"
lang["#FIREAXE_NAME"] = "Hacha de Bombero"
lang["#DEATHCLAWWARAXE_NAME"] = "Hacha de Guerra de Sanguinario"
lang["#DEATHCLAWGAUNTLET_NAME"] = "Guantelete de Sanguinario"
lang["#FISTOFMORTIS_NAME"] = "Puño de la Muerte"
lang["#WARAXE_NAME"] = "Hacha de Guerra"
lang["#KATANA_NAME"] = "Katana"
lang["#MACHETE_NAME"] = "Machete"
lang["#BOWIEKNIFE_NAME"] = "Cuchillo Bowie"
lang["#BLOODNAP_NAME"] = "Siesta Sangrienta"
lang["#REBARCLUB_NAME"] = "Porra de Varilla"
lang["#SHISHKEBAB_NAME"] = "Shishkebab"
lang["#SPIKEKNUCKLES_NAME"] = "Nudillos de Púas"
lang["#SUPERSLEDGE_NAME"] = "Super Martillo"
lang["#9IRON_NAME"] = "Hierro 9"
lang["#BASEBALLBAT_NAME"] = "Bate de Béisbol"
lang["#BASEBALLBAT_STARTER_NAME"] = "Bate de Béisbol Viejo"
lang["#BASEBALLBAT_SCRAPYARD_NAME"] = "Aplastachatarra"
lang["#CATTLEPROD_NAME"] = "Picana Eléctrica"
lang["#SUPERCATTLEPROD_NAME"] = "Super Picana Eléctrica"
lang["#CLEAVER_NAME"] = "Cuchilla de Carnicero"
lang["#DRESSCANE_NAME"] = "Bastón de Vestir"
lang["#LEADPIPE_NAME"] = "Tubo de Plomo"
lang["#KITCHENKNIFE_NAME"] = "Cuchillo de Cocina"
lang["#DRIVER_NAME"] = "Palo de Golf"
lang["#NAILBOARD_NAME"] = "Tabla con Clavos"
lang["#HATCHET_NAME"] = "Hacha de Mano"
lang["#PIPEWRENCH_NAME"] = "Llave Inglesa"
lang["#STRAIGHTRAZOR_NAME"] = "Navaja de Afeitar"
lang["#ROLLINGPIN_NAME"] = "Rodillo"
lang["#SLEDGE_NAME"] = "Mazo"
lang["#WEIGHTBAR_NAME"] = "La de 45 Libras"
lang["#SHOVEL_NAME"] = "Pala"
lang["#HOE_NAME"] = "Azada"
lang["#SPADE_NAME"] = "Lampa"
lang["#MOP_NAME"] = "Fregona"
lang["#SWITCHBLADE_NAME"] = "Navaja Automática"
lang["#WAKAZASHI_NAME"] = "Wakizashi"
lang["#BUMPER_NAME"] = "Espada Parachoques"
lang["#BATON_NAME"] = "Porra"
lang["#ALIENBATON_NAME"] = "Porra de Choque Alienígena"
lang["#POWERFIST_NAME"] = "Puño de Fuerza"
lang["#SICKLE_NAME"] = "Hoz"
lang["#BONEKNIFE_NAME"] = "Cuchillo de Hueso"
lang["#BONECLUB_NAME"] = "Porra de Hueso"
lang["#BONESWORD_NAME"] = "Espada de Hueso"
lang["#CANOPENER_NAME"] = "Abrelatas"
lang["#BEAREROFTHESTANDARD_NAME"] = "Portaestandarte"
lang["#ENDBOSSKNIFE_NAME"] = "Cuchilla de Muñeca de Frank Horrigan"

--Descripciones de Armas Cuerpo a Cuerpo
lang["#BOTTLESHANK_DESC"] = "Botella rota. La etiqueta está gastada hasta quedar irreconocible, pero puedes distinguir dos letras: M.J.\n\nPodría usarse como arma de combate cercano, si te gusta eso."
lang["#STORMCUTTER_DESC"] = "Forjada en electricidad, esta gran hoja es capaz de cercenar la cabeza de cualquier bandido que se interponga en tu camino.\n\nVe; pon a prueba tu hoja. Conviértela en una leyenda."
lang["#ZAPGLOVE_DESC"] = "Un guante con una rejilla eléctrica en los nudillos, diseñado para proporcionar una alternativa electrizante al puñetazo de un lego.\n\nAdvertencia: La descarga estática después de usar este guante es notablemente potente; asegúrate de descargarte a tierra después."
lang["#INDUSTRIALGAUNTLET_DESC"] = "Un guante con una hoja de sierra acoplada al dorso de la mano, diseñado para proporcionar una alternativa sangrienta al puñetazo de un lego.\n\nAdvertencia: Muchos usuarios han perdido dedos accidentalmente al quitárselo. Procede con precaución."
lang["#PLASMACUTTER_DESC"] = "Una herramienta de corte diseñada para fundir rápidamente el acero, tanto en contextos industriales como de rescate.\n\n¿En tus manos? Desde luego, no rescatarás a nadie."
lang["#PICKAXE_DESC"] = "Por desgracia, no podrás extraer mineral de coches fácilmente con esto.\n\n¡Sin embargo, puedes extraer fácilmente la materia gris de alguien!"
lang["#SWORD_DESC"] = "Miles de pliegues forman esta hoja, forjada con acero de antes de la guerra y templada en sangre de después de la guerra.\n\nTodo eso es irrelevante; esta hoja será un palo afilado en un momento de necesidad."
lang["#BONECLUB_DESC"] = "Un hueso grande convertido en una porra...\n\nno vas a usarlo, ¿verdad?"
lang["#SICKLE_DESC"] = "Por desgracia, los campos de trigo son escasos en el yermo. Sin embargo, es lo suficientemente afilada para separar un cuello de un cuerpo.\n\nAsesinar es ciertamente más rentable que cultivar."
lang["#BONEKNIFE_DESC"] = "Esta arma primitiva se compone de un pequeño trozo de hueso unido a una afilada astilla de obsidiana. Cortará la piel de un sanguinario, eso seguro."
lang["#BONESWORD_DESC"] = "Esta arma primitiva se compone de una cornamenta unida a una afilada losa de obsidiana. Esta no solo cortará la piel de un sanguinario, sino que lo decapitará."
lang["#COMBATKNIFE_DESC"] = "Un cuchillo de combate utilizado principalmente por el ejército.\n\nUn elemento básico del combate cuerpo a cuerpo, que lo convirtió en un cuchillo popular entre entusiastas y supervivientes.\n\nSe puede usar como bayoneta en algunas armas."
lang["#COMBATKNIFE_STARTER_DESC"] = "Un viejo cuchillo de mierda. Una vez usado por el ejército, ahora abandonado por el tiempo. No muy afilado, pero aún se podría pinchar algo con él."
lang["#CROWBAR_DESC"] = "Una simple barra de acero con un extremo curvo, pero una herramienta eficaz.\nA pesar de su intención como dispositivo utilitario, el peso y el equilibrio de esta herramienta la convierten en un eficaz recurso como arma cuerpo a cuerpo."
lang["#DEATHCLAWWARAXE_DESC"] = "Un hacha, hecha con dos cuernos de sanguinario. Por desgracia, los cuernos de sanguinario no son muy afilados en los bordes; esto es funcionalmente solo una maza con forma de hacha."
lang["#DEATHCLAWGAUNTLET_DESC"] = "Las garras de este poderoso puño fueron tomadas directamente de un Sanguinario, utilizadas para despedazar a sus presas. Se ajusta cómodamente a tu muñeca.\n\nLa fuerza de un Sanguinario no está incluida."
lang["#FISTOFMORTIS_DESC"] = "Las garras de este poderoso puño fueron tomadas directamente de Unguem Mortis, el Sanguinario más fuerte del oeste.\nSe parece bastante a un guantelete de sanguinario normal.\n\nA diferencia de un guantelete de sanguinario normal, sientes la fuerza de un Sanguinario fluir por tus venas."
lang["#WARAXE_DESC"] = "¡Un hacha de guerra de bárbaro, del tipo que el propio Grognak usaría!\n\nNo hay nada cómico en cómo vas a usarla."
lang["#BOWIEKNIFE_DESC"] = "Creado originalmente para duelos, el Cuchillo Bowie representa la respuesta perfecta para una pelea con cuchillos.\n\nTambién es probablemente la respuesta perfecta para un necrófago, pero no podían saberlo cuando lo hicieron."
lang["#BLOODNAP_DESC"] = "¿Lo mejor de un cuchillo?\n\nNo falla y siempre está cargado."
lang["#FIREAXE_DESC"] = "El hacha de bombero es un hacha con mango de madera y una pesada cabeza de acero destinada a uso en extinción de incendios. El largo mango de madera dura permite ataques amplios a distancia razonable y está parcialmente recubierto de goma para asegurar un buen agarre del arma.\n\nOriginalmente diseñada para derribar paredes y puertas, esta arma puede infligir graves daños a un objetivo blando."
lang["#KATANA_DESC"] = "Arma cuerpo a cuerpo mortal.\nAleación de acero trabajada que ha sido perfectamente afilada y aplanada más de mil veces para producir una hoja perfecta; útil para todos los estilos de combate con hoja, como apuñalar, cortar y lanzar estocadas."
lang["#MACHETE_DESC"] = "Arma cuerpo a cuerpo afilada.\nMetal reutilizado con forma de hoja de longitud media. Un extremo tiene un mango envuelto en cuero para un buen agarre.\nSe puede usar como arma cuerpo a cuerpo de alcance medio."
lang["#REBARCLUB_DESC"] = "Arma cuerpo a cuerpo contundente improvisada.\nUna varilla de acero corrugado como mango y un trozo de hormigón como cabeza de martillo; Es una opción cuestionable como arma, es efectiva pero está desequilibrada, lo que la hace difícil de usar.\nSe puede usar como arma de alcance medio."
lang["#SHISHKEBAB_DESC"] = "Arma cuerpo a cuerpo incendiaria.\nUn diseño muy elaborado de gran intelecto; algún tipo de combustible fluye hacia una llama que rodea la afilada hoja plana del dispositivo, verdaderamente maravilloso.\nSe puede usar como un arma eficaz de alcance medio que puede incendiar a sus objetivos."
lang["#SPIKEKNUCKLES_DESC"] = "Arma cuerpo a cuerpo cruda.\nMetal reutilizado con forma de agarre con púas cónicas en los nudillos.\nSe puede usar como arma de combate cercano."
lang["#SUPERSLEDGE_DESC"] = "Arma cuerpo a cuerpo contundente eficaz.\nUn gran pistón hidráulico en el extremo de un mango de asta larga; El pistón y el mango forman una forma de martillo, el pistón está alimentado por fuerzas invisibles.\nSe puede usar como un arma aplastante eficaz, que también es de largo alcance."
lang["#9IRON_DESC"] = "Este viejo hierro 9 está doblado y golpeado después de muchos años de exposición a los elementos."
lang["#BASEBALLBAT_DESC"] = "Este bate de béisbol de madera, totalmente americano, sacará cualquier cosa del parque."
lang["#BASEBALLBAT_STARTER_DESC"] = "Un viejo bate de béisbol de madera. Una vez usado para batear bolas fuera del parque, ahora es bueno para aplastar la cabeza de una amenaza."
lang["#BASEBALLBAT_SCRAPYARD_DESC"] = "Un bate de béisbol de metal usado por la Tribu 80s.\n\nToma un bate de aluminio, templa, envuelve un poco de cuero de brahmán alrededor del mango y encadena un par de hojas de sierra circulares y obtienes esta desagradable pieza de trabajo.\n\n''Una bala .308 en el codo significa que ya no puedo usar esto. Batea a las vallas, chico.'' - Tweak"
lang["#SUPERCATTLEPROD_DESC"] = "Una picana eléctrica modelo 'Best Friend' del granjero de Wattz Electronics. Este modelo ha sido mejorado para aumentar la descarga eléctrica."
lang["#CATTLEPROD_DESC"] = "Normalmente se usa para arrear ganado testarudo, se ha reutilizado como un arma no letal contra humanos.\n\nAdemás de las puntas similares a las de un Taser que se encuentran normalmente en las picanas eléctricas, se ha equipado con una gruesa bobina de metal electrificada alrededor del extremo de golpe, conectada a un par de baterías pegadas con cinta cerca del mango."
lang["#CLEAVER_DESC"] = "¡Un utensilio de cocina hecho específicamente para trocear, descuartizar, picar esa carne!"
lang["#DRESSCANE_DESC"] = "Un bastón de vestir de antes de la guerra.\n\nComo todas las cosas propiedad de la alta sociedad, está en excelentes condiciones y está hecho de una madera negra fuerte y brillante con un mango de marfil."
lang["#LEADPIPE_DESC"] = "Un arma cuerpo a cuerpo ampliamente disponible y económica. Uno de los extremos tiene cinta adhesiva para mejorar el agarre, mientras que el otro está rematado con un accesorio de tubería.\n\nPrecaución: Conocido por el estado de Nueva California por causar defectos de nacimiento.\n\n#WIP_DESC"
lang["#HATCHET_DESC"] = "Es un hacha de mano con mango de madera con agarre de goma para cortar leña y extremidades por igual.\n\nA diferencia de las hachas arrojadizas, estas no están equilibradas para su uso como arma de proyectil."
lang["#KITCHENKNIFE_DESC"] = "Para todas tus necesidades relacionadas con películas de terror, o si solo necesitas cortar unas zanahorias."
lang["#DRIVER_DESC"] = "Asegúrate siempre de tener la última versión."
lang["#NAILBOARD_DESC"] = "Esta tabla 2x4 tiene varios clavos atravesados, con un eje tallado para asegurar un mejor agarre.\n\nComúnmente utilizado por supermutantes y otros idiotas."
lang["#PIPEWRENCH_DESC"] = "Una llave inglesa típica utilizada por los mecánicos para lastimar a la gente. ¡También es buena para desarmar vehículos!"
lang["#STRAIGHTRAZOR_DESC"] = "Una navaja de afeitar anticuada con un mango de madera pulida. Aunque su hoja es corta, es ligera y puede asestar varios golpes cortantes en rápida sucesión."
lang["#ROLLINGPIN_DESC"] = "Un rodillo de madera simple que se usa en la cocina para aplanar la masa, con un par de finas rayas de sangre en un lado."
lang["#SLEDGE_DESC"] = "La especialidad del hombre fuerte hace acto de presencia en el yermo."
lang["#WEIGHTBAR_DESC"] = "Claramente nunca destinada a ser usada como arma, esta masa malévola de plomo y acero no es ajena a ser blandida solo por los más fuertes de entre los fuertes."
lang["#SHOVEL_DESC"] = "Una pala de mango de madera. Útil para desenterrar tumbas o golpear a tus objetivos desde la distancia máxima posible. Diseñada para aquellos que son verdaderos caballeros de la pala."
lang["#HOE_DESC"] = "Una vieja herramienta de jardinería. Un palo largo con una gruesa pieza de metal unida al extremo. No estás seguro de lo que planeas hacer con esto, pero podría resultar ser un arma útil."
lang["#SPADE_DESC"] = "Similar a una pala, pero significativamente más pequeña. ¿Cuál es la diferencia real entre estas dos? Igualmente aplastarán una cabeza."
lang["#MOP_DESC"] = "Puedes usar esto para limpiar la sangre del suelo de tus enemigos después de golpearlos violentamente hasta la muerte con ella."
lang["#SWITCHBLADE_DESC"] = "La hoja de este pequeño cuchillo está sujeta por un muelle. Cuando se presiona un botón en el mango, la hoja sale disparada con un satisfactorio sonido 'Sssssshk'."
lang["#WAKAZASHI_DESC"] = "Un cuchillo corto finamente elaborado.\n\n¡La punta parece estar diseñada para perforar armaduras!"
lang["#BUMPER_DESC"] = "Más un trozo de acero en bruto que un arma, la espada parachoques es un arma extremadamente pesada y afilada creada a partir del parachoques de un automóvil, que causa un daño masivo."
lang["#BATON_DESC"] = "Un modelo plegable de porra policial, utilizado por varios departamentos de policía antes de la Gran Guerra."
lang["#ALIENBATON_DESC"] = "Una porra de choque de origen extraterrestre, más adecuada para manos alienígenas que para las humanas.\n\nRecuerda a la picana eléctrica humana, pero notablemente carece de características de seguridad. Ser golpeado por esto sería muy, muy desagradable."
lang["#POWERFIST_DESC"] = "Originalmente utilizado como hardware de antes de la guerra para equipos de demolición en lugar de como arma.\n\nEl Puño de Fuerza usa un ariete neumático para asestar golpes potentes de velocidad media a los atacantes."
lang["#CANOPENER_DESC"] = "Algo especial para aquellos cuya agresión sin abrir provocaría una guerra por algo tan trivial como los frijoles de antes de la guerra.\n\n¡Solo localiza algunas de esas latas preciosas y empieza a golpear, nena!"
lang["#BEAREROFTHESTANDARD_DESC"] = "Llevado al frente de una carga de la Hermandad, este asta de bandera reforzada ahora sirve para un propósito más directo. El emblema de la Hermandad del Acero cuelga de su estandarte con ceniza y polvo del desierto, un recordatorio de que los símbolos pueden golpear con tanta fuerza como el acero. Algunos dicen que luchar bajo el estandarte estabiliza la mano y endurece el corazón. Otros simplemente aprecian un arma que les permite golpear a sus enemigos con ideología."
lang["#ENDBOSSKNIFE_DESC"] = "Una hoja de combate brutal y retráctil montada debajo de un guantelete de servoarmadura, una vez parte del arsenal personal del soldado más temido del Enclave. La cuchilla de muñeca zumba débilmente cuando se activa, su filo monomolecular vibrando con energía suprimida. Diseñada para ejecuciones a quemarropa, se despliega con un chasquido hidráulico capaz de cortar placas de blindaje o hueso con igual facilidad. Un residuo negro seco mancha la bisagra, un testamento silencioso del trabajo de campo de su antiguo dueño."

--███████╗███╗   ██╗███████╗██████╗  ██████╗██╗   ██╗
--██╔════╝████╗  ██║██╔════╝██╔══██╗██╔════╝╚██╗ ██╔╝
--█████╗  ██╔██╗ ██║█████╗  ██████╔╝██║  ███╗╚████╔╝
--██╔══╝  ██║╚██╗██║██╔══╝  ██╔══██╗██║   ██║ ╚██╔╝
--███████╗██║ ╚████║███████╗██║  ██║╚██████╔╝  ██║
--╚══════╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚═════╝   ╚═╝

lang["#GATLASER_NAME"] = "Ametralladora Láser"
lang["#HKL40_NAME"] = "[WIP] P.E L-40 Apollo"
lang["#LASERGUN_NAME"] = "Pistola Láser"
lang["#PLASMAGUN_NAME"] = "Rifle de Plasma"
lang["#TRILASER_NAME"] = "Pistola Láser de Triple Haz"
lang["#PLASMACASTER_NAME"] = "Centro de Plasma"
lang["#PLASMACASTERTURBO_NAME"] = "Centro de Plasma Turbo"
lang["#GAUSSRIFLE_NAME"] = "Rifle Gauss"
lang["#GAUSSPISTOL_NAME"] = "Pistola Gauss"
lang["#M72_NAME"] = "Rifle Gauss M72"
lang["#RCW_NAME"] = "Laser RCW"
lang["#SOLARCANNON_NAME"] = "Cañón Solar"

lang["#INCENERATOR_NAME"] = "Incinerador"
lang["#FLAMER_NAME"] = "Lanzallamas"
lang["#P95_NAME"] = "P95 Turbo Plasma Rifle"
lang["#WATZ2k_NAME"] = "Rifle Láser Wattz 2000"
lang["#WATZ1k_NAME"] = "Pistola Láser Wattz 1000"
lang["#HOLORIFLE_NAME"] = "Rifle Holograma"
lang["#PULSERIFLE_NAME"] = "Rifle de Pulso YK42B"
lang["#PPK12_NAME"] = "Pistola Gauss PPK12"
lang["#PLASMADEFENDER_NAME"] = "Defensor de Plasma"
lang["#UNIQUEPLASMADEFENDER_NAME"] = "Semper Purus"
lang["#ENDBOSSPLASMAGUN_NAME"] = "Cañón de Plasma de Frank Horrigan"

-- Alienígena

lang["#ALIENDISINTEGRATOR_NAME"] = "Desintegrador Alienígena"
lang["#ALIENBLASTER_NAME"] = "Alien Blaster"
lang["#ALIENATOMIZER_NAME"] = "Atomizador Alienígena"
lang["#CAPTAINSSIDEARM_NAME"] = "Arma Secundaria del Capitán"

-- Plasma

lang["#PLASMAGUN_PISTOL_NAME"] = "Pistola de Plasma"
lang["#PLASMAGUN_MAGNUM_NAME"] = "Pistola de Plasma Pesada"
lang["#PLASMAGUN_RIFLE_NAME"] = "Rifle de Plasma"
lang["#PLASMAGUN_CARBINE_NAME"] = "Carabina de Plasma"
lang["#PLASMAGUN_REPEATER_NAME"] = "Repetidor de Plasma"
lang["#PLASMAGUN_PDW_NAME"] = "PDW Plasma"
lang["#PLASMAGUN_MULTIPLASRIFLE_NAME"] = "Rifle Multiplas"
lang["#PLASMAGUN_MULTIPLASPISTOL_NAME"] = "Pistola Multiplas"
lang["#PLASMAGUN_SNIPERPISTOL_NAME"] = "Pistola de Francotirador de Plasma"
lang["#PLASMAGUN_SNIPERRIFLE_NAME"] = "Rifle de Francotirador de Plasma"

-- Láser

lang["#LASERGUN_PISTOL_NAME"] = "Pistola Láser"
lang["#LASERGUN_PISTOL_STARTER_NAME"] = "Pistola Láser Desenfocada"
lang["#LASERGUN_RIFLE_STARTER_NAME"] = "Carabina Láser Desenfocada"
lang["#LASERGUN_BLASTER_NAME"] = "Ráfaga Láser"
lang["#LASERGUN_RIFLE_NAME"] = "Rifle Láser"
lang["#LASERGUN_CARBINE_NAME"] = "Carabina Láser"
lang["#LASERGUN_REPEATER_NAME"] = "Repetidor Láser"
lang["#LASERGUN_PDW_NAME"] = "PDW Láser"
lang["#LASERGUN_SNIPERPISTOL_NAME"] = "Pistola de Carga Láser"
lang["#LASERGUN_SNIPERRIFLE_NAME"] = "Rifle de Carga Láser"

-- Dispersión

lang["#LASERGUN_SCATTERRIFLE_NAME"] = "Rifle Láser de Dispersión"
lang["#LASERGUN_SCATTERPISTOL_NAME"] = "Pistola Láser de Dispersión"
lang["#LASERGUN_SCATTERREPEATER_NAME"] = "Repetidor Láser de Dispersión"
lang["#LASERGUN_SCATTERPDW_NAME"] = "PDW Láser de Dispersión"
lang["#LASERGUN_SCATTERCARBINE_NAME"] = "Carabina Láser de Dispersión"
lang["#LASERGUN_SCATTERBLASTER_NAME"] = "Ráfaga Láser de Dispersión"
lang["#LASERGUN_SNIPERSCATTERPISTOL_NAME"] = "Pistola de Carga Láser de Dispersión"
lang["#LASERGUN_SNIPERSCATTERRIFLE_NAME"] = "Rifle de Carga Láser de Dispersión"

-- Triple Haz

lang["#TRILASERPISTOL_NAME"] = "Pistola Láser de Triple Haz"
lang["#TRILASERRIFLE_NAME"] = "Rifle Láser de Triple Haz"

--Descripciones de Armas de Energía
lang["#GATLASER_DESC"] = "Una ametralladora láser de múltiples prismas.\n\nDiseñada específicamente para uso militar, se encontraba en fase de prototipo al inicio de la Gran Guerra.\n\nAlimentada por Cargas de Electrones, estas armas tienen una alta cadencia de fuego y un generoso depósito de batería."
lang["#HKL40_DESC"] = "Un diseño de ametralladora láser de múltiples prismas robado por Poseidon Energy de H&K a finales de la década de 2060. El Apollo fue originalmente concebido como una mejora del diseño L-30 producido en masa, pero se reorientó para cumplir un papel pesado antia blindaje más adelante en su desarrollo.\n\nEl Apollo está equipado con una miríada de tecnología patentada de Poseidon Energy, lo que provoca que el láser tenga un efecto deflagrante en la armadura, obligando a que generalmente se monte en un trípode para su uso debido a su peso extremo."
lang["#INCENERATOR_DESC"] = "Diseñado por alguna facción de alta tecnología que afirma ser el gobierno del viejo mundo, este monstruo dispara napalm como un mortero."
lang["#AERPISTOL_DESC"] = "La Pistola Láser AER7 es un láser de grado militar, utilizado esporádicamente por unidades policiales y militares antes de la guerra. Utiliza un conjunto de cristales que la hace mucho más letal que una Wattz."
lang["#AERPISTOL_STARTER_DESC"] = "Una pistola láser defectuosa ensamblada a partir de otras pistolas láser defectuosas."
lang["#AERRIFLE_STARTER_DESC"] = "Una carabina láser defectuosa ensamblada a partir de otras pistolas láser defectuosas."
lang["#AERRIFLE_DESC"] = "El Rifle Láser AER9 es un rifle láser de alta potencia que utiliza un conjunto de cristales, y estaba en camino de ser desplegado por unidades militares nacionales antes de la Gran Guerra."
lang["#PLASMACASTER_DESC"] = "El Centro de Plasma Winchester P94 se utilizó como herramienta de destrucción industrial que empleaba proyectiles de plasma antes de la guerra.\n\nAhora es solo una herramienta de destrucción que usa proyectiles de plasma."
lang["#PLASMAGUN_DESC"] = "Los rifles de plasma son armas de alta tecnología que encuentran numerosas aplicaciones en los campos militar e industrial.\n\nEl proyectil de plasma es un toroide de gas de hidrógeno sobrecalentado que inflige altos niveles de daño tanto térmico como cinético al objetivo, derritiendo la mayoría de los tipos de armaduras y causando quemaduras masivas de tercer y cuarto grado."
lang["#M72_DESC"] = "El M72 Gauss Driver es de diseño alemán. Utiliza un campo electromagnético para impulsar proyectiles a velocidades tremendas... y perforar casi cualquier obstáculo. Su alcance, precisión y poder de parada son casi inigualables."
lang["#GAUSSRIFLE_DESC"] = "El Rifle Gauss utiliza inducción magnética para impulsar un proyectil a una velocidad increíble y devastadora.\n\nCada disparo se puede cargar para obtener el máximo daño manteniendo presionado el gatillo un momento antes de soltarlo."
lang["#GAUSSPISTOL_DESC"] = "La Pistola Gauss PPK12 tiene un alcance, precisión y daño inigualables en su clase."
lang["#RCW_DESC"] = "Un precursor de la ametralladora láser, la característica única de esta arma es la adición de un banco de condensadores rotatorio.\n\nEsta rotación de condensadores permite que el Laser RCW opere como un 'rifle de asalto láser', evitando las limitaciones de cadencia de fuego de un diseño de condensador único."
lang["#TRILASER_DESC"] = "Un arma muy modificada formada por la combinación de múltiples láseres.\n\nDispara 3 haces de máxima potencia por cada presión del gatillo, consumiendo la misma cantidad de munición.\n\nLa producción de daño es masivamente mejorada en comparación con el Rifle Láser estándar, pero su diseño improvisado apresuradamente requiere un mantenimiento mucho más frecuente."
lang["#FLAMER_DESC"] = "Versión Varmiter del Lanzallamas Flambe modelo 450. Dispara napalm caliente para la 'exterminación de insectos'."
lang["#SOLARCANNON_DESC"] = "Desarrollado por Poseidon Energy antes de la Gran Guerra, el Cañón Solar es un arma de energía que puede disparar una bola de energía solar utilizando células de microfusión.\n\nEstaba destinado para el control de multitudes, pero se descubrió que era demasiado inestable."

-- Alienígena
lang["#ALIENDISINTEGRATOR_DESC"] = "⏃ ⏃⍜⏃⎎⟒⍀⎎⎍⎍ ⏃⏁⍜⋏⏃⏁⟟☾ ⏃⌇⌇⏁⎍⎍⏁ ⍀⟟⎎⟒, ⌖⎍⏃⍀⏁⋏⟒⟒⎅ ⏁⍜ ⎍⟟⎎⎍⎅⟒⎅ ⏃ ⍑⍜⌇⏁⟟⎍⎍ ⏃⎍⟟⟒⋏.\n\n⊗⎍⍀⏃⍀ ⍙⍜⎍⎅ ⏃⟒ ⏃⍀⍜⎍⎅." -- Idioma Minecraft Enderman
lang["#ALIENBLASTER_DESC"] = "⏃ ⌇⎍⟟☾⌇ ⎍⏁⏁⟒⎍ ⏃⟟⌇⏁⍜⎍, ☾⍀⟒⏃⏁⟒⎅ ⏁⍜ ⌇⟒⍜⏁ ⏃⎍⟟⟒⋏ ⎎⏃⎍⋏⏃.\n\n⌖⟒'⎍⍀⟒ ⋏⍜⏁ ⏃☽⏁⍜⎍⟒⎍ ⏁⍀⏃⋏⌇⎍⟟⏁⟒⋏☌ ⊑⟟⌇, ⏃⍀⟒ ⎍⍀⟟⍜⎍?" -- Idioma Minecraft Enderman
lang["#CAPTAINSSIDEARM_DESC"] = "⏁⊑⟟⌇ ⏃⟟⌇⏁⍜⎍, ⋔⏃⋏⍜⎎⎍⎅⍜⍀⍀⎍⏁⟒⎅ ⏃⎍⎅ ⊑⍜ ⊑⟒ ⎍⟒☌⟒⋏⎅⏃⍀⟒⎍ ⏃⎍⟟⟒⋏ ⌇⋏⟟⊑ ⊗⎍⍀⏃, ⏁⍀⏃⎅⍀⟒⎍⎅ ⋔⟟⎍⎍⍜⋏⌇ ⍜⎎ ⎍⟟☌⊑⏁⟟⟒⏃⍀⌇ ⏁⍜ ⊑⟒ ⍀⏃⋏⟒⏁ |Earth|.\n\n⟒⏁ ⍙⏃⌇ ⟒⎎⌇⍜⟒☌⟟⎍⟟⏁⎍⟟⏁⟒⎅ ⎍⌇⟒⎅ ⊑⍜ ⊑⟒ ⏃⎍⟟⟒⋏ ☾⏃⏁⏁⟟⏃⋏⌇.\n\n⋏⍜⍙, ⟟⏁'⌇ ⏁⟟⋔⟒ ⏁⍜ ⋏⏃☾⟒ ⊑⟒ ⊑⎍⋏⏃⋏ ⍀⏃☾⟒ ⏃⟒⋏⎅ ⏁⍜ ⍙⍜⎍⍀ ⍙⟟⌇⌇." -- Idioma Minecraft Enderman
lang["#ALIENATOMIZER_DESC"] = "⏃ ⍀⏃⌿⟟⎅ ⎎⟟⍀⟒ ⌿⟟⌇⏁⍜⌰ ⎎⍜⍀ ⏃⌰⟟⟒⋏ ⊑⏃⋏⎅⌇.\n\n⏁⊑⍜⎍☌⊑ ⟟⏁ ⎅⍜⟒⌇⋏'⏁ ⊑⟟⏁ ⏃⌇ ⊑⏃⍀⎅ ⏃⌇ ⏃ ⏚⌰⏃⌇⏁⟒⍀, ⟟⏁ ⎎⟟⍀⟒⌇ ⌇⟟☌⋏⟟⎎⟟☊⏃⋏⏁⌰⊬ ⎎⏃⌇⏁⟒⍀." -- Idioma Minecraft Enderman

lang["#AER9_DESC"] = "El AER9 es un arma de alta tecnología que emite un haz concentrado de luz coherente, con suficiente potencia para causar daños considerables.\n\nMucho más robusto y fiable, es mucho más común de encontrar que los modelos que le siguieron."
lang["#AEP7_DESC"] = "El láser AEP7 entró en servicio para reemplazar al N99 como arma secundaria estándar para las fuerzas militares.\n\nMientras que los modelos civiles utilizan un diodo láser, los modelos militares emplean una cámara de enfoque fotónico y un conjunto de cristales, creando un haz más concentrado y destructivo."
lang["#PLASMADEFENDER_DESC"] = "Pistola de Plasma Glock 86, diseñada por la inteligencia artificial Gaston Glock.\n\nDispara un pequeño proyectil de plasma sobrecalentado.\n\nAlimentada por Células de Microfusión."
lang["#UNIQUEPLASMADEFENDER_DESC"] = "Una versión de presentación de la Glock 86.\n\nA pesar de que la plata y los grabados no proporcionan ninguna ventaja táctica, esta pieza fue ligeramente mejorada para el combate mientras aún se mantenía con cariño. 'Coronel Samuel Vimes' está grabado a lo largo de un lado con letras pequeñas."
lang["#PULSERIFLE_DESC"] = "El YK42B es un arma de pulso eléctrico que fue desarrollada por el Yuma Flats Energy Consortium.\n\nSe considera un arma muy superior a la pistola de pulso YK32, con una mayor capacidad de carga y alcance."
lang["#WATZ2k_DESC"] = "El Wattz 2000 es un rifle láser de alta tecnología de grado de consumo que utiliza luz de alta energía como medio de daño, alcanzando a su objetivo al instante a cualquier distancia."
lang["#WATZ1k_DESC"] = "El Wattz 1000 es un láser de grado de consumo creado por la Corporación Wattz. Utiliza un diodo de enfoque láser en lugar de un conjunto de cristales, lo que disminuye su daño."
lang["#PPK12_DESC"] = "Un arma de mano de diseño alemán que utiliza bobinas electromagnéticas para impulsar proyectiles de metal a velocidades extremadamente altas. Disparan una bala increíblemente pequeña de 2mm a velocidades justo por debajo de la velocidad de la luz, atravesando casi cualquier armadura."
lang["#P95_DESC"] = "Un prototipo temprano, el rifle de plasma Winchester P95 nunca se produjo oficialmente en masa debido a su costoso material y su diseño voluminoso.\n\nA pesar de esto, el arma es mortal gracias a su acelerador de plasma experimental, que permite que el arma proyecte plasma a velocidades extremas."
lang["#ENDBOSSPLASMAGUN_DESC"] = "Un monstruoso proyector de plasma de mano fusionado directamente a la armadura del operativo del Enclave Frank Horrigan. Diseñado para canalizar una oleada concentrada de plasma ionizado a través de conductos sellados magnéticamente, esta arma vaporiza cualquier cosa lo suficientemente desafortunada como para estar en su camino. Su sistema de refrigeración personalizado evita que se derrita su propia carcasa, apenas."

-- ██████╗ ██╗   ██╗███╗   ██╗███████╗
--██╔════╝ ██║   ██║████╗  ██║██╔════╝
--██║  ███╗██║   ██║██╔██╗ ██║███████╗
--██║   ██║██║   ██║██║╚██╗██║╚════██║
--╚██████╔╝╚██████╔╝██║ ╚████║███████║
-- ╚═════╝  ╚═════╝ ╚═╝  ╚═══╝╚══════╝

--Rifle
lang["#ASSAULTCARBINE_NAME"] = "Carabina de Asalto"
lang["#MARKSMANCARBINE_NAME"] = "Carabina de Tirador"
lang["#PATRIOT_NAME"] = "El Patriota"
lang["#ANTIMAT_NAME"] = "Rifle Antimaterial"
lang["#BLACKARROW_NAME"] = "Flecha Negra"
lang["#LEVERGUN_NAME"] = "Rifle de Monte"
lang["#COWBOYREPEATER_NAME"] = "Repetidora de Vaquero"
lang["#COWBOYREPEATER_STARTER_NAME"] = "Repetidor de Vaquero Antiguo"
lang["#TRAILCARBINE_NAME"] = "Carabina de Repetición"
lang["#DKS_NAME"] = "Rifle de Francotirador"
lang["#FAMAS_NAME"] = "FAMAS"
lang["#LIBERTY_NAME"] = "Libertad"
lang["#FAL_NAME"] = "Rifle de Batalla"
lang["#FNC_NAME"] = "Carabina de Batalla"
lang["#HUNTING_NAME"] = "Rifle de Caza"
lang["#R91_NAME"] = "Rifle de Asalto"
lang["#SERVICERIFLE_NAME"] = "Rifle de Servicio"
lang["#AK_NAME"] = "Rifle Soviético"
lang["#TYPE93_NAME"] = "Rifle de Asalto Chino"
lang["#PIPERIFLE_NAME"] = "Arma de Tubo"
lang["#PIPERIFLE_STARTER_PISTOL_NAME"] = "Pistola de Chatarra"
lang["#PIPERIFLE_STARTER_RIFLE_NAME"] = "Rifle de Chatarra"
lang["#PIPERIFLE_STARTER_SMG_NAME"] = "Subfusil de Chatarra"
lang["#PIPERIFLEBOLT_NAME"] = "Arma de Tubo de Cerrojo"
lang["#VARMINT_NAME"] = "Rifle de Alimañas"
lang["#VARMINT_STARTER_NAME"] = "Rifle de Alimañas de Bubba"
lang["#BAR_NAME"] = "Rifle Automático Browning"
lang["#MACHINEGUN_NAME"] = "Ametralladora Ligera"
lang["#HMACHINEGUN_NAME"] = "T-24 GPMG"
lang["#G11_NAME"] = "Rifle Salvo"
lang["#RANCOR_NAME"] = "Repetidor Rencor"
lang["#BOZAR_NAME"] = "Bozar"
lang["#ASVAL_NAME"] = "AS-Val"
lang["#VSK_NAME"] = "VSK"
lang["#M1GARAND_NAME"] = "M1 Garand"
lang["#M1903_NAME"] = "M1903 Springfield"


lang["#SVD_NAME"] = "Francotirador Soviético"
lang["#RHODIESPECIAL_NAME"] = "Especial Rodesiano"
lang["#R91INFILTRATOR_NAME"] = "Infiltrador"
lang["#R91PERFORATOR_NAME"] = "Perforador"
lang["#R91WANDA_NAME"] = "Wanda"
lang["#RATSLAYER_NAME"] = "Matarratas"
lang["#R91TELAVIV_NAME"] = "Rifle de Combate de Tel Aviv"
lang["#SRIFLE12.7_NAME"] = "Carabina Thumper 12.7mm"
lang["#SRIFLECOMRADE_NAME"] = "Camarada-15"
lang["#SRIFLEPARTIZAN_NAME"] = "Partisano"
lang["#SRIFLEM199_NAME"] = "Rifle de Servicio M199"
lang["#SRIFLEROBERTS_NAME"] = "Rifle de Entrenamiento de Roberts"
lang["#HRIFLE_WHITEDEATH"] = "Muerte Blanca"
lang["#TYPE93BD_NAME"] = "Rifle de Asalto Xuanlong"

--Escopeta
lang["#SHOTGUN"] = "Escopeta"
lang["#COMBATSHOTGUN_NAME"] = "Escopeta de Combate"
lang["#SINGLEBARREL_NAME"] = "Escopeta Simple"
lang["#DOUBLEBARREL_NAME"] = "Escopeta de Dolbe Cañon"
lang["#TOZ34_NAME"] = "Escopeta de Caza"
lang["#870_NAME"] = "Escopeta de Bombeo"
lang["#STREETSWEEPER_NAME"] = "Barredora de Calles"
lang["#SPAS12_NAME"] = "Escopeta Policial"
lang["#SALVATION_NAME"] = "Salvación"
lang["#RIOTSHOTGUN_NAME"] = "Escopeta Antidisturbios"
lang["#870ECHO_RED_NAME"] = "Ecos de Redención"
lang["#870ECHO_DEL_NAME"] = "Ecos de Deliberación"
lang["#870ECHO_PERD_NAME"] = "Ecos de Perdición"
lang["#FUDD_NAME"] = "Herencia de Fudd"
lang["#COACHGUN_NAME"] = "Escopeta de Diligencia"
lang["#GRIMSREAVER_NAME"] = "Segador Sombrío"
lang["#ULTIMATUM_NAME"] = "Ultimátum"


--Pistola
lang["#USP_NAME"] = "Pistola de Combate 9mm"
lang["#USP45_NAME"] = "Pistola de Combate .45"
lang["#MAUSER_NAME"] = "Pistola Mauser"
lang["#10MMPISTOL_NAME"] = "Pistola 10mm"
lang["#10MMREVOLVER_NAME"] = "Revólver 10mm"
lang["#12.7MMPISTOL_NAME"] = "Pistola 12.7mm"
lang["#14.5MMPISTOL_NAME"] = "Pistola 14mm"
lang["#357MAGNUM_NAME"] = "Revólver .357"
lang["#357MAGNUM_STARTER_NAME"] = "Magnum Oxidado"
lang["#44MAGNUM_NAME"] = "Revólver .44 Magnum"
lang["#DEAGLE357_NAME"] = "Desert Eagle .357"
lang["#DEAGLE_NAME"] = "Desert Eagle .44"
lang["#WASTELANDHAWK_NAME"] = "Halcón del Yermo"
lang["#HUNTINGREVOLVER_NAME"] = "Revólver de Caza"
lang["#SEQUOIA_NAME"] = "Secuoya del Ranger"
lang["#NEEDLER_NAME"] = "HK Needler"
lang["#M9FS_NAME"] = "Pistola 9mm"
lang["#M9FS_STARTER_NAME"] = "Pistola 9mm Desgastada"
lang["#1911PISTOL_NAME"] = "Pistola .45 Auto"
lang["#1911CAV_NAME"] = "Pistola de Caballería"
lang["#DETECTIVEPISTOL_NAME"] = "Pistola de Detective"
lang["#MARKSMANPISTOL_NAME"] = "Pistola de Tirador"
lang["#GALVANICTHUNDER_NAME"] = "Trueno Galvánico"

lang["#1911DELTA_NAME"] = "Delta Elite"
lang["#THATGUN_NAME"] = "Esa Arma"
lang["#93R_NAME"] = "Rápida 9"
lang["#ELDERSJUDGEMENT_NAME"] = "Juicio del Elder"
lang["#357POLICE_NAME"] = "Magnum de Combate"
lang["#10MMVOLLEY_NAME"] = "Pistola de Ráfaga 10mm"
--subfusil
lang["#9MMSMG_NAME"] = "Subfusil 9mm"
lang["#P90_NAME"] = "PDW 4.7mm"
lang["#10MMSMG_NAME"] = "Subfusil 10mm"
lang["#TOMMYGUN_NAME"] = "Subfusil .45 Auto"
lang["#44TOMMY_NAME"] = "Máquina de Escribir Valentina"
lang["#P90C_NAME"] = "PDW 10mm"
lang["#12.7MMSMG_NAME"] = "Subfusil 12.7mm"

lang["#GREASEGUN_NAME"] = "El Camión Cisterna"

--pesada
lang["#MINIGUN_NAME"] = "Minigun 5mm"
lang["#AVENGER_NAME"] = "Minigun Vengador"
lang["#VINDICATOR_NAME"] = "Minigun Vindicador"
lang["#GAUSS_MINIGUN_NAME"] = "Minigun Gauss"
--otras
lang["#SYRINGER_NAME"] = "Pistola de Dardos"
--lang["#FARTNADE_NAME"] = "Bomba Pedo" -- Esta mierda era muy estúpida.
lang["#RAILRIFLE_NAME"] = "Rifle de Ferrocarril"
lang["#RAILSHOTGUN_NAME"] = "Escopeta de Ferrocarril"

--explosiva
lang["#APW_NAME"] = "APW de 25mm"
lang["#M79_NAME"] = "Rifle De Granadas"
lang["#SKYBREAKER_NAME"] = "Rompecielos"
lang["#FATMAN_NAME"] = "Fat-Man"
lang["#MISSILELAUNCHER_NAME"] = "Lanzamisiles"
lang["#REDGLARE_NAME"] = "Fogonazo Rojo"
lang["#CHINALAKE_NAME"] = "China Lake"
-------------------------------------------------------
--Descripciones de Armas de Fuego
-------------------------------------------------------
--rifle
lang["#ASSAULTCARBINE_DESC"] = "La carabina de asalto es un arma automática compacta alimentada por cargador, con una alta cadencia de fuego y una dispersión máxima comparativamente baja.\n\nCamarada en 5mm, esta arma fue diseñada como una solución ligera y portátil para la infantería blindada.\n\nSin embargo, el tamaño comparativamente pequeño del proyectil la hace inadecuada para cualquier otra cosa que no sea su propósito previsto."
lang["#MARKSMANCARBINE_DESC"] = "Un rifle semiautomático de gama alta de origen estadounidense.\n\nPrimo del Rifle de Servicio, la Carabina de Tirador es una versión mejorada que utiliza solo los mejores componentes disponibles.\n\n¡Mayor cadencia de disparo, más duradera y más ligera!"
lang["#PATRIOT_DESC"] = "Una carabina de 5mm corta y ligera de cañón recortado, sin culata ni alza. El acero está oxidado y el armazón muestra el desgaste honesto de años en manos firmes, marcado pero no disminuido.\n\nPortada por innumerables soldados, lleva las marcas silenciosas de puestos de guardia y largos caminos, de servicio en defensa del hogar y del derecho a mantenerse libre.\n\nSe ha mantenido en defensa de hogares, de hermanos y hermanas de armas, del simple derecho a mantenerse libre. Grabado a lo largo de su costado, suavizado por la edad pero nunca borrado, están las palabras Sic Transit Gloria. Un recordatorio de que la gloria puede desvanecerse pero el servicio, el sacrificio y el espíritu de quienes la portan perduran."
lang["#ANTIMAT_DESC"] = "El PGM Hecate II es un arma antimateria extremadamente potente diseñada para ser utilizada contra equipos militares fuertemente blindados.\n\nUno solo podría imaginar lo que podría hacerle a un Sanguinario."
lang["#BLACKARROW_DESC"] = "Un rifle bullpup prototipo 12.7. El papel original de este rifle era actuar como una alternativa compacta y ligera a los rifles antimateria anteriores.\n\nNo es nativo de los Estados Unidos, este diseño nació en la Unión Soviética. Adecuado para distancias más cercanas que los diseños más contemporáneos."
lang["#COWBOYREPEATER_DESC"] = "Una reproducción de antes de la guerra de un diseño ahora antiguo, el Repetidor de Vaquero.\n\nEs bueno que sea así, la munición del siglo XIX es difícil de conseguir."
lang["#COWBOYREPEATER_STARTER_DESC"] = "Un antiguo Repetidor de Vaquero, solo recamarado para .38 Especial. Sigue siendo bastante potente, pero podría usar una limpieza."
lang["#TRAILCARBINE_DESC"] = "Una reproducción de antes de la guerra de un diseño ahora antiguo, recamarada para munición moderna.\n\nEs bueno que sea así, la munición del siglo XIX es difícil de conseguir."
lang["#DKS_DESC"] = "Un rifle de francotirador DKS-501, excelente para el combate a larga distancia.\n\nRecamarado para .308.\n\nVisto principalmente como un arma militar contratada; tuvo un uso limitado en el mercado comercial como un rifle de caza de gama alta, pero notoriamente frágil."
lang["#FAMAS_DESC"] = "Un rifle de servicio Bullpup fabricado en Francia.\n\nRecamarado para 5.56, este rifle poco común es más fácil de alimentar que de encontrar. Uno se pregunta cómo llegó a suelo estadounidense."
lang["#LIBERTY_DESC"] = "Un símbolo de libertad y resistencia.\n\nUna variante muy personalizada del rifle de batalla re-camarada en 5.56, este rifle es popular entre rebeldes y luchadores por la libertad.\n\n'Sic semper tyrannis.'"
lang["#FAL_DESC"] = "Un rifle de batalla producido por el fabricante de armas belga Fabrique Nationale de Herstal.\n\nEste rifle ha sido más utilizado por las fuerzas armadas que cualquier otro rifle en la historia."
lang["#FNC_DESC"] = "Una variante del rifle de batalla producido por el fabricante de armas belga Fabrique Nationale de Herstal.\n\nEste es una variante recamarada en 5.56, mejorada internamente, totalmente automática y ligeramente más moderna del Rifle de Batalla."
lang["#HUNTING_DESC"] = "Un arma envejecida pero fiable.\n\nEste rifle ha visto días mejores, pero sigue siendo eficaz para el combate a larga distancia.\n\nRecamarado en .308."
lang["#LEVERGUN_DESC"] = "Un rifle de palanca de gran calibre recamarado en .45-70 Govt.\n\nLos rifles de monte son conocidos por su facilidad de uso en matorrales densos o espacios reducidos, donde un rifle de precisión de largo alcance sería difícil de manejar o poco práctico."
lang["#PARTIZAN_DESC"] = "Esta arma es la libertad,\n\nten por seguro que el día en que ya no la tengas, serás devuelto a la esclavitud."
lang["#R91_DESC"] = "Un rifle de asalto urbano R91 totalmente automático, emitido a las Fuerzas Armadas de EE. UU. durante operaciones de pacificación urbana y combate.\n\nLa serie R de rifles se utilizó tras la interrupción de la serie M a principios del siglo XXI.\n\nProducido por el fabricante civil Stent Security Solutions, se fabricaron en muchos modelos y variaciones."
lang["#SERVICERIFLE_DESC"] = "Un rifle semiautomático de origen estadounidense.\n\nIngeniería inversa a partir de esquemas de antes de la guerra, este diseño ha disfrutado de un nuevo aumento de popularidad por su facilidad de fabricación y respetable potencia de fuego.\n\nEste ejemplar es una imitación de después de la guerra, ya que los originales habían sido eliminados gradualmente en favor de la serie R cuando cayeron las bombas."
lang["#AK_DESC"] = "Originaria de la Rusia soviética a finales de la Segunda Guerra Mundial, este diseño se ha utilizado desde entonces en conflictos de todo el mundo.\n\nNo es sorprendente que tantos años después de la caída de las bombas estos robustos rifles permanezcan, de una forma u otra."
lang["#TYPE93_DESC"] = "Un diseño utilizado en masa durante las Guerras de Recursos por los infiltrados y simpatizantes chinos.\n\nMiles de estas armas fueron introducidas de contrabando en los EE. UU., y muchas siguen funcionando 150 años después de la Gran Guerra."
lang["#PIPERIFLE_DESC"] = "Un arma tosca, pero efectiva. Fabricada con chatarra sobrante y tuberías de antes de la guerra, es barata y fácil de producir.\n\nJunto con su recámara de 9mm, esto la hace ampliamente utilizada tanto por saqueadores como por solitarios."
lang["#PIPERIFLE_STARTER_PISTOL_DESC"] = "Un arma funcional, hecha con restos. Nada realmente especial, aparte de que dispara balas malas."
lang["#PIPERIFLE_STARTER_RIFLE_DESC"] = "Un arma funcional, hecha con restos. Una base más fuerte con una culata de mierda atornillada, dispara bastante lento."
lang["#PIPERIFLE_STARTER_SMG_DESC"] = "Un arma funcional, hecha con restos. Esta tiene un ajuste automático integrado, por lo que puede disparar en modo totalmente automático. Muy débil en cuanto a daño."
lang["#PIPERIFLEBOLT_DESC"] = "Un arma simple, pero efectiva. Fabricada con chatarra sobrante y tuberías de antes de la guerra, es potente y fácil de producir.\n\nDada la alta presión de su recámara .308, se eligió un cargador interno superior y un mecanismo de cerrojo para evitar que explote en tus manos."
lang["#VARMINT_DESC"] = "Un rifle de antes de la guerra que se usaba típicamente para cazar animales pequeños.\n\nMenos potente que su primo .308, pero mucho más común, al igual que su munición.\n\nRecamarado en 5.56."
lang["#VARMINT_STARTER_DESC"] = "Un rifle de alimañas terriblemente maltratado recamarado en 5.56.\n\nEsta arma sufrió su parte de abusos mucho antes de que cayeran las bombas, y los años siguientes no han sido más amables."
lang["#MACHINEGUN_DESC"] = "Una ametralladora de apoyo totalmente automática.\n\nRecamarada en 5.56 y con un cargador de 90 rondas por defecto, esta es una de las armas cortas de antes de la guerra más intimidantes que aún sobreviven hoy en día.\n\nDesafortunadamente, necesitarás la fuerza y los recursos combinados de un ejército para transportarla y alimentarla."
lang["#HMACHINEGUN_DESC"] ="La Ametralladora Ligera T24 es un prototipo recuperado de antes de la guerra basado en la MG 42 alemana, desarrollado originalmente para reemplazar la BAR y la M1919A4.\n\nAunque el proyecto fracasó antes de la Gran Guerra, la Compañía Phoenix lo revivió más tarde utilizando piezas y planos saqueados, creando variantes robustas apreciadas por su feroz cadencia de fuego y fiabilidad en el yermo."
lang["#BAR_DESC"] = "Este rifle automático enfriado por aire, recamarado para balas calibre .30-06, es uno de los tipos de armamento más raros en los Estados Unidos de antes de la guerra.\n\nEl rifle automático fue utilizado extensamente por las fuerzas estadounidenses en la Primera Guerra Mundial, la Segunda Guerra Mundial y la Guerra de Corea."
lang["#G11_DESC"] = "El HK G11 K2 es uno de los rifles de asalto más avanzados creados.\n\nEs capaz de disparar ráfagas de 4.7mm que salen del arma antes de que se pueda sentir el retroceso.\n\nDebido a su compleja construcción y materiales raros, así como a la munición especializada difícil de conseguir, este rifle es extremadamente raro."
lang["#RANCOR_DESC"] = "Esta arma nació de la necesidad de protección contra un yermo en evolución e implacable.\n\nConstruida con algunos de los materiales más caros que los Rangers del Desierto pudieron encontrar, el Repetidor Rencor es capaz de disparar 14mm: un cartucho de pistola monstruosamente grande diseñado para derribar enemigos monstruosamente grandes."
lang["#BOZAR_DESC"] = "El refinamiento definitivo del arte del francotirador. Aunque algo quisquilloso y propenso a atascarse si no se mantiene escrupulosamente limpio, la precisión de esta gran arma compensa con creces sus requisitos de mantenimiento adicionales."
lang["#M1GARAND_DESC"] = "Antes de los rifles de plasma y las armas láser, el M1 Garand era la vanguardia del poder de fuego estadounidense. Esta leyenda semiautomática se ganó su lugar en la historia a través de décadas de servicio militar y ahora ha encontrado una segunda vida en tus manos.\n\nDisparando .30-06 desde un clip de 8 balas en bloque con ese inconfundible 'ping', es un símbolo de una era pasada donde la artesanía se enfrentaba al poder de fuego. Robusto, fiable y aún mortal."
lang["#M1903_DESC"] = "Forjada en los fuegos de dos Guerras Mundiales y resucitada para los yermos, la M1903 Springfield es el sueño de un tirador de cerrojo, mortalmente precisa y devastadora a distancia.\n\nEsta belleza antigua se ganó sus galones en las trincheras de Europa y las islas del Pacífico. Recamarada en .30-06, la Springfield no rocía, habla, y cuando lo hace, las cabezas explotan como melones."

lang["#RATSLAYER_DESC"] = "Desarrollado por un granjero cansado de las Ratas Topo, este es el pináculo de la tecnología del Rifle de Alimañas.\n\nContinúa su legado. Haz que esas malditas ratas se extingan."
lang["#SVD_DESC"] = "Un rifle largo. Similar al Rifle Soviético, pero es capaz de disparar balas .308, lo que lo convierte en un gran francotirador para usar."
lang["#RHODIESPECIAL_DESC"] = "'Pugnamus Amo Leo'"
lang["#R91INFILTRATOR_DESC"] = "Rifle de asalto urbano R91, Variante de Infiltración.\n\nDiseñado para ser utilizado por grupos de operaciones especiales, se ha eliminado la culata, acortado el cañón y se han añadido un silenciador, una mira y un cargador extendido."
lang["#R91PERFORATOR_DESC"] = "Rifle de asalto urbano R91, Variante de Perforador.\n\n'Esta es la mejor arma que he tenido. Un poco más lenta en el gatillo, pero lo compensa con potencia y precisión.\n\nÚsala con buena salud.'"
lang["#R91WANDA_DESC"] = "Un rifle de asalto urbano R91 de rafagas.\n\n'Mira, obviamente no sabes nada sobre trabajo de inteligencia, señora.\n\nEs una técnica X-K-Red-27.'"
lang["#R91TELAVIV_DESC"] = "Un rifle de combate extranjero.\n\nRecamarado en .308, este patrón de rifle fue la base de diseño para el R91 fabricado en Estados Unidos. El selector está atascado en modo automático. Este rifle en particular fue rescatado de las ruinas irradiadas de Tel Aviv después de su destrucción en 2053.\n\n'Ki b'Tahbulot, Ta'ase-l'kha milhama.'"
lang["#SRIFLE12.7_DESC"] = "Una carabina de gran calibre semiautomática de origen estadounidense.\n\nIngeniería inversa a partir de esquemas de antes de la guerra, esta conversión de calibre fue diseñada originalmente para inutilizar vehículos enemigos.\n\nDespués de la guerra, se ha descubierto que funciona en todo lo demás, siempre que puedas permitírtelo."
lang["#SRIFLECOMRADE_DESC"] = "'Ese rifle que cuelga en la pared del piso de la clase trabajadora o de la cabaña del trabajador es el símbolo de la democracia.\n\nEs nuestro trabajo asegurarnos de que permanezca allí.'"
lang["#SRIFLEPARTIZAN_DESC"] = "'Esta arma es la libertad,\n\nten por seguro que el día en que ya no la tengas, serás devuelto a la esclavitud.'"
lang["#SRIFLEM199_DESC"] = "Quizás el arma más reconocida en el arsenal militar moderno de EE. UU., el M199 ganó su apodo 'El Contestador' por el inusual informe que hace el mecanismo de disparo al expulsar una vaina vacía.\n\nDisparando balas estándar de 5.56mm, el M199 fue el arma de infantería oficial del Ejército de los EE. UU. antes de ser discontinuado en favor de la serie R a principios del siglo XXI."
lang["#SRIFLEROBERTS_DESC"] = "Un rifle de servicio muy querido.\n\nSe dice que este rifle en particular perteneció al Coronel Roberts, primer Jefe de Artillería del Ejército de la Nueva República de California.\n\n'¡Por la República!'"
lang["#HRIFLE_WHITEDEATH_DESC"] = "Un arma envejecida pero fiable.\n\nImportado barato en masa antes de la Gran Guerra, este rifle fue fabricado en algún lugar de Europa del Este.\n\nRecamarado en 7.62x39."
lang["#TYPE93BD_DESC"] = "El antiguo emperador chino Huizong de Song canonizó cinco dragones de colores como 'reyes'.\n\nXuanlong es el dragón negro, que habita en las profundidades de las aguas místicas."

--escopeta
lang["#COMBATSHOTGUN_DESC"] = "La Winchester City-Killer es una escopeta Bullpup automática.\n\nRestringida a las fuerzas del orden y militares, esta arma vio la mayor parte de su acción en el control de disturbios."
lang["#SINGLEBARREL_DESC"] = "Una escopeta de un solo disparo de cañón abatible.\n\nSimple, fiable, barata. Estas cualidades hicieron que las escopetas de un solo cañón se produjeran en cantidades increíbles antes de que cayeran las bombas.\n\nCapaz de disparar cartuchos de escopeta Calibre 12, de los cuales existen varios tipos."
lang["#DOUBLEBARREL_DESC"] = "Una escopeta de cañones yuxtapuestos. Popular en la caza y en los deportes de tiro de antes de la guerra.\n\nCapaz de disparar cartuchos de escopeta Calibre 12, de los cuales existen varios tipos."
lang["#TOZ34_DESC"] = "Una escopeta de cañones superpuestos. Popular en la caza y en los deportes de tiro de antes de la guerra.\n\nCapaz de disparar cartuchos de escopeta Calibre 12, de los cuales existen varios tipos."
lang["#870_DESC"] = "Una escopeta de bombeo. Popular en la caza y en la protección del hogar de antes de la guerra.\n\nCapaz de disparar cartuchos de escopeta Calibre 12, de los cuales existen varios tipos."
lang["#870ECHO_DESC"] = "Una escopeta de trinchera M-12 marcada por la batalla y muy modificada, equipada con una bayoneta de 17 pulgadas. Su superficie está grabada con marcas y sellos de cera, cada uno contando una historia de dificultades.\n\nAl tomarla, una pesada sensación presiona tus hombros acompañada de un impulso implacable para avanzar hacia una meta invisible. Grabado entre las marcas están las palabras: 'La luz de la mente por sí sola no puede quemar toda la oscuridad'."
lang["#STREETSWEEPER_DESC"] = "Una escopeta semiautomática con un cargador de tambor.\n\nCapaz de disparar cartuchos de escopeta Calibre 12, de los cuales existen varios tipos.\n\nVista con poca frecuencia en manos de unidades militares y departamentos de policía de antes de la guerra, este modelo ha encontrado una popularidad renovada después de la guerra por parte de casi cualquier persona que pueda echarle mano."
lang["#SPAS12_DESC"] = "Una escopeta semiautomática con un cargador de tubo.\n\nCapaz de disparar cartuchos de escopeta Calibre 12, de los cuales existen varios tipos.\n\nUn modelo importado de gama alta popular entre los departamentos de policía y los entusiastas de las armas de fuego por igual, su alta cadencia de fuego es excelente para lidiar con múltiples objetivos."
lang["#SALVATION_DESC"] = "Esta escopeta bien hecha y fiable se caracteriza principalmente por su alta cadencia de fuego, una mejora notable sobre otros modelos de Escopeta Policial.\n\nPor desgracia, tiene un riel superior/ inferior destrozado. Será difícil apuntar con estas miras."
lang["#RIOTSHOTGUN_DESC"] = "Una terrorífica escopeta semiautomática alimentada por tambor, vista siendo usada por el Control de Disturbios de la RNC.\n\nNo muy desplazada de su uso original de antes de la guerra, la Escopeta Antidisturbios es el arma perfecta para deshacerse de grandes multitudes de civiles protestantes o, en cambio, de saqueadores homicidas."

lang["#GRIMSREAVER_DESC"] = "Segador Sombrío."
lang["#ULTIMATUM_DESC"] = "Ultimátum."
lang["#FUDD_DESC"] = "Un regalo de mayoría de edad de un padre, destinado a su ahora fallecido hijo, llevado antes de tiempo.\n\n\n\nEs temporada de Cuervos."
lang["#COACHGUN_DESC"] = "Una escopeta de dos cañones especialmente modificada por la Tribu 80s.\n\nLas escopetas de diligencia presentan una culata de longitud completa pero un cañón recortado. Esta escopeta en particular dispara ambos cañones a la vez; una desagradable sorpresa para objetivos sin armadura.\n\nIncapaz de disparar postas.\n\n''Dispárala a las piernas desarmadas de un soldado y míralas convertirse en gelatina.'' -Gridlock"


--pistola
lang["#USP_DESC"] = "Un H&K USP, fabricado en un país extranjero.\n\nUna vez comercializado para uso internacional de las fuerzas del orden y militares, esta pistola nunca fue adoptada en los EE. UU.\n\nAquejada por la competencia de fabricantes nacionales, los altos costos de importación y un error particularmente embarazoso en un cartel promocional generalizado, estas pistolas son una rareza oscura en el Yermo."
lang["#MAUSER_DESC"] = "Una pistola Shanxi Tipo 17.\n\nProducida en masa por el Arsenal de Taiyuan para el ejército de Yan Xishan, esta pistola es ahora una reliquia de la Guerra Sino-Americana."
lang["#10MMPISTOL_DESC"] = "Favorecida por su calidad y su fabricación simple, esta arma fue ampliamente utilizada por las fuerzas del orden en el viejo mundo.\n\nDebido a su fiabilidad en condiciones similares al desierto, la Colt 6520 todavía se usa ampliamente hoy en día."
lang["#10MMREVOLVER_DESC"] = "Este revólver está recamarado en 10mm y es una opción fiable para las fuerzas del orden.\n\nEs fiable, claro, pero aún así se quedó atrás de la Pistola 10mm bastante rápido."
lang["#14.5MMPISTOL_DESC"] = "Una pistola semiautomática Sig-Sauer 14mm. Pistola grande de un solo disparo. Artesanía casi perfecta."
lang["#12.7MMPISTOL_DESC"] = "Una pistola semiautomática Sig-Sauer 12.7mm.\n\nPistola semiautomática grande con cañón fijo, un ejemplo de excelente artesanía.\n\nImportada a los EE. UU. desde Europa, este diseño fue recamarado originalmente en 14mm."
lang["#MARKSMANPISTOL_DESC"] = "Una pistola de cañón abatible Comanche recamarada para .45-70 govt. Solo puede contener una bala, esperemos que mate a quien apunta."
lang["#357MAGNUM_DESC"] = "Un revólver de acción simple recamarado para balas .357 Magnum y .38 special.\n\nSu cadencia de fuego comparativamente lenta y su baja capacidad se compensan con su potente cartucho y su acción fiable.\n\nEl cilindro se abre para expulsar rápidamente las balas gastadas y recargar."
lang["#357MAGNUM_STARTER_DESC"] = "Un viejo magnum. Todavía puede cargar y disparar .357, pero no tan bien como probablemente podría haberlo hecho entonces."
lang["#44MAGNUM_DESC"] = "Una de las pistolas de mayor calibre del mundo, esta arma puede atravesar casi todas las armaduras blandas.\n\nLa munición es difícil de encontrar y puede ser muy costosa."
lang["#DEAGLE357_DESC"] = "Una pistola semiautomática poderosa y equilibrada recamarada en .357 Magnum."
lang["#DEAGLE_DESC"] = "Una pistola semiautomática potente recamarada en .44 Magnum."
lang["#WASTELANDHAWK_DESC"] = "Nombrada 'Halcón del Yermo' como un juego de palabras con 'Águila del Desierto', esta pistola se ha ganado la reputación de ser la mejor pistola que un Cazarrecompensas puede comprar.\n\nAhora que está en tus manos, es hora de caer sobre tu presa como una especie de..."
lang["#HUNTINGREVOLVER_DESC"] = "Una pistola monstruosamente grande recamarada para la bala 45-70 Govt.\n\nUsada exclusivamente en la caza mayor, esta pistola es castigadora de disparar, pero podría salvar tu vida."
lang["#SEQUOIA_DESC"] = "Un Revólver de Caza visto siendo usado por Rangers Veteranos, esta arma ha sido denominada la 'Secuoya del Ranger' por su distintiva imagen de fuerza y resistencia que evocan tanto los rangers como el arma."
lang["#NEEDLER_DESC"] = "Una pistola capaz de disparar agujas llenas de diversas sustancias.\n\nLa munición se puede hacer a mano y llenar con todo tipo de sustancias."
lang["#M9FS_DESC"] = "Una de las pistolas 9mm más comunes, la Beretta es popular debido a su fiabilidad, cargador de 17 balas y buen aspecto."
lang["#M9FS_STARTER_DESC"] = "Una vieja pistola 9mm que se te dio antes de que te aventuraras por tu cuenta. Hay muchas como ella, pero esta es tuya."
lang["#1911PISTOL_DESC"] = "La clásica Colt M1911 A1.\n\nSi bien el cañón fijo y las tolerancias estrictas de esta pistola la convierten en un arma de fuego extremadamente precisa, tiene el costo de una mayor frecuencia de atascos.\n\nPor esta razón y la capacidad comparativamente limitada, este diseño fue eliminado gradualmente del servicio estadounidense algún tiempo después de la Segunda Guerra Mundial."
lang["#1911CAV_DESC"] = "Una versión mejorada de la clásica Colt M1911A1.\n\nSi bien el cañón fijo y las tolerancias estrictas de esta pistola la convierten en un arma de fuego extremadamente precisa, este recamarado y configuración reducen las posibilidades de atasco de la versión estándar.\n\nAdoptada por las Unidades de Caballería Blindada de los EE. UU., esta arma de fuego bastante pesada reduce el retroceso y la elevación, y presenta varias mejoras, incluido un cañón de precisión y miras nocturnas, pero fue eliminada del servicio estadounidense justo después de la M1911A1 en favor de opciones de armas secundarias más nuevas."
lang["#DETECTIVEPISTOL_DESC"] = "Noches largas.\nCasos difíciles.\nRamen rancio de un Protectron.\nEstas son las señas de identidad de un buen Detective.\n\nY el amigo de este detective está listo para ayudarte a acabar con cualquier monstruo rebelde de RobCo."
lang["#GALVANICTHUNDER_DESC"] = "Ja ja ja, no des."

lang["#THATGUN_DESC"] = "¿Esta pistola?\n\nNo. Esa Pistola. Esa Pistola es la única que necesitarás."
lang["#1911DELTA_DESC"] = "Variante de Catálogo 5 - Martillo con espuela y cachas de madera.\n\n''Una verdadera pieza de colección.''"
lang["#93R_DESC"] = "Pistola ametralladora de ráfaga.\n\n''Muerto o vivo, vienes conmigo.''"
lang["#ELDERSJUDGEMENT_DESC"] = "¿Ves el destino inmutable?\n\n¿El destino o la dedicación te mantienen arrodillado y obediente?\n\n¿Finges la predestinación?\n\n¿O es el fanatismo la verdad de todo?"
lang["#357POLICE_DESC"] = "Un revólver de acción doble recamarado para balas .357 Magnum y .38 special.\n\nPermite disparar sin tener que amartillar el martillo antes de cada disparo.\n\nEl cilindro se abre para expulsar rápidamente las balas gastadas y recargar."
lang["#10MMVOLLEY_DESC"] = "Una pistola 10mm modificada por la Tribu 80s.\n\nModificada para vaciar todo su cargador con un solo tirón del gatillo. Da una patada como una maldita mula y no puede aceptar cargadores extendidos, pero dispara muy rápido.\n\n''Ataca rápido, ataca fuerte. -Entrepierna de Fuego''"
--subfusil
lang["#9MMSMG_DESC"] = "Un subfusil de cerrojo abierto recamarado en 9mm. Tiene una buena capacidad de cargador y cadencia de fuego, pero el cañón corto está terriblemente desgastado, limitando los combates a corta distancia."
lang["#10MMSMG_DESC"] = "Un subfusil de gama alta recamarado en 10mm.\n\nSi bien el mecanismo de disparo de rodillo asegurado resulta en un retroceso increíblemente bajo, su alcance efectivo es limitado en modo totalmente automático.\n\nFácil de controlar y de destrozar enemigos sin armadura, esta arma es vital entre los mercenarios independientes."
lang["#P90_DESC"] = "Un arma de defensa personal recamarada en 4.7mm.\n\nEsta arma tiene un cargador extremadamente generoso de 50 balas. Junto con una alta cadencia de fuego.\n\nLos cartuchos no son comunes y deben comprarse más a menudo que encontrarse."
lang["#TOMMYGUN_DESC"] = "El Subfusil .45 Auto es un arma relativamente robusta que ofrece una gran potencia de fuego. Desafortunadamente, el resultado es que esta arma requiere dos manos para operar.\n\nAdemás, el fuerte retroceso significa que este subfusil no puede ser utilizado por personas frágiles y la precisión se verá afectada en enfrentamientos a larga distancia."
lang["#44TOMMY_DESC"] = "''El día de San Valentín siempre ha sido una tradición de amor, que se remonta a la época de los malditos romanos.\n\nEntonces, Al Capone descubrió un mejor uso para el día.\n\nAdiós, mi amor.''"
lang["#P90C_DESC"] = "Un arma de defensa personal 10mm, también conocida como H&K P90c.\n\nLos entusiastas de las armas de fuego de antes de la guerra encontrarían extraño que el logotipo de Heckler & Koch esté en una P90, pero eso ya no es relevante para ellos.\n\nA pesar de haber sido producida en secreto con diseños robados, no es una mala copia."
lang["#ASVAL_DESC"] = "Una reliquia de la ingeniería soviética, el AS-Val es un rifle de asalto totalmente automático con silenciador integral recamarado en cartuchos subsónicos 9x39mm.\n\nOriginalmente construido para operaciones encubiertas tras las líneas enemigas, sus balas perforantes y su perfil silencioso como un susurro lo convierten en un favorito entre los aspirantes a asesinos del yermo."
lang["#VSK_DESC"] = "Un rifle de tirador recamarado en el exótico cartucho 9x39.\n\nDiseñado como compañero de otras armas de su procedencia, tiene silenciador integral y es más adecuado para combates de corto a medio alcance."
lang["#12.7MMSMG_DESC"] = "Subfusil 12.7mm"

lang["#GREASEGUN_DESC"] = "''Nunca me gustaste, Joker.\nNunca pensé que fueras gracios--''\n\n\nBANG"
--pesada
lang["#MINIGUN_DESC"] = "Una Minigun Personal Rockwell CZ53. Cuando llegó la Gran Guerra, ya era un diseño anticuado y estaba siendo reemplazada lentamente por la minigun Avenger CZ57 más avanzada."
lang["#AVENGER_DESC"] = "Rockwell diseñó el Avenger como reemplazo de su anticuada Minigun Personal CZ53. Las mejoras de diseño del Avenger incluyen un enfriamiento mejorado con gel y orificios de cañón cromados. Esto le da un mayor alcance y letalidad."
lang["#VINDICATOR_DESC"] = "La empresa alemana Rheinmetall AG creó la minigun definitiva.\n\nLa Vindicador lanza 4.7mm a través de sus seis cañones de carbono-polímero.\n\nComo la cima de la habilidad de ingeniería teutónica, es el arma de mano definitiva."
lang["#GAUSS_MINIGUN_DESC"] = "La minigun Gauss es un arma balística automática potente que dispara rápidamente cartuchos electromagnéticos de 2mm. Si bien acelera los proyectiles a una velocidad más lenta en comparación con otras armas gauss, lo compensa con la gran cantidad de proyectiles que golpean al pobre desgraciado en la mira de este monstruo."

--otras
lang["#SYRINGER_DESC"] = "Un arma improvisada, pero efectiva. Fabricada con chatarra sobrante y tuberías de antes de la guerra, fue diseñada a imagen de las 'pistolas tranquilizantes' de antes de la guerra.\n\nSe puede usar de forma ofensiva o como arma de apoyo, dependiendo del tipo de dardos elegidos por el usuario."
lang["#FARTNADE_DESC"] = "La Granada Gastrointestinal Táctica M-42 es una cápsula de mano diseñada para contener Megapedos, pequeñas ojivas apestosas.\nDevastadora contra todas las narices."
lang["#RAILRIFLE_DESC"] = "Una conversión neumática de alta potencia de una pistola de clavos industrial, ahora capaz de lanzar clavos a grandes distancias.\n\nAntes devastadora para las vías del tren, ahora devastadora para la RNC y cualquiera de sus 'aliados' que lleven Armadura Asistida."
lang["#RAILSHOTGUN_DESC"] = "Un cañón neumático diseñado para lanzar un puñado de clavos. El cañón sacrifica la precisión y penetración del Rifle de Ferrocarril por un solo golpe devastador."

--explosiva
lang["#APW_DESC"] = "El arma antipersonal de 25mm es un lanzagranadas semiautomático.\n\nDiseñado para darle a un soldado la capacidad de lanzar granadas montadas en vehículos en un paquete más portátil."
lang["#M79_DESC"] = "Un lanzagranadas de mano de un solo disparo.\n\nLanza granadas de 40mm.\n\nDesarrollado a principios de la década de 1960, esta arma ha sido utilizada continuamente por las fuerzas estadounidenses durante más de un siglo debido a su diseño simple."
lang["#SKYBREAKER_DESC"] = "Un lanzagranadas de mano de dos disparos.\n\nLanza granadas de 40mm.\n\n#WIP_DESC"
lang["#FATMAN_DESC"] = "La Catapulta Nuclear Táctica M-42 es una ballesta de hombro diseñada para lanzar Mini Nukes, pequeñas ojivas atómicas.\nDevastadora contra todos los objetivos, si puedes encontrar algo de munición para ella."
lang["#MISSILELAUNCHER_DESC"] = "Un arma explosiva montada en el hombro.\n\nDispara un gran proyectil que explota al impactar."
lang["#REDGLARE_DESC"] = "Un arma explosiva montada en el hombro completamente automática.\n\nDispara un Cohete Rojo que explota al impactar.\n\nLos cohetes sacrifican el radio letal por más velocidad y tamaño del cargador.\n\n\"Y el Resplandor Rojo del Cohete... las bombas estallando en el aire...\"."
lang["#CHINALAKE_DESC"] = "Un lanzagranadas de bombeo.\n\nLanza granadas de 40mm.\n\nDiseñado para fuerzas especiales, el China Lake fue desarrollado como reemplazo del M79. Se sabe que los Rock-Biters encontraron un gran alijo de estos en Yolla Bolly.\n\nTres granadas en el tubo, tres veces el poder de fuego."

RELOADSCHEMA = true
