local lang = RSRG.Languages["es-es"]


-- █████╗ ███╗   ███╗███╗   ███╗ ██████╗
--██╔══██╗████╗ ████║████╗ ████║██╔═══██╗
--███████║██╔████╔██║██╔████╔██║██║   ██║
--██╔══██║██║╚██╔╝██║██║╚██╔╝██║██║   ██║
--██║  ██║██║ ╚═╝ ██║██║ ╚═╝ ██║╚██████╔╝
--╚═╝  ╚═╝╚═╝     ╚═╝╚═╝     ╚═╝ ╚═════╝

---ENERGÍA
lang["#SEC_NAME"] = "Celula de Energía"
lang["#MFC_NAME"] = "Célula de Microfusión"
lang["#MFC_OC_NAME"] = "Célula de Microfusión, SobreCargada"
lang["#MFC_MC_NAME"] = "Célula de Microfusión, Máxima Carga"
lang["#MFC_BULK_NAME"] = "Célula de Microfusión, A Granel"
lang["#MFC_ND_NAME"] = "Célula de Microfusión con Fugas"
lang["#ECP_NAME"] = "Carga de Electrones"
lang["#ECP_OC_NAME"] = "Carga de Electrones, SobreCargada"
lang["#ECP_MC_NAME"] = "Carga de Electrones, Máxima Carga"
lang["#ECP_BULK_NAME"] = "Carga de Electrones, A Granel"
lang["#PLASMACARTRIDGE_NAME"] = "Cartucho de Plasma"
lang["#ALIENPOWERCELL_NAME"] = "Celda de Energía Alienígena"
lang["#ALIENPOWERMODULE_NAME"] = "Módulo de Energía Alienígena"
---PISTOLA
lang["#9MM_NAME"] = "9mm"
lang["#9MM_AP_NAME"] = "9mm AP"
lang["#9MM_HP_NAME"] = "9mm HP"
lang["#9MM_+P_NAME"] = "9mm +P"
lang["#9MM_ND_NAME"] = "9mm Viejo"
lang["#10MM_NAME"] = "10mm"
lang["#10MM_AP_NAME"] = "10mm AP"
lang["#10MM_HP_NAME"] = "10mm HP"
lang["#10MM_+P_NAME"] = "10mm +P"
lang["#38_NAME"] = ".38 Especial"
lang["#38_ND_NAME"] = ".38 Especial Viejo"
lang["#357_NAME"] = ".357 Mag LRN"
lang["#357_HP_NAME"] = ".357 Mag JSP"
lang["#357_HC_NAME"] = ".357 Mag +P HCLFN"
lang["#357_ND_NAME"] = ".357 Mag Viejo"
lang["#44_NAME"] = ".44 Mag LRN"
lang["#44_SPL_NAME"] = ".44 Especial"
lang["#44_HP_NAME"] = ".44 Mag JSP"
lang["#44_HC_NAME"] = ".44 Mag +P HCLFN"
lang["#45ACP_NAME"] = ".45 Auto"
lang["#45ACP_HP_NAME"] = ".45 Auto HP"
lang["#45ACP_AP_NAME"] = ".45 Auto AP"
lang["#45ACP_+P_NAME"] = ".45 Auto +P"
lang["#14.5MM_NAME"] = "14mm LFN"
lang["#12.7MM_NAME"] = "12.7mm LFN"
lang["#12.7MM_AP_NAME"] = "12.7mm JHP"
lang["#12.7MM_HP_NAME"] = "12.7mm HP"
---RIFLE
lang["#22LR_NAME"] = ".22LR"
lang["#22LR_HP_NAME"] = ".22LR HP"
lang["#22LR_PLINK_NAME"] = ".22LR Granel"
lang["#2MM_NAME"] = "2mm EC"
lang["#4.7MM_NAME"] = "4.7mm"
lang["#5MM_NAME"] = "5mm"
lang["#5MM_AP_NAME"] = "5mm AP"
lang["#5MM_HP_NAME"] = "5mm HP"
lang["#5.56MM_NAME"] = "5.56mm"
lang["#5.56MM_AP_NAME"] = "5.56mm AP"
lang["#5.56MM_HP_NAME"] = "5.56mm HP"
lang["#5.56MM_MATCH_NAME"] = "5.56mm, Precisión"
lang["#223_NAME"] = ".223"
lang["#223_ND_NAME"] = ".223 Viejo"
lang["#7.62MM_NAME"] = "7.62x39"
lang["#7.62MM_AP_NAME"] = "7.62x39 AP"
lang["#7.62MM_MATCH_NAME"] = "7.62x39, Precisión"
lang["#308_NAME"] = ".308"
lang["#308_AP_NAME"] = ".308 AP"
lang["#308_HP_NAME"] = ".308 SP"
lang["#308_MATCH_NAME"] = ".308, Precisión"
lang["#3006_NAME"] = ".30-06"
lang["#3006_MATCH_NAME"] = ".30-06, Precisión"
lang["#3006_AP_NAME"] = ".30-06 AP"
lang["#9X39MM_NAME"] = "9x39mm"
lang["#9X39MM_AP_NAME"] = "9x39mm AP"
lang["#4570_NAME"] = ".45-70 GOVT"
lang["#4570_HP_NAME"] = ".45-70 HP"
lang["#4570_HC_NAME"] = ".45-70 +P HCLFN"
lang["#50BMG_NAME"] = ".50 BMG"
lang["#50BMG_MATCH_NAME"] = ".50 BMG, Súper Precisión"
--CARTUCHOS DE ESCOPETA
lang["#12G_NAME"] = "12GA 00 Perdigón"
lang["#12G_SLUG_NAME"] = "12GA Posta"
lang["#12G_PSLUG_NAME"] = "12GA Posta de Pulso"
lang["#12G3_NAME"] = "12GA 00 Perdigón 3'' Magnum"
lang["#12G3_SLUG_NAME"] = "12GA Posta 3'' Magnum"
lang["#12G_FLECHETTE_NAME"] = "12GA Flechete"
lang["#12G_DRAGONS_BREATH_NAME"] = "12GA Aliento de Dragón"
lang["#20G_NAME"] = "20GA Perdigón"
lang["#20G_SLUG_NAME"] = "20GA Posta"
---MUNICIÓN PESADA
lang["#ROCKET_NAME"] = "Cohete"
lang["#ROCKET_CANISTER_NAME"] = "Bote de Cohetes"
lang["#MISSILEHE_NAME"] = "Misil HE"
lang["#MININUKE_NAME"] = "Mini Nuke"
lang["#25MM_NAME"] = "Granada de 25mm"
lang["#40MM_NAME"] = "Granada de 40mm"
lang["#FUELGAS_NAME"] = "Combustible de Lanzallamas"
lang["#FUELNAPALM_NAME"] = "Combustible de Lanzallamas, Optimizado"
lang["#FUELHOMEMADE_NAME"] = "Combustible de Lanzallamas Improvisado"

---OTROS
lang["#DART_NAME"] = "Dardo"
lang["#DART_STIM_NAME"] = "Dardo, Stimpak"
lang["#DART_RADSCOPRION_NAME"] = "Dardo, Mutascorpius"
lang["#DART_CONCENTRATEDRADSCOPRION_NAME"] = "Dardo, Mutascorpius Concentrado"
lang["#DART_GREENGECKO_NAME"] = "Dardo, Gecko Verde"
lang["#DART_CONCENTRATEDGREENGECKO_NAME"] = "Dardo, Gecko Verde Concentrado"
lang["#DART_FATIGUE_NAME"] = "Dardo, Fatiga"
lang["#DART_BLIGHT_NAME"] = "Dardo, Tizón"
lang["#DART_FEVCURLING11_NAME"] = "Dardo, FEV Curling-11"
lang["#DART_CONCENTRATEDBLIGHT_NAME"] = "Dardo, Tizón Concentrado"
lang["#DART_RAD_NAME"] = "Dardo, Radiactivo"
lang["#DART_SBLOCK_NAME"] = "Dardo, Bloqueador de Stims"
lang["#DART_CBLOCK_NAME"] = "Dardo, Bloqueador de Chems"
lang["#DART_PSYCHO_NAME"] = "Dardo, Psycho"
lang["#DART_BUFFOUT_NAME"] = "Dardo, Buffout"
lang["#DART_SLOTH_NAME"] = "Dardo, Pereza"
lang["#DART_HYDRA_NAME"] = "Dardo, Hydra"
-- lang["#DART_GOBLIN_NAME"] = "Dardo, Goblin" -- Esta mierda es muy tonta. La odio.
lang["#RAILSPIKE_NAME"] = "Clavo de Ferrocarril"
lang["#RAILSPIKE_SPIKY_NAME"] = "Clavo de Ferrocarril Puntiagudo"
lang["#RAILSTAKE_NAME"] = "Estaca de Ferrocarril"

------------------------------------------------------------------
---Descripciones de Munición
------------------------------------------------------------------
--ENERGÍA
lang["#SEC_DESC"] = "La Celula de Energía es una batería de alta capacidad que contiene una cantidad considerable de energía para su tamaño.\n\nDebido a que no produce energía como la célula de microfusión, es más adecuada para aplicaciones que requieren menos, como las pistolas de energía."
lang["#SEC_OC_DESC"] = "La variante SobreCargada de una celula de energía.\n\nUtiliza un método no estándar para contener la energía, lo que hace que la batería sea más inestable, pero proporciona una mayor producción de energía, lo que resulta en un mayor daño a costa del estado del arma."
lang["#MFC_DESC"] = "Una fuente de energía de grado militar, que se encuentra comúnmente en el uso de armas de disparo lento.\n\nLa Célula de Microfusión es una pequeña planta de fusión autónoma, capaz de generar y contener una enorme cantidad de energía.\n\nSi bien tenía muchas aplicaciones en el viejo mundo, hoy en día se usa principalmente para alimentar varios rifles de energía."
lang["#MFC_OC_DESC"] = "Una fuente de energía de grado militar, que se encuentra comúnmente en el uso de armas de disparo lento.\n\nVariante SobreCargada.\n\nAumenta la producción de daño y el efecto de penetración de armadura, a costa de una degradación más rápida del arma."
lang["#MFC_MC_DESC"] = "Una fuente de energía de grado militar, que se encuentra comúnmente en el uso de armas de disparo lento.\n\nVariante de Máxima Carga.\n\nAumenta en gran medida la producción de daño y el efecto de penetración de armadura, a costa de una fuerte degradación del arma."
lang["#MFC_BULK_DESC"] = "Una fuente de energía de grado militar, que se encuentra comúnmente en el uso de armas de disparo lento.\n\nVariante a Granel.\n\nReduce la degradación del arma, a costa de una menor producción de daño y sin penetración de armadura inherente."
lang["#MFC_ND_DESC"] = "Una Célula de Microfusión dañada, recuperada de la basura de otra persona.\n\n#STARTER_AMMO_DISCLAIMER"
lang["#ECP_DESC"] = "Una fuente de energía de grado militar, que se encuentra comúnmente en el uso de armas de disparo rápido.\n\nA diferencia de las celula de Energía, que no son capaces de una transferencia de energía lo suficientemente alta, y las Células de Microfusión, que son insuficientes para la descarga rápida, las Cargas de Electrones contienen tanto la carga como la potencia para alimentar las armas láser más intensas de antes de la guerra."
lang["#ECP_OC_DESC"] = "Una fuente de energía de grado militar, que se encuentra comúnmente en el uso de armas de disparo rápido.\n\nVariante SobreCargada.\n\nAumenta la producción de daño y el efecto de penetración de armadura, a costa de una degradación más rápida del arma."
lang["#ECP_MC_DESC"] = "Una fuente de energía de grado militar, que se encuentra comúnmente en el uso de armas de disparo rápido.\n\nVariante de Máxima Carga.\n\nAumenta en gran medida la producción de daño y el efecto de penetración de armadura, a costa de una fuerte degradación del arma."
lang["#ECP_BULK_DESC"] = "Una fuente de energía de grado militar, que se encuentra comúnmente en el uso de armas de disparo rápido.\n\nVariante a Granel.\n\nReduce la degradación del arma, a costa de una menor producción de daño y sin penetración de armadura inherente."
lang["#PLASMACARTRIDGE_DESC"] = "El Cartucho de Plasma es un pequeño contenedor verde y es utilizado por todo tipo de armas de plasma."
lang["#ALIENPOWERCELL_DESC"] = "Una inusual celda de energía de grado militar.\n\nContiene mucha más energía que cualquier cosa producida en la Tierra.\n\nUtilizada por el Alien Blaster."
lang["#ALIENPOWERMODULE_DESC"] = "Una inusual celda de energía de grado militar.\n\nContiene mucha más energía que cualquier cosa producida en la Tierra.\n\nUtilizada por el Atomizador Alienígena y el Desintegrador Alienígena."
--PISTOLA
lang["#9MM_DESC"] = "Un cartucho de pistola ligero, que se encuentra comúnmente en el uso de pistolas y subfusiles.\n\nAunque ha sido en gran medida retirado por las fuerzas del orden en favor del 10mm, este cartucho mantiene un seguimiento constante en varias partes del mundo debido a su bajo costo y controlabilidad."
lang["#9MM_AP_DESC"] = "Un cartucho de pistola ligero, que se encuentra comúnmente en el uso de pistolas y subfusiles.\n\nVariante Perforante\n\nUna bala de sobrepresión utilizada en subfusiles por el ejército, estas balas contienen un penetrador endurecido para usar contra objetivos blindados."
lang["#9MM_HP_DESC"] = "Un cartucho de pistola ligero, que se encuentra comúnmente en el uso de pistolas y subfusiles.\n\nVariante de Punta Hueca\n\nUna bala defensiva utilizada tanto por las fuerzas del orden como por los civiles, estas balas se expanden en objetivos blandos para una mayor letalidad, pero fallan contra la armadura."
lang["#9MM_+P_DESC"] = "Un cartucho de pistola ligero, que se encuentra comúnmente en el uso de pistolas y subfusiles.\n\nVariante de Sobrepresión\n\nMunición que ha sido cargada intencionalmente a una presión interna más alta. Esto asegura una mayor velocidad del proyectil y poder de parada, y proporciona una ligera capacidad de perforación de armadura, pero a costa de requerir más mantenimiento de lo habitual."
lang["#9MM_ND_DESC"] = "Un cartucho de pistola mal envejecido.\n\n#STARTER_AMMO_DISCLAIMER"
lang["#38_DESC"] = "Un cartucho de pistola ligero, que se encuentra comúnmente en el uso de revólveres de cañón corto.\n\nEsta bala se puede usar en la mayoría de las armas recamaradas para .357.\n\n.38 Especial y .357 son cartuchos de pared recta con pestaña, que comparten el mismo diámetro de bala. El primero, sin embargo, es mucho menos potente y causa menos desgaste a las armas de fuego."
lang["#38_ND_DESC"] = "Una bala .38 vieja. Todavía se podría disparar.\n\n#STARTER_AMMO_DISCLAIMER"
lang["#357_DESC"] = "Un cartucho de pistola mediano, popular para cazar animales pequeños. Se usa en revólveres y ciertos rifles.\n\nLas cargas de Punta Redonda de Plomo usan una bala de plomo simple, y son relativamente comunes y baratas."
lang["#357_HP_DESC"] = "Un cartucho de pistola mediano, popular para cazar animales pequeños. Se usa en revólveres y ciertos rifles.\n\nVariante de Caza\n\nDiseñado para animales pequeños a medianos, las puntas blandas se expanden al impactar, abatiendo a la presa de manera rápida y efectiva.\n\nLa eficacia se resiente contra la armadura."
lang["#357_HC_DESC"] = "Un cartucho de pistola pesado, popular para cazar animales grandes. Se usa en revólveres y ciertos rifles.\n\nVariante de Caza Mayor\n\nDiseñado para ser usado contra cosas más grandes, rápidas y mortales que tú, las balas de Punta Plana de Plomo Fundido usan un proyectil endurecido con la máxima carga posible para perforar la piel engrosada de los animales.\n\nEsta potente bala es difícil de encontrar y acorta drásticamente la vida útil del arma de fuego."
lang["#357_ND_DESC"] = "Todavía muy potente para su edad.\n\n#STARTER_AMMO_DISCLAIMER"
lang["#10MM_DESC"] = "Un cartucho común, que se encuentra en el uso de pistolas y subfusiles.\n\nAdoptado por numerosas agencias policiales, es el calibre estándar para el B.A.D.T.F.L."
lang["#10MM_AP_DESC"] = "Un cartucho común, que se encuentra en el uso de pistolas y subfusiles.\n\nVariante Perforante\n\nUna bala de alta presión utilizada en subfusiles por el ejército, estas balas contienen un penetrador endurecido para usar contra objetivos blindados."
lang["#10MM_HP_DESC"] = "Un cartucho común, que se encuentra en el uso de pistolas y subfusiles.\n\nVariante de Punta Hueca\n\nUna bala defensiva utilizada tanto por las fuerzas del orden como por los civiles, estas balas se expanden en objetivos blandos para una mayor letalidad, pero fallan contra la armadura."
lang["#10MM_+P_DESC"] = "Un cartucho común, que se encuentra en el uso de pistolas y subfusiles.\n\nVariante de Sobrepresión\n\nMunicioón que ha sido cargada intencionalmente a una presión interna más alta. Esto asegura una mayor velocidad del proyectil y poder de parada, y proporciona una ligera capacidad de perforación de armadura, pero a costa de requerir más mantenimiento de lo habitual."
lang["#44_DESC"] = "Un cartucho de pistola pesado, popular para cazar animales medianos a grandes. Se usa en varias armas secundarias y ciertos rifles.\n\nLas cargas de Punta Redonda de Plomo usan una bala de plomo simple, y son relativamente comunes y baratas."
lang["#44_SPL_DESC"] = "Un cartucho de pistola mediano, que se encuentra comúnmente en el uso de revólveres.\n\nEsta bala se puede usar en la mayoría de las armas recamaradas para .44.\n\n.44 Especial y .44 son cartuchos de pared recta con pestaña, que comparten el mismo diámetro de bala. El primero, sin embargo, es mucho menos potente y causa menos desgaste a las armas de fuego."
lang["#44_HP_DESC"] = "Un cartucho de pistola pesado, popular para cazar animales medianos a grandes. Se usa en revólveres y ciertos rifles.\n\nVariante de Caza\n\nDiseñado para animales pequeños a medianos, las puntas blandas se expanden al impactar, abatiendo a la presa de manera rápida y efectiva.\n\nLa eficacia se resiente contra la armadura."
lang["#44_HC_DESC"] = "Un cartucho de pistola pesado, popular para cazar animales medianos a grandes. Se usa en revólveres y ciertos rifles.\n\nVariante de Caza Mayor\n\nDiseñado para ser usado contra cosas más grandes, rápidas y mortales que tú, las balas de Punta Plana de Plomo Fundido usan un proyectil endurecido con la máxima carga posible para perforar la piel engrosada de los animales.\n\nEsta potente bala es difícil de encontrar y acorta drásticamente la vida útil del arma de fuego."
lang["#45ACP_DESC"] = "Un cartucho de pistola de gran calibre, que se encuentra en el uso de pistolas y subfusiles.\n\n¿Quieres causar más daño sin gastar tapas en Punta Hueca? La respuesta es simple: Haz un agujero más grande."
lang["#45ACP_HP_DESC"] = "Un cartucho de pistola de gran calibre, que se encuentra en el uso de pistolas y subfusiles.\n\nVariante de Punta Hueca\n\nUna bala defensiva utilizada tanto por las fuerzas del orden como por los civiles, estas balas se expanden en objetivos blandos para una mayor letalidad, pero fallan contra la armadura."
lang["#45ACP_+P_DESC"] = "Un cartucho de pistola de gran calibre, que se encuentra en el uso de pistolas y subfusiles.\n\nVariante de Sobrepresión\n\nMunicioón que ha sido cargada intencionalmente a una presión interna más alta. Esto asegura una mayor velocidad del proyectil y poder de parada, y proporciona una ligera capacidad de perforación de armadura, pero a costa de requerir más mantenimiento de lo habitual."
lang["#14.5MM_DESC"] = "Un cartucho de fabricación soviética comparable al .50 AE.\n\nCon un diámetro de bala de más de media pulgada, este cartucho es, con mucho, el más grande de pistola que se encuentra en el Yermo Fronterizo.\n\nDifícil de encontrar y muy buscado."
lang["#12.7MM_DESC"] = "Una bala de defensa cívica Hauer Premium es un cartucho de pistola grande comparable al .50 AE.\n\nCon un diámetro de bala de media pulgada, este cartucho es, con mucho, uno de los más grandes de pistola que se encuentra en el Yermo Fronterizo.\n\nDifícil de encontrar y muy buscado."
lang["#12.7MM_AP_DESC"] = "Una bala de defensa cívica Hauer Premium es un cartucho de pistola grande que atraviesa cualquier cosa que toca.\n\nVariante de Punta Hueca Enchaquetada\n\nEsta bala logra mantener en su mayoría el poder de fuego de una bala HP mientras permite una mayor penetración de la mayoría de las armaduras y pieles.\n\nEsta potente bala es difícil de encontrar y acorta drásticamente la vida útil del arma de fuego."
lang["#12.7MM_HP_DESC"] = "Una bala de defensa cívica Hauer Premium es un cartucho de pistola grande que atraviesa cualquier cosa que toca.\n\nVariante de Punta Hueca\n\nA diferencia de la mayoría de las cargas de este calibre, esta bala cuenta con una Punta Hueca, intercambiando penetración por un enorme canal de herida.\n\nDifícil de encontrar y muy buscado."
lang["#45ACP_AP_DESC"] = "Un cartucho de pistola de gran calibre, que se encuentra en el uso de pistolas y subfusiles.\n\nVariante Perforante\n\nUna baña especializada diseñada para perforar armadura y objetivos endurecidos. Estas balas sacrifican expansión en objetivos blandos a favor de mejor penetración."
--RIFLE
lang["#22LR_DESC"] = "El .22LR es un cartucho de rifle de muy baja potencia, que se encuentra comúnmente en el uso de rifles y pistolas.\n\nEl .22LR se usaba como una bala comercial para la caza de animales pequeños y para tiro recreativo.\n\nTiene un cebo 'de percusión anular' autónomo y, por lo tanto, no se puede descomponer para obtener cebos de pistola pequeña, ni se puede fabricar."
lang["#22LR_HP_DESC"] = "El .22LR es un cartucho de rifle de muy baja potencia, que se encuentra comúnmente en el uso de rifles y pistolas.\n\nVariante de Punta Hueca\n\nUsado principalmente para la caza de animales pequeños y control de plagas, estas balas se expanden en objetivos blandos para una mayor letalidad, pero fallan hopelessly contra la armadura y la ropa muy almidonada."
lang["#22LR_PLINK_DESC"] = "El .22LR es un cartucho de rifle de muy baja potencia, que se encuentra comúnmente en el uso de rifles y pistolas. Una bala de fabricación barata, incluso para .22LR, la munición plinking se produjo en masa para 'cantidad sobre calidad'.\n\nAunque es menos potente, precisa y fiable que la munición .22LR estándar, la munición plinking generalmente se puede encontrar en abundancia."
lang["#2MM_DESC"] = "Una bala ultraligera y miniatura. Se usa en armas de propulsión electromagnética.\n\nCon una velocidad solo superada por su rareza, estos cartuchos hiperveloces son letales para todas las formas conocidas de armadura de antes de la guerra."
lang["#4.7MM_DESC"] = "Una de las formas más raras de munición disponible en el yermo, y utilizada para algunas de las armas de antes de la guerra más exclusivas.\n\nEstos cartuchos hiperveloces son letales para todas las formas conocidas de armadura de antes de la guerra."
lang["#5MM_DESC"] = "A pesar de ser una bala anticuada incluso antes de la guerra, este cartucho es utilizado por muchas armas automáticas.\n\nCompensando un bajo rendimiento de daño, la bala de 5mm tiene una alta velocidad y puede penetrar armaduras y coberturas ligeras."
lang["#5MM_AP_DESC"] = "A pesar de ser una bala anticuada incluso antes de la guerra, este cartucho es utilizado por muchas armas automáticas.\n\nVariante Perforante\n\nUsando un penetrador especialmente endurecido y una punta con forma, la naturaleza antia blindaje del 5mm se extiende aún más.\n\nEstos cartuchos hiperveloces son letales para todas las formas conocidas de armadura de antes de la guerra."
lang["#5MM_HP_DESC"] = "A pesar de ser una bala anticuada incluso antes de la guerra, este cartucho es utilizado por muchas armas automáticas.\n\nVariante de Punta Hueca\n\nUtilizada por el ejército como una bala antipersonal, estas balas se expanden en objetivos blandos para una mayor letalidad, pero fallan contra la armadura."
lang["#5.56MM_DESC"] = "Un cartucho de rifle intermedio.\n\nEsta bala ligera tiene alta velocidad y penetración adecuada.\n\nRelativamente fácil de encontrar y de precio moderado, esta bala fue adaptada del .223 para uso militar internacional."
lang["#5.56MM_AP_DESC"] = "Un cartucho de rifle intermedio.\n\nVariante Perforante\n\nEmitida casi exclusivamente a las Fuerzas Armadas, estas balas contienen un penetrador endurecido para usar contra la mayoría de las formas de armadura y cobertura ligera."
lang["#5.56MM_HP_DESC"] = "Un cartucho de rifle intermedio.\n\nVariante de Punta Hueca\n\nUna bala defensiva utilizada tanto por las fuerzas del orden como por los civiles, estas balas se expanden en objetivos blandos para una mayor letalidad, pero fallan contra la armadura."
lang["#5.56MM_MATCH_DESC"] = "Un cartucho de rifle intermedio.\n\nVariante de Precisión\n\nCargada a mano cuidadosamente con un proyectil de Grado de Precisión, esta bala supera con creces a la munición producida en masa tanto en precisión como en exactitud a larga distancia."
lang["#223_DESC"] = "Un cartucho de rifle intermedio.\n\nEsta bala se puede usar en cualquier arma recamarada para 5.56.\n\n.223 y 5.56 son cartuchos de rifle con cuello de botella, que comparten el mismo diámetro de bala. El primero, sin embargo, es menos potente y causa menos desgaste a las armas de fuego."
lang["#223_ND_DESC"] = "Un cartucho de rifle ligeramente oxidado.\n\nEsta bala se puede usar en cualquier arma recamarada para 5.56mm.\n\n#STARTER_AMMO_DISCLAIMER"
lang["#7.62MM_DESC"] = "Un cartucho de rifle intermedio.\n\nUna bala calibre 30 con una carga moderada, su nombre métrico delata su origen extranjero."
lang["#7.62MM_AP_DESC"] = "Un cartucho de rifle intermedio.\n\nUna bala calibre 30 con una carga moderada, esta tiene un proyectil perforante."
lang["#7.62MM_MATCH_DESC"] = "Un cartucho de rifle intermedio.\n\nUna variante de Precisión, cargada a mano cuidadosamente para un rendimiento mejorado."
lang["#9X39MM_DESC"] = "Un cartucho subsónico de alto calibre diseñado para el sigilo y la precisión, el 9x39mm es apreciado por los habitantes del yermo que prefieren operar en las sombras. Desarrollado originalmente por la Unión Soviética de antes de la guerra para su uso con rifles silenciados, esta bala es perfecta para derribos silenciosos y es capaz de atravesar armaduras ligeras con facilidad. Aunque es raro de encontrar, puede cambiar las reglas del juego en las manos adecuadas."
lang["#9X39MM_AP_DESC"] = "Un cartucho subsónico de alto calibre diseñado para el sigilo y la precisión, el 9x39mm es apreciado por los habitantes del yermo que prefieren operar en las sombras. Desarrollado originalmente por la Unión Soviética de antes de la guerra para su uso con rifles silenciados, esta bala es perfecta para derribos silenciosos y es capaz de atravesar armaduras ligeras con facilidad. Esta es la variante perforante.\n\nBastante devastadora para cualquier objetivo desprevenido."
lang["#308_DESC"] = "Un cartucho de rifle popular, que se encuentra comúnmente en el uso de deportistas y ejércitos.\n\nConocido internacionalmente como 7.62x51mm, estas balas completamente encamisadas se vendían como una alternativa más asequible a las balas de caza comunes de la época."
lang["#308_AP_DESC"] = "Un cartucho de rifle popular, que se encuentra comúnmente en el uso de deportistas y ejércitos.\n\nVariante Perforante\n\nEmitida casi exclusivamente a las Fuerzas Armadas, estas balas contienen un penetrador endurecido para usar contra la mayoría de las formas de armadura y cobertura ligera."
lang["#308_HP_DESC"] = "Un cartucho de rifle popular, que se encuentra comúnmente en el uso de deportistas y ejércitos.\n\nVariante de Caza\n\nDiseñado para animales medianos a grandes, las puntas blandas se expanden al impactar, abatiendo a la presa de manera rápida y efectiva.\n\nLa eficacia se resiente contra la armadura."
lang["#308_MATCH_DESC"] = "Un cartucho de rifle popular, que se encuentra comúnmente en el uso de deportistas y ejércitos.\n\nVariante de Precisión\n\nCargada a mano cuidadosamente con un proyectil de Grado de Precisión, esta bala supera con creces a la munición producida en masa tanto en precisión como en exactitud a larga distancia."
lang["#308_DESC"] = "Un cartucho de rifle popular, que se encuentra comúnmente en el uso de deportistas y ejércitos.\n\nConocido internacionalmente como 7.62x51mm, estas balas completamente encamisadas se vendían como una alternativa más asequible a las balas de caza comunes de la época."
lang["#3006_DESC"] = "Antes de la guerra, la munición .30-06 era un elemento básico de las fuerzas militares, un cartucho de rifle potente y de tamaño completo utilizado originalmente en el M1 Garand del Ejército de los EE. UU. y otros rifles de alta potencia. Aunque la mayor parte de la producción cesó después de la Gran Guerra, estos cartuchos todavía son apreciados por los francotiradores del Yermo por su poder de parada y fiabilidad cuando puedes encontrarlos."
lang["#3006_MATCH_DESC"] = "Antes de la guerra, la munición .30-06 era un elemento básico de las fuerzas militares, un cartucho de rifle potente y de tamaño completo utilizado originalmente en el M1 Garand del Ejército de los EE. UU. y otros rifles de alta potencia. Aunque la mayor parte de la producción cesó después de la Gran Guerra, estos cartuchos todavía son apreciados por los francotiradores del Yermo por su poder de parada y fiabilidad cuando puedes encontrarlos.\n\nVariante de Precisión"
lang["#3006AP_DESC"] = "Un cartucho de rifle de longitud completa y cuello de botella, la bala .30-06 M2 AP presenta un núcleo de acero endurecido asentado en una bala de punta negra, completamente encamisada, engarzada en una vaina larga de latón con una ligera conicidad en el hombro. La longitud total y la carga de pólvora le dan una impresionante velocidad inicial, haciéndola mortalmente precisa a larga distancia."

lang["#4570_DESC"] = "Un cartucho de rifle antiguo, todavía en uso hoy en día.\n\nEsta atemporal bala se considera adecuada para cualquier caza mayor de América del Norte.\n\nDesarrollado originalmente hace más de 400 años para su uso con pólvora negra, el .45-70 es uno de los primeros cartuchos militares de EE. UU."
lang["#4570_HP_DESC"] = "Un cartucho de rifle antiguo, todavía en uso hoy en día.\n\nVariante de Caza\n\nDiseñado para animales medianos a grandes, las puntas blandas se expanden al impactar, abatiendo a la presa de manera rápida y efectiva.\n\nLa eficacia se resiente contra la armadura."
lang["#4570_HC_DESC"] = "Un cartucho de rifle antiguo, todavía en uso hoy en día.\n\nVariante de Caza Mayor\n\nDiseñado para ser usado contra cosas más grandes, rápidas y mortales que tú, las balas de Punta Plana de Plomo Fundido usan un proyectil endurecido con la máxima carga posible para perforar la piel engrosada de los animales.\n\nEsta potente bala es difícil de encontrar y acorta drásticamente la vida útil del arma de fuego."
lang["#50BMG_DESC"] = "La .50 Browning Machine Gun es un cartucho monstruosamente pesado, utilizado exclusivamente en armas antimaterial y montadas en vehículos.\n\nEsta bala producida en masa, aunque de diseño simple, entrega una carga devastadora."
lang["#50BMG_MATCH_DESC"] = "La .50 Browning Machine Gun es un cartucho monstruosamente pesado, utilizado exclusivamente en armas antimaterial y montadas en vehículos.\n\nVariante de Precisión\n\nCargada a mano cuidadosamente con un proyectil de Grado de Precisión, esta bala supera con creces a la munición producida en masa tanto en precisión como en exactitud a larga distancia."
--CARTUCHOS DE ESCOPETA
lang["#12G_SLUG_DESC"] = "Una posta estriada, para usar en escopetas de ánima lisa.\n\nRequeriendo una cantidad considerable de plomo por cartucho, este proyectil masivo fue diseñado para la caza de animales medianos y grandes."
lang["#12G_PSLUG_DESC"] = "Estas postas causan más daño a los robots y enemigos que usan servoarmadura, y el objetivo recibe una patada adicional de un pulso electromagnético activado por el impacto."
lang["#12G_DESC"] = "Un cartucho usado en escopetas.\n\nEl daño se divide entre un grupo de perdigones, lo que lo hace devastador para objetivos blandos, pero más o menos rebota en armaduras pesadas."
lang["#12G3_SLUG_DESC"] = "Una posta estriada Magnum, para usar en escopetas de ánima lisa.\n\nLa mayor carga de pólvora y la posta de cobre sólido de este cartucho significan mayores velocidades, mayor daño y mejor penetración contra armaduras medianas.\n\nLos inconvenientes son un mayor retroceso, desgaste prematuro del arma, y da una patada como un maldito Bighorner."
lang["#12G3_DESC"] = "Un cartucho Magnum usado en escopetas de ánima lisa.\n\nLa mayor carga de pólvora y los perdigones chapados en cobre de este cartucho significan mayores velocidades, mayor daño y mejor penetración contra armaduras ligeras.\n\nLos inconvenientes son un mayor retroceso, desgaste prematuro del arma, y da una patada como un maldito Bighorner."
lang["#12G_FLECHETTE_DESC"] = "Un cartucho perforante especial para escopetas.\n\nLos flechetes son pequeños dardos de metal ideales para perforar armaduras ligeras. Aunque no son tan letales como los perdigones, los flechetes sirven como una respuesta eficaz a las armaduras corporales.\n\nDeben dispararse con ánima lisa y, por lo tanto, son incompatibles con estranguladores estriados."
lang["#12G_DRAGONS_BREATH_DESC"] = "Una caja marcada con letras orientales y un dragón que contiene cartuchos rellenos de perdigones de magnesio y perdigón de ave que se encienden al hacer contacto con el aire. Devastador para objetivos blandos e incluso para objetivos duros que tienen carne expuesta."
--MUNICIÓN PESADA
lang["#ROCKET_DESC"] = "Un cohete con una gran ojiva explosiva."
lang["#ROCKET_CANISTER_DESC"] = "Un cohete con una gran cantidad de metralla cargada en su interior."
lang["#MISSILEHE_DESC"] = "Un misil de Alto Explosivo, destinado a ser disparado desde un lanzamisiles."
lang["#MININUKE_DESC"] = "Una ojiva atómica en miniatura, se puede disparar tal cual desde un FatMan, o usarse en artesanías de variedad destructiva."
lang["#25MM_DESC"] = "Una granada de 25mm diseñada para un lanzador militar de antes de la guerra, explota al contacto.\n\nEn contraste con el uso más específico de los misiles, estas a menudo se disparaban en rápida sucesión para efecto de área."
lang["#40MM_DESC"] = "Una granada de 40mm."
lang["#FUELGAS_DESC"] = "Un cilindro que contiene un combustible líquido extremadamente inflamable para lanzallamas."
lang["#FUELNAPALM_DESC"] = "Un cilindro que contiene un combustible líquido extremadamente inflamable para lanzallamas.\n\nEste combustible para lanzallamas utiliza una mezcla avanzada de súper combustión."
lang["#FUELHOMEMADE_DESC"] = "Un cilindro que contiene un combustible líquido extremadamente inflamable para lanzallamas.\n\nImprovisado con materiales crudos, esta fórmula funciona extremadamente sucia y degradará el arma a un ritmo alarmante."

---OTROS
lang["#DART_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales."
lang["#DART_STIM_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Apoyo\n\nConteniendo una dosis parcial de la droga milagrosa de antes de la guerra, los Stimdards son útiles como una forma de 'primeros auxilios de largo alcance'."
lang["#DART_RADSCOPRION_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Veneno\n\nLleno de veneno del temible Mutascorpius, asegúrate de advertir a tu objetivo 'esto puede picar un poco'."
lang["#DART_CONCENTRATEDRADSCOPRION_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Veneno\n\nLleno de veneno concentrado del temible Mutascorpius, asegúrate de advertir a tu objetivo 'esto va a doler MUCHO'."
lang["#DART_GREENGECKO_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Veneno\n\nLleno de veneno del Gecko Verde, actúa rápidamente, pero no dura mucho."
lang["#DART_CONCENTRATEDGREENGECKO_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Veneno\n\nLleno de veneno concentrado del Gecko Verde, actúa rápidamente y mata especialmente rápido."
lang["#DART_FEVCURLING11_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nLa undécima prueba del Virus Evolutivo Forzado fue un fracaso, pero el Enclave lo usa para causar daño orgánico que incapacita temporalmente a un objetivo.\n\nSolo un monstruo usaría esto en otras personas."
lang["#DART_FATIGUE_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Veneno\n\nContiene una dosis para cansar a la gente de correr."
lang["#DART_BLIGHT_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Veneno\n\nContiene un lodo repugnante de líquido verde viscoso. Seguramente esto no puede ser bueno para ti."
lang["#DART_BLIGHT_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Veneno\n\nContiene un lodo repugnante de líquido verde viscoso. En su forma concentrada parece más un sólido."
lang["#DART_RAD_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Veneno\n\nCargado con líquido radiactivo, estos 'dardos sucios' se usan mejor contra objetivos humanos, no mutantes."
lang["#DART_SBLOCK_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante Contraapoyo\n\nUn cóctel de drogas especializado diseñado para suprimir la capacidad de curación del cuerpo, haciendo que los objetos curativos consumidos por el objetivo, como los stimpaks, sean temporalmente inútiles."
lang["#DART_CBLOCK_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante Contraapoyo\n\nUn cóctel de drogas especializado diseñado para suprimir el sistema adrenal del cuerpo, haciendo que los químicos de combate consumidos por el objetivo, como el Buffout, sean temporalmente inútiles."
lang["#DART_PSYCHO_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Apoyo\n\nConteniendo una dosis parcial de la droga de combate de antes de la guerra, los Psychodards se usan para proporcionar un impulso temporal a los amigos sin el riesgo de adicción."
lang["#DART_BUFFOUT_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Apoyo\n\nConteniendo una dosis parcial del esteroide de antes de la guerra, los Buffdards se usan para proporcionar un impulso temporal de S.P.E.C.I.A.L. a los amigos sin el riesgo de adicción."
lang["#DART_SLOTH_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante Contraapoyo\n\nContiene los ingredientes del tranquilizante. Es poco probable que duerma a un enemigo activo de inmediato, pero debería ralentizarlos lo suficiente como para ser cazados como presas."
lang["#DART_HYDRA_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Apoyo\n\nConteniendo una dosis parcial de la droga improvisada del yermo, los Hydradards se usan para reparar rápidamente las extremidades rotas de los amigos sin el riesgo de adicción."
-- lang["#DART_GOBLIN_DESC"] = "Un dardo balístico con punta de aguja hipodérmica y un depósito hueco que se asemeja a una jeringa, para usar en pistolas de aire comprimido especiales.\n\nVariante de Veneno\n\n''Prueba a agarrar estos huevos'' - Dictador"
lang["#RAILSPIKE_DESC"] = "Un clavo grande, destinado a clavar nuevas vías de tren. Son capaces de penetrar el acero y otros materiales duraderos. Desafortunadamente, no puedes trabajar exactamente en ningún tren en Fallout: Resurgence.\n\nSupongo que tendrás que disparar a la gente con ellos."
lang["#RAILSPIKE_SPIKY_DESC"] = "Un clavo grande, con varias púas soldadas. Se enganchará un poco en la armadura, pero destrozará completamente la carne de las personas.\n\nNota: Solo causarán sangrado cuando se dispare a seres con alma."
lang["#RAILSTAKE_DESC"] = "Un clavo muy, muy, muy grande, que ya no está destinado a clavar vías de tren. Son capaces de penetrar tanques, y más aún armaduras.\n\nSin embargo, son grandes y difíciles de manejar; no estás seguro de si encajarán fácilmente en un Rifle de Ferrocarril."

-- Nombres de Granada
lang["#FRAGGRENADE_NAME"] = "Granada de Fragmentación"
lang["#BASEBALLGRENADE_NAME"] = "Granada de Béisbol"
lang["#SHORTFUSE_NAME"] = "Granada de Mecha Corta"
lang["#PLASGRENADE_NAME"] = "Granada de Plasma"
lang["#NUKAGRENADE_NAME"] = "Granada Nuka"
lang["#TINGRENADE_NAME"] = "Granada de Lata"
lang["#MFCGRENADE_NAME"] = "Granada MFC"
lang["#TIMEBOMB_NAME"] = "Bomba de Tiempo"
lang["#TIMEBOMBHY_NAME"] = "Bomba de Tiempo, Alto Rendimiento"
lang["#DYNO_NAME"] = "Dinamita"
lang["#DYNOLF_NAME"] = "Dinamita, Mecha Larga"
lang["#GRENADEFLAME_NAME"] = "Granada Incendiaria"
lang["#MOLOTOV_NAME"] = "Bomba Molotov"
-- Descripciones de Granada
lang["#FRAGGRENADE_DESC"] = "Un pequeño explosivo de mano.\n\nSe fragmenta en metralla, haciendo que el rango letal de la explosión sea bastante grande.\n\nRetira el pasador y lanza."
lang["#BASEBALLGRENADE_DESC"] = "Béisboles ahuecados llenos de una Bomba Cereza, Pólvora de Pistola y Fertilizante, que actúan como una mezcla explosiva improvisada. De baja tecnología y fácil de hacer, la granada de béisbol causa daño explosivo moderado a los enemigos cercanos."
lang["#SHORTFUSE_DESC"] = "Un pequeño explosivo de mano.\n\nSe fragmenta en metralla, haciendo que el rango letal de la explosión sea bastante grande.\n\nParece haber sido manipulado. Tiene una mecha muy corta."
lang["#PLASGRENADE_DESC"] = "Un dispositivo explosivo que produce una explosión de plasma sobrecalentado.\n\nDonde carece de fragmentación y radio de explosión, lo compensa con creces con el daño."
lang["#NUKAGRENADE_DESC"] = "Un dispositivo explosivo improvisado extremadamente poderoso.\n\nIncorpora las propiedades radiactivas de una variante de Nuka-Cola relativamente rara para producir una explosión de plasma mejorada.\n\n#WIP_DESC"
lang["#TINGRENADE_DESC"] = "La granada de lata es un dispositivo explosivo arrojadizo improvisado,\nse crea en un banco de trabajo y se ensambla a partir de chatarra.\n\nUna lata se usa tanto para la carcasa como para la metralla, pólvora de pistola para el explosivo y cinta aislante para mantenerlo todo junto.\n\n#WIP_DESC"
lang["#MFCGRENADE_DESC"] = "Un arma improvisada poderosa hecha de Células de Microfusión modificadas.\n\nMenos dañina que una Granada de Plasma verdadera, pero con un área de efecto más amplia.\n\n#WIP_DESC"
lang["#TIMEBOMB_DESC"] = "Un arma explosiva improvisada hecha con varios cartuchos de dinamita.\n\nTemporizador de 15 segundos.\n\n''Configúrala, NO la olvides''."
lang["#TIMEBOMBHY_DESC"] = "Un arma explosiva improvisada hecha con varios cartuchos de dinamita.\n\nTemporizador de 15 segundos.\n\nPones más, obtienes más."
lang["#DYNO_DESC"] = "Cartuchos con mechas que sobresalen de ellos. Una vez encendidos, se lanzan a un hostil y lo dañarán o matarán.\n\nUtilizado principalmente en las industrias minera, de canteras, construcción y demolición; tiene un radio de explosión bastante pequeño para un explosivo, lo que reduce su efectividad contra grupos de enemigos.\n\n#WIP_DESC"
lang["#DYNOLF_DESC"] = "Cartuchos con mechas que sobresalen de ellos. Una vez encendidos, se lanzan a un hostil y lo dañarán o matarán.\n\nUtilizado principalmente en las industrias minera, de canteras, construcción y demolición; tiene un radio de explosión bastante pequeño para un explosivo, lo que reduce su efectividad contra grupos de enemigos.\n\nEsta versión tiene una mecha el doble de larga.\n\n#WIP_DESC"
lang["#GRENADEFLAME_DESC"] = "La Granada Incendiaria AN-2051 es un dispositivo explosivo arrojadizo que se enciende después de una pequeña demora.\n\nLos objetivos atrapados en el radio de la explosión sufrirán daño por fuego y continuarán ardiendo durante varios segundos después de la detonación inicial.\n\nÚtil para negar área y matar cosas con fuego."
lang["#MOLOTOV_DESC"] = "Un explosivo arrojadizo improvisado que estalla en una bola de fuego al contacto.\n\nLa botella está llena de una sustancia inflamable, como aceite o gasolina, y rematada con una tapa y un paño como encendedor.\n\nSolo enciende y lanza, pequeño pirómano.\n\n#WIP_DESC"

-- Nombres de Mina
lang["#FRAGMINE_NAME"] = "Mina de Fragmentación"
lang["#PLASMAMINE_NAME"] = "Mina de Plasma"
lang["#POWDERCHARGE_NAME"] = "Carga de Pólvora"
lang["#FLAMEMINE_NAME"] = "Mina Incendiaria"
lang["#FATMINE_NAME"] = "Mina Gorda"
lang["#BCMINE_NAME"] = "Mina de Chapas"

-- Descripciones de Mina
lang["#FRAGMINE_DESC"] = "Un arma explosiva de antes de la guerra utilizada para negar área. Una vez activada, explotará si se toca, o si su temporizador de proximidad termina, explotando al infractor con metralla.\n\nTrata de no conseguir un nuevo piercing."
lang["#PLASMAMINE_DESC"] = "Un arma explosiva de alta tecnología utilizada para negar área. Una vez activada, explotará si se toca, o si su temporizador de proximidad termina, explotando al infractor con fuego de plasma.\n\nNo te hagas derretir la cara."
lang["#POWDERCHARGE_DESC"] = "Un arma explosiva improvisada utilizada para negar área. Una vez activada, explotará si se toca, o si su temporizador de proximidad termina, explotando al infractor con cualquier cosa que hayas metido dentro.\n\nEspero que tu cableado sea bueno.\n\n#WIP_DESC"
lang["#FLAMEMINE_DESC"] = "Un arma explosiva de antes de la guerra utilizada para negar área. Una vez activada, explotará si se toca, o si su temporizador de proximidad termina, cubriendo el área con napalm encendido.\n\nNo quemes el vecindario, chico.\n\n#WIP_DESC"
lang["#FATMINE_DESC"] = "Un arma de fusión improvisada utilizada para negar área. Una vez activada, explotará si se toca, o si su temporizador de proximidad termina, explotando al infractor con el poder de un pequeño Sol.\n\n¿Qué clase de monstruo crearía esto?\n\n#WIP_DESC"
lang["#BCMINE_DESC"] = "Un arma explosiva improvisada disfrazada de basura. Una vez activada, explotará si se toca, o si su temporizador de proximidad termina, explotando al infractor con cambio suelto.\n\n(La nota escrita a mano de mamá no está incluida)\n\n#WIP_DESC"

RELOADSCHEMA = true