local lang = RSRG.Languages["ru"]

lang["#CONTROL_BINDCHECKER_TITLE"] = "Обнаружены неназначенные клавиши!"
lang["#CONTROL_BINDCHECKER_SUBTITLE"] = "Resurgence заменяет стандартное управление Garry's Mod. Если эти клавиши не назначены, у вас возникнут сложности с игрой."
lang["#CONTROL_BINDCHECKER_FOOTNOTE"] = "Нажмите \"Открыть меню Garry's Mod\", перейдите в \"Настройки\", выберите \"Клавиатура\" и назначьте эти клавиши или нажмите \"Сброс\" для оптимальной игры.\nПосле завершения нажмите \"Проверить управление\"."
lang["#CONTROL_BINDCHECKER_REVALIDATE"] = "Проверить управление"
lang["#CONTROL_BINDCHECKER_OPENMENU"] = "Открыть меню Garry's Mod"
lang["#CONTROL_BINDCHECKER_PLAYANYWAY"] = "Играть в любом случае"
lang["#CONTROL_BINDCHECKER_PLAYANYWAY_CONFIRM"] = "Вы уверены, что хотите играть без назначения этих клавиш?\nВозможны ошибки или невозможность игры."
lang["#CONTROL_BINDCHECKER_NOTVALIDATED"] = "Всё ещё обнаружены неназначенные клавиши."
lang["#CONTROL_BINDCHECKER_VALIDATED"] = "Все клавиши назначены!\nТеперь вы можете играть."

lang["#CONTROL_AMMOTYPE"] = "Смена типа боеп. / Меню оружия (удерж.)"
lang["#CONTROL_MELEENADE"] = "Силовая атака в ближнем бою / Приклад / Граната (удерж.)"
lang["#CONTROL_ACCEPTINVITE"] = "Принять приглашение"
lang["#CONTROL_DECLINEINVITE"] = "Отклонить приглашение"
lang["#CONTROL_COMMUNITY"] = "Открыть меню сообщества"
lang["#CONTROL_CAMERA"] = "Режим камеры"
lang["#CONTROL_PING"] = "Сигнал группы"
lang["#CONTROL_PIPBOY"] = "Открыть ПИП-Бой / Вкл./откл. фонарик (удерж.)"
lang["#CONTROL_INTERACT"] = "Взаимодействие"
lang["#CONTROL_ATTACK"] = "Атака / Выстрел"
lang["#CONTROL_AIM"] = "Прицеливание / Парирование"
lang["#CONTROL_RELOAD"] = "Перезарядка / Взять/убрать оружие (удерж.)"
lang["#CONTROL_HOTKEY1"] = "Горячая клавиша 1"
lang["#CONTROL_HOTKEY2"] = "Горячая клавиша 2"
lang["#CONTROL_HOTKEY3"] = "Горячая клавиша 3"
lang["#CONTROL_HOTKEY4"] = "Горячая клавиша 4"
lang["#CONTROL_HOTKEY5"] = "Горячая клавиша 5"
lang["#CONTROL_HOTKEY6"] = "Горячая клавиша 6"
lang["#CONTROL_HOTKEY7"] = "Горячая клавиша 7"
lang["#CONTROL_HOTKEY8"] = "Горячая клавиша 8"
lang["#CONTROL_HOTKEY9"] = "Горячая клавиша 9"
lang["#CONTROL_ZOOMIN"] = "Приблизить"
lang["#CONTROL_ZOOMOUT"] = "Отдалить"

lang["#BINDING_PURPOSE"] = "Назначение Resurgence: $control"
lang["#BINDING_DEFAULT"] = "По умолчанию: $key"
lang["#BINDING_CURRENT"] = "Текущее назначение: $command"

-- Shows as "currently bound to Nothing in the bind checker"
lang["#BINDING_NOTHING"] = "ничего"

RELOADSCHEMA = true
